In [2]:
install.packages("extrafont")
library(extrafont)
system("sudo apt-get install fonts-nanum-coding")
font_import(pattern="Nanum" )

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘extrafontdb’, ‘Rttf2pt1’


Registering fonts with R

Importing fonts may take a few minutes, depending on the number of fonts and the speed of the system.
Continue? [y/n] y

Scanning ttf files in /usr/share/fonts/, /usr/local/share/fonts/ ...

Extracting .afm files from .ttf files...

/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumBarunGothic

/usr/share/fonts/truetype/nanum/NanumBarunGothicBold.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumBarunGothicBold

/usr/share/fonts/truetype/nanum/NanumGothic.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumGothic

/usr/share/fonts/truetype/nanum/NanumGothicBold.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumGothicBold

/usr/share/fonts/truetype/nanum/NanumGothicCoding.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumGothicCoding

/usr/share/fonts/truetype/nanum/NanumGothicCodingBold.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumGothicCodingBold

/usr/share/fonts/truetype/nanum/NanumMyeongjo.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumMyeongjo

/usr/share/fonts/truetype/nanum/NanumMyeongjoBold.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumMyeongjoBold

/usr/share/fonts/truetype/nanum/NanumSquareB.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumSquareB

/usr/share/fonts/truetype/nanum/NanumSquareR.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumSquareR

/usr/share/fonts/truetype/nanum/NanumSquareRoundB.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumSquareRoundB

/usr/share/fonts/truetype/nanum/NanumSquareRoundR.ttf
 => /usr/local/lib/R/site-library/extrafontdb/metrics/NanumSquareRoundR

Found FontName for 12 fonts.

Scanning afm files in /usr/local/lib/R/site-library/extrafontdb/metrics

Writing font table in /usr/local/lib/R/site-library/extrafontdb/fontmap/fonttable.csv

Writing Fontmap to /usr/local/lib/R/site-library/extrafontdb/fontmap/Fontmap...

In [1]:
library(extrafont)
fonts()

Registering fonts with R

[1] "NanumBarunGothic"         "NanumGothic"
[3] "NanumGothicCoding"        "NanumMyeongjo"
[5] "NanumSquare Bold"         "NanumSquare"
[7] "NanumSquareRound Bold"    "NanumSquareRound Regular"

In [80]:
install.packages(c("tidyverse","data.table"))

Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [81]:
library(tidyverse)
library(data.table)
library(dplyr)

## **송파구 1월 전처리**

In [82]:
#https://drive.google.com/file/d/1uDqSwEQJc5ui_wf45QiQCQJM5bSQxiAC/view?usp=sharing
system("gdown --id 1uDqSwEQJc5ui_wf45QiQCQJM5bSQxiAC")
system("ls",TRUE)

[1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
[2] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
[3] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
[4] "서울특별시 공공자전거 이용정보(일별)_22.04.csv"
[5] "공공자전거 대여소 정보(22.12월 기준).csv"
[6] "공공자전거 대여소 정보(22.12월 기준).xlsx"
[7] "일자별 날씨정보.csv"
[8] "sample_data"

In [83]:
DF01<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_22.01.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF01

Rows: 792649 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): 대여소번호, 대여소, 대여구분코드, 성별, 연령대코드, 운동량, 탄소량
dbl  (3): 이용건수, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

       대여일자   대여소번호
1      2022-01-01 00102
2      2022-01-01 00102
3      2022-01-01 00102
4      2022-01-01 00102
5      2022-01-01 00102
6      2022-01-01 00102
7      2022-01-01 00102
8      2022-01-01 00102
9      2022-01-01 00102
10     2022-01-01 00102
11     2022-01-01 00102
12     2022-01-01 00102
13     2022-01-01 00102
14     2022-01-01 00102
15     2022-01-01 00102
16     2022-01-01 00102
17     2022-01-01 00102
18     2022-01-01 00102
19     2022-01-01 00102
20     2022-01-01 00102
21     2022-01-01 00103
22     2022-01-01 00103
23     2022-01-01 00103
24     2022-01-01 00103
25     2022-01-01 00103
26     2022-01-01 00103
27     2022-01-01 00103
28     2022-01-01 00103
29     2022-01-01 00103
30     2022-01-01 00103
⋮      ⋮          ⋮
792620 2022-01-31 05074
792621 2022-01-31 05074
792622 2022-01-31 05074
792623 2022-01-31 05074
792624 2022-01-31 05074
792625 2022-01-31 05074
792626 2022-01-31 05074
792627 2022-01-31 05074
792628 2022-01-31 05075
792629 2022-01-31 05075
792630 2022-01-31 05075
792631 2022-01-31 05075
792632 2022-01-31 05075
792633 2022-01-31 05075
792634 2022-01-31 05075
792635 2022-01-31 05075
792636 2022-01-31 05075
792637 2022-01-31 05075
792638 2022-01-31 05301
792639 2022-01-31 05301
792640 2022-01-31 05301
792641 2022-01-31 05301
792642 2022-01-31 05301
792643 2022-01-31 05301
792644 2022-01-31 05301
792645 2022-01-31 05301
792646 2022-01-31 05301
792647 2022-01-31 05301
792648 2022-01-31 05301
792649 2022-01-31 09999
       대여소
1      102. 망원역 1번출구 앞
2      102. 망원역 1번출구 앞
3      102. 망원역 1번출구 앞
4      102. 망원역 1번출구 앞
5      102. 망원역 1번출구 앞
6      102. 망원역 1번출구 앞
7      102. 망원역 1번출구 앞
8      102. 망원역 1번출구 앞
9      102. 망원역 1번출구 앞
10     102. 망원역 1번출구 앞
11     102. 망원역 1번출구 앞
12     102. 망원역 1번출구 앞
13     102. 망원역 1번출구 앞
14     102. 망원역 1번출구 앞
15     102. 망원역 1번출구 앞
16     102. 망원역 1번출구 앞
17     102. 망원역 1번출구 앞
18     102. 망원역 1번출구 앞
19     102. 망원역 1번출구 앞
20     102. 망원역 1번출구 앞
21     103. 망원역 2번출구 앞
22     103. 망원역 2번출구 앞
23     103. 망원역 2번출구 앞
24     103. 망원역 2번출구 앞
25     103. 망원역 2번출구 앞
26     103. 망원역 2번출구 앞
27     103. 망원역 2번출구 앞
28     103. 망원역 2번출구 앞
29     103. 망원역 2번출구 앞
30     103. 망원역 2번출구 앞
⋮      ⋮
792620 5074. 마곡엠밸리14단지 버스정류장(마곡엠밸리11,12단지상가방면)
792621 5074. 마곡엠밸리14단지 버스정류장(마곡엠밸리11,12단지상가방면)
792622 5074. 마곡엠밸리14단지 버스정류장(마곡엠밸리11,12단지상가방면)
792623 5074. 마곡엠밸리14단지 버스정류장(마곡엠밸리11,12단지상가방면)
792624 5074. 마곡엠밸리14단지 버스정류장(마곡엠밸리11,12단지상가방면)
792625 5074. 마곡엠밸리14단지 버스정류장(마곡엠밸리11,12단지상가방면)
792626 5074. 마곡엠밸리14단지 버스정류장(마곡엠밸리11,12단지상가방면)
792627 5074. 마곡엠밸리14단지 버스정류장(마곡엠밸리11,12단지상가방면)
792628 5075. 등촌역 1번출구
792629 5075. 등촌역 1번출구
792630 5075. 등촌역 1번출구
792631 5075. 등촌역 1번출구
792632 5075. 등촌역 1번출구
792633 5075. 등촌역 1번출구
792634 5075. 등촌역 1번출구
792635 5075. 등촌역 1번출구
792636 5075. 등촌역 1번출구
792637 5075. 등촌역 1번출구
792638 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792639 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792640 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792641 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792642 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792643 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792644 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792645 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792646 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792647 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792648 5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
792649 상담센터
       대여구분코드 성별 연령대코드 이용건수 운동량 탄소량 이동거리(M)
1      일일(비회원) \\N  기타       1        48.46  0.44    1882.85
2      일일(회원)   \\N  20대       3        995.14 8.16   35143.85
3      일일(회원)   \\N  30대       2        92.04  1.06    4535.15
4      일일(회원)   \\N  40대       1        \\N    \\N        0.00
5      일일(회원)   F    20대       1        41.70  0.38    1620.00
6      일일(회원)   F    30대       1        22.45  0.26    1111.79
7      일일(회원)   F    기타       1        38.61  0.35    1500.00
8      일일(회원)   M    40대       1        80.51  0.69    2990.00
9      일일(회원)   M    50대       1        0.00   0.00       0.00
10     일일(회원)   M    기타       1        18.69  0.17     725.99
11     정기         \\N  20대       3        41.93  0.43    1825.38
12     정기         \\N  30대       4        247.17 1.74    7476.79
13     정기         \\N  40대       1        0.00   0.00       0.00
14     정기         F    20대       3        75.30  0.87    3788.36
15     정기         F    30대       4        104.14 1.10    4756.41
16     정기         F    50대       1        67.95  0.66    2860.00
17     정기         F    기타       2        16.24  0.19     820.00
18     정기         M    20대       2        21.10  0.17     730.00
19     정기         M    30대       6        428.43 3.25   13981.33
20     정기         M    60대       1        19.22  0.16     693.23
21     단체         F    20대       2        79.99  0.72    3107.49
22     일일(회원)   \\N  10대       1        118.92 1.18    5090.00
23     일일(회원)   \\N  20대       5        497.65 4.40   18930.99
24     일일(회원)   \\N  30대       1        57.45  0.54    2340.00
25     일일(회원)   F    20대       2        101.01 0.94    4064.34
26     일일(회원)   F    기타       1        152.90 1.38    5940.00
27     일일(회원)   M    20대       2        23.17  0.17     750.00
28     일일(회원)   M    30대       1        195.53 1.43    6171.96
29     일일(회원)   M    40대       1        172.15 1.33    5720.00
30     일일(회원)   M    50대       1        41.86  0.35    1510.00
⋮      ⋮            ⋮    ⋮          ⋮        ⋮      ⋮      ⋮
792620 일일(회원)   \\N  20대       1        46.76  0.33    1440.00
792621 정기         \\N  20대       1        22.43  0.19     809.06
792622 정기         \\N  30대       1        \\N    \\N        0.00
792623 정기         \\N  60대       1        621.62 5.60   24150.00
792624 정기         NA   10대       1        71.71  0.76    3292.65
792625 정기         F    20대       1        29.44  0.27    1143.63
792626 정기         F    60대       1        26.77  0.24    1040.00
792627 정기         M    10대       1        38.02  0.35    1500.00
792628 일일(회원)   M    10대       1        0.00   0.00       0.00
792629 일일(회원)   M    30대       1        43.11  0.51    2177.42
792630 정기         \\N  40대       1        67.36  0.56    2430.00
792631 정기         NA   20대       1        100.92 0.94    4045.34
792632 정기         F    20대       4        38.32  0.42    1770.00
792633 정기         F    30대       1        10.51  0.14     590.00
792634 정기         F    기타       2        43.41  0.32    1370.00
792635 정기         M    20대       2        51.80  0.43    1860.00
792636 정기         M    30대       1        37.62  0.23    1000.00
792637 정기         M    기타       1        0.00   0.00       0.00
792638 일일(회원)   \\N  30대       1        206.72 1.86    8031.07
792639 일일(회원)   NA   20대       1        16.41  0.17     714.59
792640 일일(회원)   M    20대       1        45.11  0.41    1780.00
792641 일일(회원)   M    30대       1        0.00   0.00       0.00
792642 정기         \\N  20대       3        47.43  0.41    1796.35
792643 정기         \\N  30대       1        23.48  0.17     741.06
792644 정기         F    20대       1        0.00   0.00       0.00
792645 정기         F    40대       1        29.52  0.35    1491.12
792646 정기         M    20대       3        39.97  0.40    1694.65
792647 정기         M    40대       1        0.00   0.00       0.00
792648 정기         M    50대       1        34.92  0.34    1469.90
792649 일일(회원)   M    40대       1        277.37 1.83    7870.00
       이용시간(분)
1       49
2      251
3       33
4       20
5        6
6       51
7       16
8       19
9       34
10      16
11      34
12      39
13      29
14      37
15      91
16      18
17      94
18      15
19     144
20      16
21      89
22      46
23     295
24      10
25      59
26     152
27      46
28     151
29      34
30       6
⋮      ⋮
792620   9
792621   4
792622  10
792623 115
792624  28
792625   8
792626   9
792627   9
792628  85
792629  13
792630  18
792631  23
792632  16
792633   5
792634   6
792635   9
792636   5
792637   3
792638  53
792639   6
792640  12
792641  49
792642  28
792643   5
792644  12
792645  15
792646  13
792647  20
792648  14
792649  50

In [84]:
DF01$대여소번호 <- as.numeric(DF01$대여소번호)

In [85]:
#송파구 1월 대여소 filter

f_DF01<-DF01%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897))
f_DF01

      대여일자   대여소번호 대여소                        대여구분코드 성별
1     2022-01-01 1201       1201. 가락시장역 3번 출구     일일(회원)   NA
2     2022-01-01 1201       1201. 가락시장역 3번 출구     정기         \\N
3     2022-01-01 1201       1201. 가락시장역 3번 출구     정기         \\N
4     2022-01-01 1201       1201. 가락시장역 3번 출구     정기         \\N
5     2022-01-01 1201       1201. 가락시장역 3번 출구     정기         \\N
6     2022-01-01 1201       1201. 가락시장역 3번 출구     정기         NA
7     2022-01-01 1201       1201. 가락시장역 3번 출구     정기         F
8     2022-01-01 1201       1201. 가락시장역 3번 출구     정기         F
9     2022-01-01 1201       1201. 가락시장역 3번 출구     정기         F
10    2022-01-01 1201       1201. 가락시장역 3번 출구     정기         F
11    2022-01-01 1201       1201. 가락시장역 3번 출구     정기         M
12    2022-01-01 1201       1201. 가락시장역 3번 출구     정기         M
13    2022-01-01 1201       1201. 가락시장역 3번 출구     정기         M
14    2022-01-01 1201       1201. 가락시장역 3번 출구     정기         M
15    2022-01-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   \\N
16    2022-01-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   \\N
17    2022-01-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   F
18    2022-01-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   M
19    2022-01-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   M
20    2022-01-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   M
21    2022-01-01 1203       1203. 밀리아나2빌딩 앞        정기         \\N
22    2022-01-01 1203       1203. 밀리아나2빌딩 앞        정기         \\N
23    2022-01-01 1203       1203. 밀리아나2빌딩 앞        정기         \\N
24    2022-01-01 1203       1203. 밀리아나2빌딩 앞        정기         F
25    2022-01-01 1203       1203. 밀리아나2빌딩 앞        정기         F
26    2022-01-01 1203       1203. 밀리아나2빌딩 앞        정기         F
27    2022-01-01 1203       1203. 밀리아나2빌딩 앞        정기         M
28    2022-01-01 1203       1203. 밀리아나2빌딩 앞        정기         M
29    2022-01-01 1203       1203. 밀리아나2빌딩 앞        정기         M
30    2022-01-01 1203       1203. 밀리아나2빌딩 앞        정기         M
⋮     ⋮          ⋮          ⋮                             ⋮            ⋮
66043 2022-01-31 4892       4892. 성내유수지 체육공원     정기         \\N
66044 2022-01-31 4892       4892. 성내유수지 체육공원     정기         M
66045 2022-01-31 4892       4892. 성내유수지 체육공원     정기         M
66046 2022-01-31 4893       4893. 문정법조단지12          일일(회원)   F
66047 2022-01-31 4893       4893. 문정법조단지12          정기         F
66048 2022-01-31 4895       4895. 위례포레샤인15단지 상가 일일(회원)   F
66049 2022-01-31 4895       4895. 위례포레샤인15단지 상가 정기         \\N
66050 2022-01-31 4895       4895. 위례포레샤인15단지 상가 정기         \\N
66051 2022-01-31 4895       4895. 위례포레샤인15단지 상가 정기         F
66052 2022-01-31 4895       4895. 위례포레샤인15단지 상가 정기         F
66053 2022-01-31 4895       4895. 위례포레샤인15단지 상가 정기         F
66054 2022-01-31 4895       4895. 위례포레샤인15단지 상가 정기         M
66055 2022-01-31 4895       4895. 위례포레샤인15단지 상가 정기         M
66056 2022-01-31 4895       4895. 위례포레샤인15단지 상가 정기         M
66057 2022-01-31 4896       4896. 위례포레샤인15단지      일일(회원)   \\N
66058 2022-01-31 4896       4896. 위례포레샤인15단지      정기         \\N
66059 2022-01-31 4897       4897. 잠실주공5단지1          일일(회원)   \\N
66060 2022-01-31 4897       4897. 잠실주공5단지1          일일(회원)   F
66061 2022-01-31 4897       4897. 잠실주공5단지1          일일(회원)   F
66062 2022-01-31 4897       4897. 잠실주공5단지1          일일(회원)   M
66063 2022-01-31 4897       4897. 잠실주공5단지1          정기         \\N
66064 2022-01-31 4897       4897. 잠실주공5단지1          정기         \\N
66065 2022-01-31 4897       4897. 잠실주공5단지1          정기         \\N
66066 2022-01-31 4897       4897. 잠실주공5단지1          정기         NA
66067 2022-01-31 4897       4897. 잠실주공5단지1          정기         F
66068 2022-01-31 4897       4897. 잠실주공5단지1          정기         F
66069 2022-01-31 4897       4897. 잠실주공5단지1          정기         F
66070 2022-01-31 4897       4897. 잠실주공5단지1          정기         M
66071 2022-01-31 4897       4897. 잠실주공5단지1          정기         M
66072 2022-01-31 4897       4897. 잠실주공5단지1          정기         M
      연령대코드 이용건수 운동량 탄소량 이동거리(M) 이용시간(분)
1     50대       1        64.86  0.54    2340.00     17
2     20대       4        408.85 4.20   18108.43    171
3     30대       2        117.26 0.89    3845.44     39
4     40대       1        524.34 4.27   18390.00    107
5     50대       1        66.53  0.56    2400.00     20
6     20대       1        38.64  0.51    2217.79     12
7     20대       1        19.60  0.23     990.00      7
8     30대       1        34.06  0.40    1720.22     12
9     40대       1        44.10  0.40    1740.00     13
10    기타       2        38.81  0.41    1750.00     17
11    20대       1        32.00  0.23    1010.00      6
12    30대       2        689.59 6.53   28124.24    108
13    50대       1        27.95  0.26    1138.29      7
14    기타       1        22.62  0.20     878.95      6
15    10대       1        51.48  0.46    2000.07     11
16    20대       1        47.36  0.43    1840.00     12
17    50대       1        312.46 3.45   14887.59    117
18    30대       1        89.32  0.67    2891.60     19
19    40대       1        40.47  0.34    1460.00      8
20    50대       1        343.33 3.35   14450.00    117
21    30대       1        55.60  0.50    2160.00     17
22    40대       1        36.47  0.43    1841.72     12
23    50대       2        150.66 1.45    6250.00     92
24    10대       2        74.72  0.70    3038.31     15
25    30대       1        108.18 1.09    4710.00     51
26    50대       1        0.00   0.00       0.00     12
27    10대       1        29.15  0.31    1338.18     20
28    20대       2        7.29   0.05     230.00     14
29    40대       1        0.00   0.00       0.00      9
30    50대       2        51.00  0.43    1840.00     23
⋮     ⋮          ⋮        ⋮      ⋮      ⋮           ⋮
66043 20대       1        100.21 0.56    2410.00     56
66044 20대       1        66.67  0.60    2590.00     18
66045 기타       1        40.66  0.35    1510.09     12
66046 40대       1        282.97 2.96   12760.00     64
66047 30대       1        13.75  0.14     620.00      4
66048 50대       1        80.57  0.73    3130.00     59
66049 30대       1        106.14 0.96    4123.39     32
66050 50대       1        65.46  0.66    2850.00     30
66051 30대       1        81.34  0.73    3160.00     58
66052 40대       1        0.00   0.00       0.00     17
66053 50대       1        10.17  0.09     395.09      8
66054 20대       1        42.41  0.35    1530.00      7
66055 30대       1        121.17 1.09    4707.29     56
66056 40대       1        0.00   0.00       0.00      3
66057 20대       1        0.00   0.00       0.00     12
66058 20대       1        103.28 0.75    3220.00     90
66059 20대       1        0.00   0.00       0.00     56
66060 20대       1        0.00   0.00       0.00     51
66061 기타       2        0.00   0.00       0.00     16
66062 30대       1        95.14  0.71    3080.00     56
66063 10대       2        44.02  0.40    1710.00     16
66064 20대       1        16.62  0.15     645.76      3
66065 30대       2        95.89  0.69    2947.84     51
66066 30대       1        10.75  0.14     590.00      3
66067 20대       1        30.64  0.28    1190.25      9
66068 30대       3        165.04 1.77    7641.88    102
66069 기타       1        66.50  0.72    3110.00     38
66070 30대       4        139.96 1.14    4953.44     37
66071 40대       1        327.07 2.78   11970.00     80
66072 기타       2        107.34 0.97    4170.00     48

In [99]:
selected_DF01 <- f_DF01 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대코드, 이용건수)
selected_DF01

      대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수
1     2022-01-01 1201       일일(회원)   NA   50대       1
2     2022-01-01 1201       정기         \\N  20대       4
3     2022-01-01 1201       정기         \\N  30대       2
4     2022-01-01 1201       정기         \\N  40대       1
5     2022-01-01 1201       정기         \\N  50대       1
6     2022-01-01 1201       정기         NA   20대       1
7     2022-01-01 1201       정기         F    20대       1
8     2022-01-01 1201       정기         F    30대       1
9     2022-01-01 1201       정기         F    40대       1
10    2022-01-01 1201       정기         F    기타       2
11    2022-01-01 1201       정기         M    20대       1
12    2022-01-01 1201       정기         M    30대       2
13    2022-01-01 1201       정기         M    50대       1
14    2022-01-01 1201       정기         M    기타       1
15    2022-01-01 1203       일일(회원)   \\N  10대       1
16    2022-01-01 1203       일일(회원)   \\N  20대       1
17    2022-01-01 1203       일일(회원)   F    50대       1
18    2022-01-01 1203       일일(회원)   M    30대       1
19    2022-01-01 1203       일일(회원)   M    40대       1
20    2022-01-01 1203       일일(회원)   M    50대       1
21    2022-01-01 1203       정기         \\N  30대       1
22    2022-01-01 1203       정기         \\N  40대       1
23    2022-01-01 1203       정기         \\N  50대       2
24    2022-01-01 1203       정기         F    10대       2
25    2022-01-01 1203       정기         F    30대       1
26    2022-01-01 1203       정기         F    50대       1
27    2022-01-01 1203       정기         M    10대       1
28    2022-01-01 1203       정기         M    20대       2
29    2022-01-01 1203       정기         M    40대       1
30    2022-01-01 1203       정기         M    50대       2
⋮     ⋮          ⋮          ⋮            ⋮    ⋮          ⋮
66043 2022-01-31 4892       정기         \\N  20대       1
66044 2022-01-31 4892       정기         M    20대       1
66045 2022-01-31 4892       정기         M    기타       1
66046 2022-01-31 4893       일일(회원)   F    40대       1
66047 2022-01-31 4893       정기         F    30대       1
66048 2022-01-31 4895       일일(회원)   F    50대       1
66049 2022-01-31 4895       정기         \\N  30대       1
66050 2022-01-31 4895       정기         \\N  50대       1
66051 2022-01-31 4895       정기         F    30대       1
66052 2022-01-31 4895       정기         F    40대       1
66053 2022-01-31 4895       정기         F    50대       1
66054 2022-01-31 4895       정기         M    20대       1
66055 2022-01-31 4895       정기         M    30대       1
66056 2022-01-31 4895       정기         M    40대       1
66057 2022-01-31 4896       일일(회원)   \\N  20대       1
66058 2022-01-31 4896       정기         \\N  20대       1
66059 2022-01-31 4897       일일(회원)   \\N  20대       1
66060 2022-01-31 4897       일일(회원)   F    20대       1
66061 2022-01-31 4897       일일(회원)   F    기타       2
66062 2022-01-31 4897       일일(회원)   M    30대       1
66063 2022-01-31 4897       정기         \\N  10대       2
66064 2022-01-31 4897       정기         \\N  20대       1
66065 2022-01-31 4897       정기         \\N  30대       2
66066 2022-01-31 4897       정기         NA   30대       1
66067 2022-01-31 4897       정기         F    20대       1
66068 2022-01-31 4897       정기         F    30대       3
66069 2022-01-31 4897       정기         F    기타       1
66070 2022-01-31 4897       정기         M    30대       4
66071 2022-01-31 4897       정기         M    40대       1
66072 2022-01-31 4897       정기         M    기타       2

In [100]:
selected_DF01$`대여구분코드`<-ifelse(selected_DF01$`대여구분코드`=='정기',1,0)

In [101]:
selected_DF01 <- selected_DF01 %>%
  mutate(성별 = as.character(성별)) %>%
  mutate(성별 = case_when(
    성별 == "M" ~ 0,
    성별 == "F" ~ 1,
    TRUE ~ 2
  ))
#selected_DF02$`성별`<-ifelse(selected_DF02$`성별`=='M',0,ifelse(selected_DF02$`성별`=='F',1,2))

In [102]:
#selected_DF01$`연령대코드`<-ifelse(selected_DF01$`연령대코드`==c('10대','20대'),0,ifelse(selected_DF01$`연령대코드`=='30대',1,
#ifelse(selected_DF01$`연령대코드`=='40대',2,ifelse(selected_DF01$`연령대코드`=='50대',3,4))))
selected_DF01 <- selected_DF01 %>%
  mutate(연령대코드 = case_when(
    연령대코드 == "10대" ~ 0,
    연령대코드 == "20대" ~ 0,
    연령대코드 == "30대" ~ 1,
    연령대코드 == "40대" ~ 2,
    연령대코드 == "50대" ~ 3,
    연령대코드 == "60대" ~ 4,
    연령대코드 == "70대이상" ~ 4,
    연령대코드 == "기타" ~ 4,
    TRUE ~ as.numeric(연령대코드) # 숫자로 변환할 수 없는 값은 그대로 유지
  ))

Warning message:
“There was 1 warning in `mutate()`.
ℹ In argument: `연령대코드 = case_when(...)`.
Caused by warning:
! NAs introduced by coercion”

In [103]:
selected_DF01

      대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수
1     2022-01-01 1201       0            2    3          1
2     2022-01-01 1201       1            2    0          4
3     2022-01-01 1201       1            2    1          2
4     2022-01-01 1201       1            2    2          1
5     2022-01-01 1201       1            2    3          1
6     2022-01-01 1201       1            2    0          1
7     2022-01-01 1201       1            1    0          1
8     2022-01-01 1201       1            1    1          1
9     2022-01-01 1201       1            1    2          1
10    2022-01-01 1201       1            1    4          2
11    2022-01-01 1201       1            0    0          1
12    2022-01-01 1201       1            0    1          2
13    2022-01-01 1201       1            0    3          1
14    2022-01-01 1201       1            0    4          1
15    2022-01-01 1203       0            2    0          1
16    2022-01-01 1203       0            2    0          1
17    2022-01-01 1203       0            1    3          1
18    2022-01-01 1203       0            0    1          1
19    2022-01-01 1203       0            0    2          1
20    2022-01-01 1203       0            0    3          1
21    2022-01-01 1203       1            2    1          1
22    2022-01-01 1203       1            2    2          1
23    2022-01-01 1203       1            2    3          2
24    2022-01-01 1203       1            1    0          2
25    2022-01-01 1203       1            1    1          1
26    2022-01-01 1203       1            1    3          1
27    2022-01-01 1203       1            0    0          1
28    2022-01-01 1203       1            0    0          2
29    2022-01-01 1203       1            0    2          1
30    2022-01-01 1203       1            0    3          2
⋮     ⋮          ⋮          ⋮            ⋮    ⋮          ⋮
66043 2022-01-31 4892       1            2    0          1
66044 2022-01-31 4892       1            0    0          1
66045 2022-01-31 4892       1            0    4          1
66046 2022-01-31 4893       0            1    2          1
66047 2022-01-31 4893       1            1    1          1
66048 2022-01-31 4895       0            1    3          1
66049 2022-01-31 4895       1            2    1          1
66050 2022-01-31 4895       1            2    3          1
66051 2022-01-31 4895       1            1    1          1
66052 2022-01-31 4895       1            1    2          1
66053 2022-01-31 4895       1            1    3          1
66054 2022-01-31 4895       1            0    0          1
66055 2022-01-31 4895       1            0    1          1
66056 2022-01-31 4895       1            0    2          1
66057 2022-01-31 4896       0            2    0          1
66058 2022-01-31 4896       1            2    0          1
66059 2022-01-31 4897       0            2    0          1
66060 2022-01-31 4897       0            1    0          1
66061 2022-01-31 4897       0            1    4          2
66062 2022-01-31 4897       0            0    1          1
66063 2022-01-31 4897       1            2    0          2
66064 2022-01-31 4897       1            2    0          1
66065 2022-01-31 4897       1            2    1          2
66066 2022-01-31 4897       1            2    1          1
66067 2022-01-31 4897       1            1    0          1
66068 2022-01-31 4897       1            1    1          3
66069 2022-01-31 4897       1            1    4          1
66070 2022-01-31 4897       1            0    1          4
66071 2022-01-31 4897       1            0    2          1
66072 2022-01-31 4897       1            0    4          2

In [ ]:
write.csv(selected_DF01,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.01.csv",row.names=FALSE, na="")

In [104]:
selected_DF01$'평일/주말' <- ifelse(selected_DF01$대여일자 %in% date$date_time, date$weekend[match(selected_DF01$대여일자, date$date_time)], 2)
selected_DF01

      대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수 평일/주말
1     2022-01-01 1201       0            2    3          1        1
2     2022-01-01 1201       1            2    0          4        1
3     2022-01-01 1201       1            2    1          2        1
4     2022-01-01 1201       1            2    2          1        1
5     2022-01-01 1201       1            2    3          1        1
6     2022-01-01 1201       1            2    0          1        1
7     2022-01-01 1201       1            1    0          1        1
8     2022-01-01 1201       1            1    1          1        1
9     2022-01-01 1201       1            1    2          1        1
10    2022-01-01 1201       1            1    4          2        1
11    2022-01-01 1201       1            0    0          1        1
12    2022-01-01 1201       1            0    1          2        1
13    2022-01-01 1201       1            0    3          1        1
14    2022-01-01 1201       1            0    4          1        1
15    2022-01-01 1203       0            2    0          1        1
16    2022-01-01 1203       0            2    0          1        1
17    2022-01-01 1203       0            1    3          1        1
18    2022-01-01 1203       0            0    1          1        1
19    2022-01-01 1203       0            0    2          1        1
20    2022-01-01 1203       0            0    3          1        1
21    2022-01-01 1203       1            2    1          1        1
22    2022-01-01 1203       1            2    2          1        1
23    2022-01-01 1203       1            2    3          2        1
24    2022-01-01 1203       1            1    0          2        1
25    2022-01-01 1203       1            1    1          1        1
26    2022-01-01 1203       1            1    3          1        1
27    2022-01-01 1203       1            0    0          1        1
28    2022-01-01 1203       1            0    0          2        1
29    2022-01-01 1203       1            0    2          1        1
30    2022-01-01 1203       1            0    3          2        1
⋮     ⋮          ⋮          ⋮            ⋮    ⋮          ⋮        ⋮
66043 2022-01-31 4892       1            2    0          1        1
66044 2022-01-31 4892       1            0    0          1        1
66045 2022-01-31 4892       1            0    4          1        1
66046 2022-01-31 4893       0            1    2          1        1
66047 2022-01-31 4893       1            1    1          1        1
66048 2022-01-31 4895       0            1    3          1        1
66049 2022-01-31 4895       1            2    1          1        1
66050 2022-01-31 4895       1            2    3          1        1
66051 2022-01-31 4895       1            1    1          1        1
66052 2022-01-31 4895       1            1    2          1        1
66053 2022-01-31 4895       1            1    3          1        1
66054 2022-01-31 4895       1            0    0          1        1
66055 2022-01-31 4895       1            0    1          1        1
66056 2022-01-31 4895       1            0    2          1        1
66057 2022-01-31 4896       0            2    0          1        1
66058 2022-01-31 4896       1            2    0          1        1
66059 2022-01-31 4897       0            2    0          1        1
66060 2022-01-31 4897       0            1    0          1        1
66061 2022-01-31 4897       0            1    4          2        1
66062 2022-01-31 4897       0            0    1          1        1
66063 2022-01-31 4897       1            2    0          2        1
66064 2022-01-31 4897       1            2    0          1        1
66065 2022-01-31 4897       1            2    1          2        1
66066 2022-01-31 4897       1            2    1          1        1
66067 2022-01-31 4897       1            1    0          1        1
66068 2022-01-31 4897       1            1    1          3        1
66069 2022-01-31 4897       1            1    4          1        1
66070 2022-01-31 4897       1            0    1          4        1
66071 2022-01-31 4897       1            0    2          1        1
66072 2022-01-31 4897       1            0    4          2        1

In [105]:
selected_DF01 <- selected_DF01 %>% select('평일/주말', '대여구분코드', '성별', '연령대코드', '이용건수')
selected_DF01

      평일/주말 대여구분코드 성별 연령대코드 이용건수
1     1         0            2    3          1
2     1         1            2    0          4
3     1         1            2    1          2
4     1         1            2    2          1
5     1         1            2    3          1
6     1         1            2    0          1
7     1         1            1    0          1
8     1         1            1    1          1
9     1         1            1    2          1
10    1         1            1    4          2
11    1         1            0    0          1
12    1         1            0    1          2
13    1         1            0    3          1
14    1         1            0    4          1
15    1         0            2    0          1
16    1         0            2    0          1
17    1         0            1    3          1
18    1         0            0    1          1
19    1         0            0    2          1
20    1         0            0    3          1
21    1         1            2    1          1
22    1         1            2    2          1
23    1         1            2    3          2
24    1         1            1    0          2
25    1         1            1    1          1
26    1         1            1    3          1
27    1         1            0    0          1
28    1         1            0    0          2
29    1         1            0    2          1
30    1         1            0    3          2
⋮     ⋮         ⋮            ⋮    ⋮          ⋮
66043 1         1            2    0          1
66044 1         1            0    0          1
66045 1         1            0    4          1
66046 1         0            1    2          1
66047 1         1            1    1          1
66048 1         0            1    3          1
66049 1         1            2    1          1
66050 1         1            2    3          1
66051 1         1            1    1          1
66052 1         1            1    2          1
66053 1         1            1    3          1
66054 1         1            0    0          1
66055 1         1            0    1          1
66056 1         1            0    2          1
66057 1         0            2    0          1
66058 1         1            2    0          1
66059 1         0            2    0          1
66060 1         0            1    0          1
66061 1         0            1    4          2
66062 1         0            0    1          1
66063 1         1            2    0          2
66064 1         1            2    0          1
66065 1         1            2    1          2
66066 1         1            2    1          1
66067 1         1            1    0          1
66068 1         1            1    1          3
66069 1         1            1    4          1
66070 1         1            0    1          4
66071 1         1            0    2          1
66072 1         1            0    4          2

In [106]:
write.csv(selected_DF01,file="/content/전처리__송파구_서울특별시 공공자전거 이용정보(일별)_22.01.csv",row.names=FALSE, na="")

In [94]:
selected_DF01%>%
  filter(selected_DF01$`평일/주말`== 0 && selected_DF01$`성별`== 0 && selected_DF01$`연령대코드`== 0 && selected_DF01$`이용건수`== 0 && selected_DF01$`대여구분코드`== 0)
  %>% sum(이용건수, na.rm = TRUE)

ERROR: ignored

In [ ]:
summarized_data <- selected_DF01 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data

   대여일자   이용건수_합계
1  2022-01-01 2595
2  2022-01-02 2317
3  2022-01-03 4199
4  2022-01-04 4544
5  2022-01-05 4654
6  2022-01-06 5003
7  2022-01-07 5027
8  2022-01-08 3889
9  2022-01-09 3350
10 2022-01-10 4923
11 2022-01-11 3321
12 2022-01-12 3722
13 2022-01-13 3579
14 2022-01-14 4326
15 2022-01-15 3618
16 2022-01-16 2814
17 2022-01-17 3178
18 2022-01-18 3894
19 2022-01-19 2197
20 2022-01-20 3205
21 2022-01-21 4094
22 2022-01-22 3700
23 2022-01-23 3681
24 2022-01-24 5393
25 2022-01-25 3806
26 2022-01-26 5149
27 2022-01-27 4820
28 2022-01-28 4613
29 2022-01-29 3336
30 2022-01-30 2825
31 2022-01-31 2552

## **송파구 2월 전처리**

In [19]:
#https://drive.google.com/file/d/1DfhlIGas5mIgqR7Hmm6irq0C4ki6euBn/view?usp=sharing
system("gdown --id 1DfhlIGas5mIgqR7Hmm6irq0C4ki6euBn")
system("ls",TRUE)

[1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
[2] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
[3] "일자별 날씨정보.csv"
[4] "sample_data"

In [20]:
DF02<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_22.02.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF02

Rows: 747394 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): 대여소번호, 대여소, 대여구분코드, 성별, 연령대코드, 운동량, 탄소량
dbl  (3): 이용건수, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

       대여일자   대여소번호 대여소
1      2022-02-01 00003      중랑센터
2      2022-02-01 00102      102. 망원역 1번출구 앞
3      2022-02-01 00102      102. 망원역 1번출구 앞
4      2022-02-01 00102      102. 망원역 1번출구 앞
5      2022-02-01 00102      102. 망원역 1번출구 앞
6      2022-02-01 00102      102. 망원역 1번출구 앞
7      2022-02-01 00102      102. 망원역 1번출구 앞
8      2022-02-01 00102      102. 망원역 1번출구 앞
9      2022-02-01 00102      102. 망원역 1번출구 앞
10     2022-02-01 00102      102. 망원역 1번출구 앞
11     2022-02-01 00102      102. 망원역 1번출구 앞
12     2022-02-01 00102      102. 망원역 1번출구 앞
13     2022-02-01 00102      102. 망원역 1번출구 앞
14     2022-02-01 00102      102. 망원역 1번출구 앞
15     2022-02-01 00103      103. 망원역 2번출구 앞
16     2022-02-01 00103      103. 망원역 2번출구 앞
17     2022-02-01 00103      103. 망원역 2번출구 앞
18     2022-02-01 00103      103. 망원역 2번출구 앞
19     2022-02-01 00103      103. 망원역 2번출구 앞
20     2022-02-01 00103      103. 망원역 2번출구 앞
21     2022-02-01 00104      104. 합정역 1번출구 앞
22     2022-02-01 00104      104. 합정역 1번출구 앞
23     2022-02-01 00104      104. 합정역 1번출구 앞
24     2022-02-01 00104      104. 합정역 1번출구 앞
25     2022-02-01 00104      104. 합정역 1번출구 앞
26     2022-02-01 00104      104. 합정역 1번출구 앞
27     2022-02-01 00104      104. 합정역 1번출구 앞
28     2022-02-01 00104      104. 합정역 1번출구 앞
29     2022-02-01 00105      105. 합정역 5번출구 앞
30     2022-02-01 00105      105. 합정역 5번출구 앞
⋮      ⋮          ⋮          ⋮
747365 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747366 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747367 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747368 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747369 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747370 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747371 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747372 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747373 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747374 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747375 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747376 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747377 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747378 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747379 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747380 2022-02-28 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
747381 2022-02-28 05851      5851. 도림천 건널목 위
747382 2022-02-28 05851      5851. 도림천 건널목 위
747383 2022-02-28 05851      5851. 도림천 건널목 위
747384 2022-02-28 05851      5851. 도림천 건널목 위
747385 2022-02-28 05851      5851. 도림천 건널목 위
747386 2022-02-28 05851      5851. 도림천 건널목 위
747387 2022-02-28 05851      5851. 도림천 건널목 위
747388 2022-02-28 05851      5851. 도림천 건널목 위
747389 2022-02-28 05851      5851. 도림천 건널목 위
747390 2022-02-28 05852      5852. 대림동현대2차 201동 앞
747391 2022-02-28 05852      5852. 대림동현대2차 201동 앞
747392 2022-02-28 09999      상담센터
747393 2022-02-28 09999      상담센터
747394 2022-02-28 09999      상담센터
       대여구분코드 성별 연령대코드 이용건수 운동량 탄소량 이동거리(M)
1      정기         M    50대       1        73.23  0.64   2760.00
2      일일(회원)   \\N  20대       2        167.16 1.55   6698.64
3      일일(회원)   \\N  30대       1        22.93  0.21    891.02
4      일일(회원)   \\N  40대       1        55.45  0.34   1473.86
5      일일(회원)   F    20대       1        112.63 1.16   4990.00
6      정기         \\N  20대       1        59.15  0.56   2409.08
7      정기         \\N  60대       1        28.00  0.31   1334.24
8      정기         F    20대       2        47.49  0.56   2424.52
9      정기         F    30대       2        55.53  0.66   2819.78
10     정기         F    40대       2        192.16 1.78   7697.72
11     정기         F    60대       1        108.00 1.13   4870.00
12     정기         M    20대       2        88.07  0.56   2406.17
13     정기         M    30대       1        16.11  0.17    739.85
14     정기         M    40대       1        31.51  0.25   1061.11
15     일일(회원)   \\N  10대       1        50.01  0.34   1485.75
16     일일(회원)   \\N  20대       1        28.42  0.36   1560.00
17     일일(회원)   \\N  기타       1        34.90  0.34   1468.79
18     일일(회원)   M    30대       1        87.22  0.79   3388.65
19     정기         F    30대       2        93.71  1.01   4350.00
20     정기         F    50대       1        55.86  0.50   2170.00
21     일일(회원)   F    30대       1        23.91  0.27   1183.83
22     정기         \\N  20대       2        123.10 1.11   4782.44
23     정기         \\N  30대       1        56.59  0.39   1681.21
24     정기         \\N  40대       1        14.11  0.13    548.08
25     정기         M    20대       2        170.51 1.47   6353.55
26     정기         M    30대       2        82.80  0.66   2867.84
27     정기         M    40대       3        227.45 1.90   8178.66
28     정기         M    기타       1        55.99  0.47   2020.00
29     일일(회원)   \\N  20대       1        42.47  0.50   2144.80
30     정기         \\N  20대       1        10.55  0.10    410.00
⋮      ⋮            ⋮    ⋮          ⋮        ⋮      ⋮      ⋮
747365 일일(회원)   M    20대       2        70.92  0.55    2370.00
747366 일일(회원)   M    기타       3        230.51 2.08    8955.11
747367 정기         \\N  10대       1        5.29   0.05     199.25
747368 정기         \\N  20대       4        224.03 2.45   10568.14
747369 정기         \\N  40대       1        0.00   0.00       0.00
747370 정기         \\N  60대       1        96.70  0.86    3700.00
747371 정기         \\N  기타       1        10.45  0.10     440.00
747372 정기         F    20대       5        354.58 3.85   16532.94
747373 정기         F    50대       1        71.30  0.64    2770.00
747374 정기         F    기타       3        75.69  0.74    3201.70
747375 정기         M    10대       3        103.60 0.94    4043.53
747376 정기         M    20대       8        247.35 2.05    8785.60
747377 정기         M    30대       1        23.47  0.26    1140.00
747378 정기         M    40대       5        314.16 2.47   10665.47
747379 정기         M    60대       1        89.32  0.81    3470.00
747380 정기         M    기타       1        32.28  0.25    1072.47
747381 일일(회원)   F    20대       1        19.43  0.21     892.19
747382 정기         \\N  20대       2        208.23 1.88    8090.00
747383 정기         \\N  60대       1        226.20 1.89    8160.00
747384 정기         NA   30대       1        162.06 1.38    5930.97
747385 정기         NA   50대       1        36.88  0.22     960.00
747386 정기         F    30대       1        6.84   0.67    2880.00
747387 정기         M    20대       1        0.00   0.00       0.00
747388 정기         M    30대       1        21.09  0.16     710.00
747389 정기         M    40대       1        50.10  0.34    1471.00
747390 일일(회원)   M    20대       2        41.28  0.30    1310.00
747391 정기         \\N  30대       1        33.86  0.22     950.00
747392 일일(회원)   \\N  기타       1        19.82  0.18     770.00
747393 정기         \\N  20대       2        0.00   0.00       0.00
747394 정기         F    60대       1        \\N    \\N        0.00
       이용시간(분)
1       10
2       65
3       11
4       10
5       56
6       16
7       13
8       21
9       26
10      43
11      35
12      37
13     200
14       8
15      15
16      28
17      14
18      26
19     108
20      20
21       9
22      39
23      11
24      77
25      49
26      63
27      42
28      13
29      22
30       3
⋮      ⋮
747365  13
747366  85
747367   9
747368  66
747369  10
747370  27
747371   5
747372 137
747373  27
747374  30
747375  35
747376  67
747377   7
747378 107
747379  33
747380   7
747381  12
747382  53
747383  67
747384  42
747385   8
747386  22
747387   5
747388   2
747389  13
747390  12
747391   5
747392   9
747393  44
747394   4

In [21]:
DF02$대여소번호 <- as.numeric(DF02$대여소번호)

In [22]:
#2월 대여소 filter
f_DF02<- DF02 %>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897))
f_DF02

      대여일자   대여소번호 대여소                          대여구분코드 성별
1     2022-02-01 1201       1201. 가락시장역 3번 출구       일일(회원)   \\N
2     2022-02-01 1201       1201. 가락시장역 3번 출구       일일(회원)   M
3     2022-02-01 1201       1201. 가락시장역 3번 출구       정기         \\N
4     2022-02-01 1201       1201. 가락시장역 3번 출구       정기         \\N
5     2022-02-01 1201       1201. 가락시장역 3번 출구       정기         F
6     2022-02-01 1201       1201. 가락시장역 3번 출구       정기         M
7     2022-02-01 1203       1203. 밀리아나2빌딩 앞          일일(회원)   \\N
8     2022-02-01 1203       1203. 밀리아나2빌딩 앞          일일(회원)   M
9     2022-02-01 1203       1203. 밀리아나2빌딩 앞          정기         \\N
10    2022-02-01 1203       1203. 밀리아나2빌딩 앞          정기         \\N
11    2022-02-01 1203       1203. 밀리아나2빌딩 앞          정기         \\N
12    2022-02-01 1203       1203. 밀리아나2빌딩 앞          정기         F
13    2022-02-01 1203       1203. 밀리아나2빌딩 앞          정기         F
14    2022-02-01 1203       1203. 밀리아나2빌딩 앞          정기         F
15    2022-02-01 1203       1203. 밀리아나2빌딩 앞          정기         M
16    2022-02-01 1204       1204. 거여역 3번출구            일일(회원)   F
17    2022-02-01 1204       1204. 거여역 3번출구            일일(회원)   M
18    2022-02-01 1204       1204. 거여역 3번출구            정기         \\N
19    2022-02-01 1204       1204. 거여역 3번출구            정기         F
20    2022-02-01 1204       1204. 거여역 3번출구            정기         M
21    2022-02-01 1204       1204. 거여역 3번출구            정기         M
22    2022-02-01 1205       1205. 종합운동장역 4번출구      일일(회원)   F
23    2022-02-01 1205       1205. 종합운동장역 4번출구      정기         F
24    2022-02-01 1205       1205. 종합운동장역 4번출구      정기         M
25    2022-02-01 1205       1205. 종합운동장역 4번출구      정기         M
26    2022-02-01 1205       1205. 종합운동장역 4번출구      정기         M
27    2022-02-01 1206       1206. 9호선종합운동장역 9번출구 단체         F
28    2022-02-01 1206       1206. 9호선종합운동장역 9번출구 정기         \\N
29    2022-02-01 1206       1206. 9호선종합운동장역 9번출구 정기         F
30    2022-02-01 1207       1207. 마천중앙시장              일일(회원)   F
⋮     ⋮          ⋮          ⋮                               ⋮            ⋮
62834 2022-02-28 4895       4895. 위례포레샤인15단지 상가   일일(회원)   F
62835 2022-02-28 4895       4895. 위례포레샤인15단지 상가   일일(회원)   F
62836 2022-02-28 4895       4895. 위례포레샤인15단지 상가   정기         \\N
62837 2022-02-28 4895       4895. 위례포레샤인15단지 상가   정기         \\N
62838 2022-02-28 4895       4895. 위례포레샤인15단지 상가   정기         F
62839 2022-02-28 4895       4895. 위례포레샤인15단지 상가   정기         F
62840 2022-02-28 4895       4895. 위례포레샤인15단지 상가   정기         F
62841 2022-02-28 4895       4895. 위례포레샤인15단지 상가   정기         M
62842 2022-02-28 4895       4895. 위례포레샤인15단지 상가   정기         M
62843 2022-02-28 4895       4895. 위례포레샤인15단지 상가   정기         M
62844 2022-02-28 4896       4896. 위례포레샤인15단지        정기         M
62845 2022-02-28 4897       4897. 잠실주공5단지1            일일(회원)   \\N
62846 2022-02-28 4897       4897. 잠실주공5단지1            일일(회원)   F
62847 2022-02-28 4897       4897. 잠실주공5단지1            일일(회원)   M
62848 2022-02-28 4897       4897. 잠실주공5단지1            정기         \\N
62849 2022-02-28 4897       4897. 잠실주공5단지1            정기         \\N
62850 2022-02-28 4897       4897. 잠실주공5단지1            정기         \\N
62851 2022-02-28 4897       4897. 잠실주공5단지1            정기         \\N
62852 2022-02-28 4897       4897. 잠실주공5단지1            정기         \\N
62853 2022-02-28 4897       4897. 잠실주공5단지1            정기         NA
62854 2022-02-28 4897       4897. 잠실주공5단지1            정기         F
62855 2022-02-28 4897       4897. 잠실주공5단지1            정기         F
62856 2022-02-28 4897       4897. 잠실주공5단지1            정기         F
62857 2022-02-28 4897       4897. 잠실주공5단지1            정기         F
62858 2022-02-28 4897       4897. 잠실주공5단지1            정기         F
62859 2022-02-28 4897       4897. 잠실주공5단지1            정기         M
62860 2022-02-28 4897       4897. 잠실주공5단지1            정기         M
62861 2022-02-28 4897       4897. 잠실주공5단지1            정기         M
62862 2022-02-28 4897       4897. 잠실주공5단지1            정기         M
62863 2022-02-28 4897       4897. 잠실주공5단지1            정기         M
      연령대코드 이용건수 운동량 탄소량 이동거리(M) 이용시간(분)
1     40대       1        98.63  0.83    3558.18     54
2     20대       1        116.48 1.02    4390.00     26
3     40대       1        47.52  0.37    1600.00     17
4     50대       1        5.57   0.04     192.59     37
5     20대       1        78.76  0.71    3060.00     63
6     30대       1        64.86  0.58    2520.00     18
7     30대       1        249.90 2.25    9708.67     79
8     기타       1        57.18  0.56    2406.45     20
9     20대       1        29.48  0.35    1489.01     14
10    30대       1        23.94  0.22     930.00      6
11    50대       1        0.00   0.00       0.00      9
12    20대       1        0.00   0.00       0.00     10
13    30대       1        13.74  0.14     598.40     21
14    기타       1        28.12  0.32    1365.61     18
15    20대       1        223.34 1.64    7050.00     70
16    20대       1        55.51  0.33    1401.71     29
17    10대       1        0.00   0.00       0.00      4
18    30대       2        501.36 3.72   16020.00     79
19    40대       2        600.15 6.06   26130.00    142
20    20대       2        70.17  0.51    2199.18     67
21    30대       1        38.33  0.28    1210.00      8
22    50대       1        128.44 1.11    4769.89     27
23    20대       1        92.06  1.08    4649.43     28
24    20대       1        0.00   0.00       0.00      3
25    40대       1        109.77 0.92    3960.00     57
26    50대       1        33.39  0.29    1240.00      7
27    50대       1        16.43  0.18     768.10     53
28    20대       1        39.35  0.48    2070.00     11
29    60대       1        49.61  0.50    2160.00     21
30    20대       1        146.98 1.32    5710.00     30
⋮     ⋮          ⋮        ⋮      ⋮      ⋮           ⋮
62834 30대       1        127.71 1.15    4961.72    48
62835 기타       1        43.42  0.39    1687.03    14
62836 20대       2        152.05 1.07    4617.93    38
62837 30대       2        93.81  0.84    3644.67    38
62838 30대       2        55.45  0.65    2800.48    23
62839 40대       2        55.13  0.58    2499.83    17
62840 50대       1        115.35 1.04    4481.45    30
62841 30대       2        18.40  0.17     714.78    17
62842 40대       2        184.48 1.46    6281.55    68
62843 50대       2        84.94  0.64    2750.00    45
62844 50대       2        0.00   0.00       0.00     6
62845 20대       2        90.16  1.15    4928.04    45
62846 20대       2        142.77 1.47    6325.08    47
62847 60대       1        88.20  0.81    3480.00    21
62848 10대       1        26.40  0.26    1130.00    10
62849 20대       5        193.13 1.64    7060.00    43
62850 30대       1        0.00   0.00       0.00     6
62851 40대       2        29.06  0.18     786.60     7
62852 기타       1        16.42  0.15     638.04     4
62853 20대       1        5.21   0.06     239.24     5
62854 10대       1        25.45  0.29    1260.00    11
62855 20대       2        298.96 2.77   11930.00    62
62856 30대       2        12.28  0.14     620.00     6
62857 40대       2        29.90  0.35    1510.00    14
62858 50대       1        19.31  0.17     750.00     3
62859 20대       2        0.00   0.00       0.00    12
62860 30대       2        101.38 0.86    3725.40    47
62861 40대       1        41.37  0.35    1514.22    11
62862 60대       1        121.12 0.87    3730.00    92
62863 기타       1        34.75  0.31    1350.00     8

In [23]:
selected_DF02 <- f_DF02 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대코드, 이용건수)
selected_DF02

      대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수
1     2022-02-01 1201       일일(회원)   \\N  40대       1
2     2022-02-01 1201       일일(회원)   M    20대       1
3     2022-02-01 1201       정기         \\N  40대       1
4     2022-02-01 1201       정기         \\N  50대       1
5     2022-02-01 1201       정기         F    20대       1
6     2022-02-01 1201       정기         M    30대       1
7     2022-02-01 1203       일일(회원)   \\N  30대       1
8     2022-02-01 1203       일일(회원)   M    기타       1
9     2022-02-01 1203       정기         \\N  20대       1
10    2022-02-01 1203       정기         \\N  30대       1
11    2022-02-01 1203       정기         \\N  50대       1
12    2022-02-01 1203       정기         F    20대       1
13    2022-02-01 1203       정기         F    30대       1
14    2022-02-01 1203       정기         F    기타       1
15    2022-02-01 1203       정기         M    20대       1
16    2022-02-01 1204       일일(회원)   F    20대       1
17    2022-02-01 1204       일일(회원)   M    10대       1
18    2022-02-01 1204       정기         \\N  30대       2
19    2022-02-01 1204       정기         F    40대       2
20    2022-02-01 1204       정기         M    20대       2
21    2022-02-01 1204       정기         M    30대       1
22    2022-02-01 1205       일일(회원)   F    50대       1
23    2022-02-01 1205       정기         F    20대       1
24    2022-02-01 1205       정기         M    20대       1
25    2022-02-01 1205       정기         M    40대       1
26    2022-02-01 1205       정기         M    50대       1
27    2022-02-01 1206       단체         F    50대       1
28    2022-02-01 1206       정기         \\N  20대       1
29    2022-02-01 1206       정기         F    60대       1
30    2022-02-01 1207       일일(회원)   F    20대       1
⋮     ⋮          ⋮          ⋮            ⋮    ⋮          ⋮
62834 2022-02-28 4895       일일(회원)   F    30대       1
62835 2022-02-28 4895       일일(회원)   F    기타       1
62836 2022-02-28 4895       정기         \\N  20대       2
62837 2022-02-28 4895       정기         \\N  30대       2
62838 2022-02-28 4895       정기         F    30대       2
62839 2022-02-28 4895       정기         F    40대       2
62840 2022-02-28 4895       정기         F    50대       1
62841 2022-02-28 4895       정기         M    30대       2
62842 2022-02-28 4895       정기         M    40대       2
62843 2022-02-28 4895       정기         M    50대       2
62844 2022-02-28 4896       정기         M    50대       2
62845 2022-02-28 4897       일일(회원)   \\N  20대       2
62846 2022-02-28 4897       일일(회원)   F    20대       2
62847 2022-02-28 4897       일일(회원)   M    60대       1
62848 2022-02-28 4897       정기         \\N  10대       1
62849 2022-02-28 4897       정기         \\N  20대       5
62850 2022-02-28 4897       정기         \\N  30대       1
62851 2022-02-28 4897       정기         \\N  40대       2
62852 2022-02-28 4897       정기         \\N  기타       1
62853 2022-02-28 4897       정기         NA   20대       1
62854 2022-02-28 4897       정기         F    10대       1
62855 2022-02-28 4897       정기         F    20대       2
62856 2022-02-28 4897       정기         F    30대       2
62857 2022-02-28 4897       정기         F    40대       2
62858 2022-02-28 4897       정기         F    50대       1
62859 2022-02-28 4897       정기         M    20대       2
62860 2022-02-28 4897       정기         M    30대       2
62861 2022-02-28 4897       정기         M    40대       1
62862 2022-02-28 4897       정기         M    60대       1
62863 2022-02-28 4897       정기         M    기타       1

In [24]:
selected_DF02$`대여구분코드`<-ifelse(selected_DF02$`대여구분코드`=='정기',1,0)

In [25]:
selected_DF02$`성별`<-ifelse(selected_DF02$`성별`=='M',0,ifelse(selected_DF02$`성별`=='F',1,2))

In [26]:
selected_DF02$`연령대코드`<-ifelse(selected_DF02$`연령대코드`=='10대',0,ifelse(selected_DF02$`연령대코드`=='20대',1,ifelse(selected_DF02$`연령대코드`=='30대',2,ifelse(selected_DF02$`연령대코드`=='40대',3,ifelse(selected_DF02$`연령대코드`=='50대',4,ifelse(selected_DF02$`연령대코드`=='60대',5,ifelse(selected_DF02$`연령대코드`=='70대이상',6,7)))))))

In [27]:
selected_DF02

      대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수
1     2022-02-01 1201       0            2    3          1
2     2022-02-01 1201       0            0    1          1
3     2022-02-01 1201       1            2    3          1
4     2022-02-01 1201       1            2    4          1
5     2022-02-01 1201       1            1    1          1
6     2022-02-01 1201       1            0    2          1
7     2022-02-01 1203       0            2    2          1
8     2022-02-01 1203       0            0    7          1
9     2022-02-01 1203       1            2    1          1
10    2022-02-01 1203       1            2    2          1
11    2022-02-01 1203       1            2    4          1
12    2022-02-01 1203       1            1    1          1
13    2022-02-01 1203       1            1    2          1
14    2022-02-01 1203       1            1    7          1
15    2022-02-01 1203       1            0    1          1
16    2022-02-01 1204       0            1    1          1
17    2022-02-01 1204       0            0    0          1
18    2022-02-01 1204       1            2    2          2
19    2022-02-01 1204       1            1    3          2
20    2022-02-01 1204       1            0    1          2
21    2022-02-01 1204       1            0    2          1
22    2022-02-01 1205       0            1    4          1
23    2022-02-01 1205       1            1    1          1
24    2022-02-01 1205       1            0    1          1
25    2022-02-01 1205       1            0    3          1
26    2022-02-01 1205       1            0    4          1
27    2022-02-01 1206       0            1    4          1
28    2022-02-01 1206       1            2    1          1
29    2022-02-01 1206       1            1    5          1
30    2022-02-01 1207       0            1    1          1
⋮     ⋮          ⋮          ⋮            ⋮    ⋮          ⋮
62834 2022-02-28 4895       0             1   2          1
62835 2022-02-28 4895       0             1   7          1
62836 2022-02-28 4895       1             2   1          2
62837 2022-02-28 4895       1             2   2          2
62838 2022-02-28 4895       1             1   2          2
62839 2022-02-28 4895       1             1   3          2
62840 2022-02-28 4895       1             1   4          1
62841 2022-02-28 4895       1             0   2          2
62842 2022-02-28 4895       1             0   3          2
62843 2022-02-28 4895       1             0   4          2
62844 2022-02-28 4896       1             0   4          2
62845 2022-02-28 4897       0             2   1          2
62846 2022-02-28 4897       0             1   1          2
62847 2022-02-28 4897       0             0   5          1
62848 2022-02-28 4897       1             2   0          1
62849 2022-02-28 4897       1             2   1          5
62850 2022-02-28 4897       1             2   2          1
62851 2022-02-28 4897       1             2   3          2
62852 2022-02-28 4897       1             2   7          1
62853 2022-02-28 4897       1            NA   1          1
62854 2022-02-28 4897       1             1   0          1
62855 2022-02-28 4897       1             1   1          2
62856 2022-02-28 4897       1             1   2          2
62857 2022-02-28 4897       1             1   3          2
62858 2022-02-28 4897       1             1   4          1
62859 2022-02-28 4897       1             0   1          2
62860 2022-02-28 4897       1             0   2          2
62861 2022-02-28 4897       1             0   3          1
62862 2022-02-28 4897       1             0   5          1
62863 2022-02-28 4897       1             0   7          1

In [ ]:
write.csv(selected_DF02,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.02.csv",row.names=FALSE, na="")

In [28]:
selected_DF02$'평일/주말' <- ifelse(selected_DF02$대여일자 %in% date$date_time, date$weekend[match(selected_DF02$대여일자, date$date_time)], 2)
selected_DF02

      대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수 평일/주말
1     2022-02-01 1201       0            2    3          1        1
2     2022-02-01 1201       0            0    1          1        1
3     2022-02-01 1201       1            2    3          1        1
4     2022-02-01 1201       1            2    4          1        1
5     2022-02-01 1201       1            1    1          1        1
6     2022-02-01 1201       1            0    2          1        1
7     2022-02-01 1203       0            2    2          1        1
8     2022-02-01 1203       0            0    7          1        1
9     2022-02-01 1203       1            2    1          1        1
10    2022-02-01 1203       1            2    2          1        1
11    2022-02-01 1203       1            2    4          1        1
12    2022-02-01 1203       1            1    1          1        1
13    2022-02-01 1203       1            1    2          1        1
14    2022-02-01 1203       1            1    7          1        1
15    2022-02-01 1203       1            0    1          1        1
16    2022-02-01 1204       0            1    1          1        1
17    2022-02-01 1204       0            0    0          1        1
18    2022-02-01 1204       1            2    2          2        1
19    2022-02-01 1204       1            1    3          2        1
20    2022-02-01 1204       1            0    1          2        1
21    2022-02-01 1204       1            0    2          1        1
22    2022-02-01 1205       0            1    4          1        1
23    2022-02-01 1205       1            1    1          1        1
24    2022-02-01 1205       1            0    1          1        1
25    2022-02-01 1205       1            0    3          1        1
26    2022-02-01 1205       1            0    4          1        1
27    2022-02-01 1206       0            1    4          1        1
28    2022-02-01 1206       1            2    1          1        1
29    2022-02-01 1206       1            1    5          1        1
30    2022-02-01 1207       0            1    1          1        1
⋮     ⋮          ⋮          ⋮            ⋮    ⋮          ⋮        ⋮
62834 2022-02-28 4895       0             1   2          1        0
62835 2022-02-28 4895       0             1   7          1        0
62836 2022-02-28 4895       1             2   1          2        0
62837 2022-02-28 4895       1             2   2          2        0
62838 2022-02-28 4895       1             1   2          2        0
62839 2022-02-28 4895       1             1   3          2        0
62840 2022-02-28 4895       1             1   4          1        0
62841 2022-02-28 4895       1             0   2          2        0
62842 2022-02-28 4895       1             0   3          2        0
62843 2022-02-28 4895       1             0   4          2        0
62844 2022-02-28 4896       1             0   4          2        0
62845 2022-02-28 4897       0             2   1          2        0
62846 2022-02-28 4897       0             1   1          2        0
62847 2022-02-28 4897       0             0   5          1        0
62848 2022-02-28 4897       1             2   0          1        0
62849 2022-02-28 4897       1             2   1          5        0
62850 2022-02-28 4897       1             2   2          1        0
62851 2022-02-28 4897       1             2   3          2        0
62852 2022-02-28 4897       1             2   7          1        0
62853 2022-02-28 4897       1            NA   1          1        0
62854 2022-02-28 4897       1             1   0          1        0
62855 2022-02-28 4897       1             1   1          2        0
62856 2022-02-28 4897       1             1   2          2        0
62857 2022-02-28 4897       1             1   3          2        0
62858 2022-02-28 4897       1             1   4          1        0
62859 2022-02-28 4897       1             0   1          2        0
62860 2022-02-28 4897       1             0   2          2        0
62861 2022-02-28 4897       1             0   3          1        0
62862 2022-02-28 4897       1             0   5          1        0
62863 2022-02-28 4897       1             0   7          1        0

In [ ]:
colnames(selected_DF02)

[1] "대여일자"     "대여소번호"   "대여구분코드" "성별"         "연령대코드"
[6] "이용건수"     "평일/주말"

In [ ]:
unique_values <- unique(selected_DF02[c("대여일자", "평일/주말")])
print(unique_values)

# A tibble: 28 × 2
   대여일자   `평일/주말`
   <date>           <dbl>
 1 2022-02-01           2
 2 2022-02-02           1
 3 2022-02-03           0
 4 2022-02-04           0
 5 2022-02-05           1
 6 2022-02-06           1
 7 2022-02-07           0
 8 2022-02-08           0
 9 2022-02-09           0
10 2022-02-10           0
# ℹ 18 more rows

In [29]:
selected_DF02 <- selected_DF02 %>% select('평일/주말', '대여구분코드', '성별', '연령대코드', '이용건수')
selected_DF02

      평일/주말 대여구분코드 성별 연령대코드 이용건수
1     1         0            2    3          1
2     1         0            0    1          1
3     1         1            2    3          1
4     1         1            2    4          1
5     1         1            1    1          1
6     1         1            0    2          1
7     1         0            2    2          1
8     1         0            0    7          1
9     1         1            2    1          1
10    1         1            2    2          1
11    1         1            2    4          1
12    1         1            1    1          1
13    1         1            1    2          1
14    1         1            1    7          1
15    1         1            0    1          1
16    1         0            1    1          1
17    1         0            0    0          1
18    1         1            2    2          2
19    1         1            1    3          2
20    1         1            0    1          2
21    1         1            0    2          1
22    1         0            1    4          1
23    1         1            1    1          1
24    1         1            0    1          1
25    1         1            0    3          1
26    1         1            0    4          1
27    1         0            1    4          1
28    1         1            2    1          1
29    1         1            1    5          1
30    1         0            1    1          1
⋮     ⋮         ⋮            ⋮    ⋮          ⋮
62834 0         0             1   2          1
62835 0         0             1   7          1
62836 0         1             2   1          2
62837 0         1             2   2          2
62838 0         1             1   2          2
62839 0         1             1   3          2
62840 0         1             1   4          1
62841 0         1             0   2          2
62842 0         1             0   3          2
62843 0         1             0   4          2
62844 0         1             0   4          2
62845 0         0             2   1          2
62846 0         0             1   1          2
62847 0         0             0   5          1
62848 0         1             2   0          1
62849 0         1             2   1          5
62850 0         1             2   2          1
62851 0         1             2   3          2
62852 0         1             2   7          1
62853 0         1            NA   1          1
62854 0         1             1   0          1
62855 0         1             1   1          2
62856 0         1             1   2          2
62857 0         1             1   3          2
62858 0         1             1   4          1
62859 0         1             0   1          2
62860 0         1             0   2          2
62861 0         1             0   3          1
62862 0         1             0   5          1
62863 0         1             0   7          1

In [ ]:
summarized_data_02 <- selected_DF02 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data_02

   대여일자   이용건수_합계
1  2022-02-01 1337
2  2022-02-02 2610
3  2022-02-03 3967
4  2022-02-04 3779
5  2022-02-05 2687
6  2022-02-06 2670
7  2022-02-07 4341
8  2022-02-08 4851
9  2022-02-09 5193
10 2022-02-10 5609
11 2022-02-11 5614
12 2022-02-12 5277
13 2022-02-13 4545
14 2022-02-14 3989
15 2022-02-15 4056
16 2022-02-16 3525
17 2022-02-17 3944
18 2022-02-18 4811
19 2022-02-19 3749
20 2022-02-20 2593
21 2022-02-21 4055
22 2022-02-22 4031
23 2022-02-23 3932
24 2022-02-24 4450
25 2022-02-25 5219
26 2022-02-26 3362
27 2022-02-27 4738
28 2022-02-28 6107

## **송파구 3월 전처리**

In [30]:
#https://drive.google.com/file/d/1S-VxhDHRQvnbyRpfCYWcFc3d4N9ysDYb/view?usp=sharing
system("gdown --id 1S-VxhDHRQvnbyRpfCYWcFc3d4N9ysDYb")
system("ls",TRUE)

[1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
[2] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
[3] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
[4] "일자별 날씨정보.csv"
[5] "sample_data"

In [31]:
DF03<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_22.03.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF03

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 1136504 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): 대여소번호, 대여소, 대여구분코드, 성별, 연령대코드
dbl  (5): 이용건수, 운동량, 탄소량, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        대여일자   대여소번호 대여소                       대여구분코드 성별
1       2022-03-01 00003      중랑센터                     정기         M
2       2022-03-01 00003      중랑센터                     정기         M
3       2022-03-01 00102      102. 망원역 1번출구 앞       일일(회원)   \\N
4       2022-03-01 00102      102. 망원역 1번출구 앞       일일(회원)   \\N
5       2022-03-01 00102      102. 망원역 1번출구 앞       일일(회원)   NA
6       2022-03-01 00102      102. 망원역 1번출구 앞       일일(회원)   F
7       2022-03-01 00102      102. 망원역 1번출구 앞       일일(회원)   M
8       2022-03-01 00102      102. 망원역 1번출구 앞       일일(회원)   M
9       2022-03-01 00102      102. 망원역 1번출구 앞       일일(회원)   M
10      2022-03-01 00102      102. 망원역 1번출구 앞       일일(회원)   M
11      2022-03-01 00102      102. 망원역 1번출구 앞       일일(회원)   M
12      2022-03-01 00102      102. 망원역 1번출구 앞       정기         \\N
13      2022-03-01 00102      102. 망원역 1번출구 앞       정기         \\N
14      2022-03-01 00102      102. 망원역 1번출구 앞       정기         \\N
15      2022-03-01 00102      102. 망원역 1번출구 앞       정기         NA
16      2022-03-01 00102      102. 망원역 1번출구 앞       정기         F
17      2022-03-01 00102      102. 망원역 1번출구 앞       정기         F
18      2022-03-01 00102      102. 망원역 1번출구 앞       정기         F
19      2022-03-01 00102      102. 망원역 1번출구 앞       정기         M
20      2022-03-01 00102      102. 망원역 1번출구 앞       정기         M
21      2022-03-01 00102      102. 망원역 1번출구 앞       정기         M
22      2022-03-01 00103      103. 망원역 2번출구 앞       일일(회원)   \\N
23      2022-03-01 00103      103. 망원역 2번출구 앞       일일(회원)   \\N
24      2022-03-01 00103      103. 망원역 2번출구 앞       일일(회원)   \\N
25      2022-03-01 00103      103. 망원역 2번출구 앞       일일(회원)   F
26      2022-03-01 00103      103. 망원역 2번출구 앞       일일(회원)   F
27      2022-03-01 00103      103. 망원역 2번출구 앞       일일(회원)   F
28      2022-03-01 00103      103. 망원역 2번출구 앞       일일(회원)   F
29      2022-03-01 00103      103. 망원역 2번출구 앞       일일(회원)   M
30      2022-03-01 00103      103. 망원역 2번출구 앞       일일(회원)   M
⋮       ⋮          ⋮          ⋮                            ⋮            ⋮
1136475 2022-03-31 05851      5851. 도림천 건널목 위       일일(회원)   F
1136476 2022-03-31 05851      5851. 도림천 건널목 위       일일(회원)   F
1136477 2022-03-31 05851      5851. 도림천 건널목 위       정기         \\N
1136478 2022-03-31 05851      5851. 도림천 건널목 위       정기         \\N
1136479 2022-03-31 05851      5851. 도림천 건널목 위       정기         \\N
1136480 2022-03-31 05851      5851. 도림천 건널목 위       정기         \\N
1136481 2022-03-31 05851      5851. 도림천 건널목 위       정기         \\N
1136482 2022-03-31 05851      5851. 도림천 건널목 위       정기         NA
1136483 2022-03-31 05851      5851. 도림천 건널목 위       정기         F
1136484 2022-03-31 05851      5851. 도림천 건널목 위       정기         F
1136485 2022-03-31 05851      5851. 도림천 건널목 위       정기         F
1136486 2022-03-31 05851      5851. 도림천 건널목 위       정기         M
1136487 2022-03-31 05851      5851. 도림천 건널목 위       정기         M
1136488 2022-03-31 05851      5851. 도림천 건널목 위       정기         M
1136489 2022-03-31 05851      5851. 도림천 건널목 위       정기         M
1136490 2022-03-31 05851      5851. 도림천 건널목 위       정기         M
1136491 2022-03-31 05851      5851. 도림천 건널목 위       정기         M
1136492 2022-03-31 05852      5852. 대림동현대2차 201동 앞 일일(비회원) \\N
1136493 2022-03-31 05852      5852. 대림동현대2차 201동 앞 일일(회원)   \\N
1136494 2022-03-31 05852      5852. 대림동현대2차 201동 앞 정기         \\N
1136495 2022-03-31 05852      5852. 대림동현대2차 201동 앞 정기         F
1136496 2022-03-31 05852      5852. 대림동현대2차 201동 앞 정기         M
1136497 2022-03-31 05852      5852. 대림동현대2차 201동 앞 정기         M
1136498 2022-03-31 09980      9980. 에이텍                 정기         M
1136499 2022-03-31 09998      9998. 영남주차장 정비센터    정기         \\N
1136500 2022-03-31 09999      상담센터                     일일(회원)   \\N
1136501 2022-03-31 09999      상담센터                     일일(회원)   F
1136502 2022-03-31 09999      상담센터                     일일(회원)   M
1136503 2022-03-31 09999      상담센터                     정기         \\N
1136504 2022-03-31 09999      상담센터                     정기         F
        연령대코드 이용건수 운동량 탄소량 이동거리(M) 이용시간(분)
1       20대        1       126.64 1.14    4920.00     23
2       50대        1        66.60 0.58    2510.00     10
3       20대        2       119.51 1.38    5937.73     94
4       30대        1       209.18 1.73    7440.00     45
5       20대        1        34.49 0.31    1340.00      8
6       20대        4       444.67 4.06   17538.26    196
7       10대        1       157.64 1.18    5103.71     66
8       20대        4       319.50 2.52   10851.56    122
9       30대        2        86.96 0.60    2559.35     16
10      40대        1        45.15 0.41    1754.17     11
11      기타        2       222.42 1.93    8303.59     71
12      20대       10       326.60 3.07   13210.66    222
13      30대        7       280.35 2.63   11262.60    135
14      50대        1        68.47 0.62    2660.00     64
15      20대        3       115.07 0.82    3535.49     25
16      10대        1        12.12 0.10     450.00      4
17      20대        7       225.83 2.50   10740.62     88
18      30대        2        75.81 0.76    3298.61     68
19      20대        4       195.16 1.83    7877.71     92
20      30대        4       219.05 1.86    8052.64    113
21      40대        3       188.23 1.39    6023.14     92
22      10대        1       105.05 1.04    4496.03    113
23      20대        1       186.18 1.51    6530.00     52
24      30대        2       361.51 3.01   12998.03     69
25      10대        1        52.11 0.62    2685.72     65
26      20대        1         0.00 0.00       0.00      9
27      30대        1        26.72 0.31    1349.60     15
28      기타        3       389.48 3.74   16120.67    192
29      20대        5       695.49 5.83   25118.84    205
30      30대        4       274.66 2.30    9890.21     91
⋮       ⋮          ⋮        ⋮      ⋮      ⋮           ⋮
1136475 30대       1         56.93 0.51    2211.56    20
1136476 40대       1         13.94 0.14     586.71     5
1136477 20대       1          0.00 0.00       0.00     7
1136478 30대       2        109.55 0.76    3282.08    17
1136479 40대       1         26.86 0.28    1190.00     8
1136480 50대       1         68.81 0.56    2413.32    13
1136481 기타       1        110.93 1.08    4668.58    17
1136482 20대       1         44.27 0.40    1720.00     6
1136483 20대       1        168.20 1.52    6534.48    39
1136484 40대       1         62.93 0.64    2740.00    22
1136485 50대       1        384.02 3.88   16720.00    84
1136486 20대       1         73.66 0.58    2480.00    14
1136487 30대       3        445.44 3.92   16900.63    78
1136488 50대       2        208.59 1.63    7000.00    79
1136489 60대       1         19.95 0.17     730.00     7
1136490 70대이상   1          0.00 0.00       0.00     8
1136491 기타       2        160.72 1.26    5430.00    36
1136492 기타       1         91.38 0.82    3550.00    18
1136493 20대       1         50.97 0.46    1980.00     7
1136494 50대       1        374.36 3.05   13130.00    52
1136495 30대       1         18.26 0.20     870.00     5
1136496 20대       1         29.62 0.20     880.00     5
1136497 30대       2        105.81 0.93    3969.86    28
1136498 20대       1          0.00 0.00       0.00     1
1136499 기타       2          0.00 0.00       0.00     0
1136500 20대       1        809.01 5.58   24034.78    99
1136501 10대       1         12.85 0.14     590.00     4
1136502 기타       1         98.05 0.91    3930.00    26
1136503 20대       2         38.67 0.36    1550.00     8
1136504 기타       1         45.82 0.41    1780.00    11

In [32]:
 DF03$대여소번호 <- as.numeric(DF03$대여소번호)

In [33]:
f_DF03<-DF03%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897,5751,5752,5753,5760,5756,5758,5759,5761,5763,5764,5765,5766,5767))
f_DF03

      대여일자   대여소번호 대여소                        대여구분코드 성별
1     2022-03-01 1201       1201. 가락시장역 3번 출구     일일(회원)   \\N
2     2022-03-01 1201       1201. 가락시장역 3번 출구     일일(회원)   \\N
3     2022-03-01 1201       1201. 가락시장역 3번 출구     일일(회원)   \\N
4     2022-03-01 1201       1201. 가락시장역 3번 출구     일일(회원)   F
5     2022-03-01 1201       1201. 가락시장역 3번 출구     일일(회원)   F
6     2022-03-01 1201       1201. 가락시장역 3번 출구     일일(회원)   M
7     2022-03-01 1201       1201. 가락시장역 3번 출구     일일(회원)   M
8     2022-03-01 1201       1201. 가락시장역 3번 출구     일일(회원)   M
9     2022-03-01 1201       1201. 가락시장역 3번 출구     정기         \\N
10    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         \\N
11    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         \\N
12    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         \\N
13    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         NA
14    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         NA
15    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         F
16    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         F
17    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         F
18    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         F
19    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         M
20    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         M
21    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         M
22    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         M
23    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         M
24    2022-03-01 1201       1201. 가락시장역 3번 출구     정기         M
25    2022-03-01 1203       1203. 밀리아나2빌딩 앞        일일(비회원) \\N
26    2022-03-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   \\N
27    2022-03-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   \\N
28    2022-03-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   \\N
29    2022-03-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   F
30    2022-03-01 1203       1203. 밀리아나2빌딩 앞        일일(회원)   F
⋮     ⋮          ⋮          ⋮                             ⋮            ⋮
94556 2022-03-31 4895       4895. 위례포레샤인15단지 상가 정기         M
94557 2022-03-31 4895       4895. 위례포레샤인15단지 상가 정기         M
94558 2022-03-31 4895       4895. 위례포레샤인15단지 상가 정기         M
94559 2022-03-31 4896       4896. 위례포레샤인15단지      일일(회원)   F
94560 2022-03-31 4896       4896. 위례포레샤인15단지      일일(회원)   M
94561 2022-03-31 4896       4896. 위례포레샤인15단지      정기         \\N
94562 2022-03-31 4896       4896. 위례포레샤인15단지      정기         M
94563 2022-03-31 4896       4896. 위례포레샤인15단지      정기         M
94564 2022-03-31 4896       4896. 위례포레샤인15단지      정기         M
94565 2022-03-31 4897       4897. 잠실주공5단지1          일일(회원)   F
94566 2022-03-31 4897       4897. 잠실주공5단지1          일일(회원)   F
94567 2022-03-31 4897       4897. 잠실주공5단지1          일일(회원)   F
94568 2022-03-31 4897       4897. 잠실주공5단지1          정기         \\N
94569 2022-03-31 4897       4897. 잠실주공5단지1          정기         \\N
94570 2022-03-31 4897       4897. 잠실주공5단지1          정기         \\N
94571 2022-03-31 4897       4897. 잠실주공5단지1          정기         \\N
94572 2022-03-31 4897       4897. 잠실주공5단지1          정기         \\N
94573 2022-03-31 4897       4897. 잠실주공5단지1          정기         \\N
94574 2022-03-31 4897       4897. 잠실주공5단지1          정기         NA
94575 2022-03-31 4897       4897. 잠실주공5단지1          정기         F
94576 2022-03-31 4897       4897. 잠실주공5단지1          정기         F
94577 2022-03-31 4897       4897. 잠실주공5단지1          정기         F
94578 2022-03-31 4897       4897. 잠실주공5단지1          정기         F
94579 2022-03-31 4897       4897. 잠실주공5단지1          정기         F
94580 2022-03-31 4897       4897. 잠실주공5단지1          정기         M
94581 2022-03-31 4897       4897. 잠실주공5단지1          정기         M
94582 2022-03-31 4897       4897. 잠실주공5단지1          정기         M
94583 2022-03-31 4897       4897. 잠실주공5단지1          정기         M
94584 2022-03-31 4897       4897. 잠실주공5단지1          정기         M
94585 2022-03-31 4897       4897. 잠실주공5단지1          정기         M
      연령대코드 이용건수 운동량 탄소량 이동거리(M) 이용시간(분)
1     20대       4        189.50 1.77   7578.80     47
2     30대       1        133.14 0.95   4100.00     30
3     40대       1         50.45 0.42   1820.00     11
4     20대       1         63.69 0.98   4232.22     41
5     30대       1         32.20 0.42   1806.94     24
6     20대       1         86.76 0.73   3130.00     21
7     40대       1         24.08 0.18    760.00      5
8     기타       1         23.94 0.22    930.00      6
9     20대       2         48.35 0.50   2141.93     19
10    30대       1        269.68 1.58   6810.00     41
11    40대       2        226.42 1.64   7063.13     54
12    50대       4         46.62 0.41   1779.41     40
13    30대       1         50.62 0.44   1879.83     15
14    60대       1          0.00 0.00      0.00      4
15    20대       3         99.49 1.10   4740.26     66
16    30대       3         97.58 1.14   4932.47     52
17    50대       1        123.31 1.20   5190.00     39
18    기타       2         89.55 0.81   3479.00     39
19    10대       1         58.35 0.47   2046.48     40
20    20대       4        138.87 1.12   4843.08     39
21    30대       5        144.50 1.25   5389.67     44
22    40대       1         78.63 0.48   2090.00     14
23    50대       1        126.20 1.19   5140.00     36
24    60대       1         71.23 0.64   2767.22     14
25    기타       1        159.19 1.43   6184.41     45
26    30대       1         27.36 0.29   1256.18     11
27    40대       1         27.44 0.36   1540.00     22
28    50대       1          0.00 0.00      0.00      7
29    20대       2        116.50 1.10   4760.62     72
30    기타       1         72.33 0.65   2810.00     21
⋮     ⋮          ⋮        ⋮      ⋮      ⋮           ⋮
94556 40대       4        227.09 1.60    6854.78    42
94557 50대       5        179.97 1.30    5628.33    33
94558 기타       1         73.00 0.66    2835.99    38
94559 30대       1         34.08 0.33    1434.36    16
94560 30대       1         45.00 0.33    1420.48    13
94561 20대       1          0.00 0.00       0.00     2
94562 20대       2        138.68 1.12    4835.70    42
94563 30대       1          1.26 0.12     530.00     3
94564 40대       1         12.08 0.09     381.20     2
94565 20대       1         13.18 0.15     640.00     5
94566 30대       1         59.20 0.53    2300.00    15
94567 40대       1         29.85 0.27    1159.52     8
94568 20대       9        295.63 2.87   12314.33    78
94569 30대       2         19.63 0.14     590.00     5
94570 40대       4        147.43 1.25    5412.15    28
94571 50대       1         24.91 0.22     967.89    14
94572 60대       1          0.00 0.00       0.00     6
94573 기타       2         20.85 0.19     810.00     7
94574 20대       3         51.53 0.50    2170.00    10
94575 10대       1         41.60 0.48    2060.00    17
94576 20대       2        164.65 1.52    6565.76    75
94577 30대       5        200.31 1.97    8509.37    74
94578 50대       1         29.80 0.33    1420.00    11
94579 기타       2         36.36 0.37    1583.17    15
94580 20대       7        318.31 2.06    8853.13    63
94581 30대       4        129.08 1.04    4502.42    42
94582 40대       2        138.19 1.09    4690.62    26
94583 50대       1         13.03 0.11     470.00    56
94584 60대       1         24.46 0.22     950.40     5
94585 기타       2        133.61 1.27    5492.94    54

In [34]:
selected_DF03 <- f_DF03 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대코드, 이용건수)
selected_DF03

      대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수
1     2022-03-01 1201       일일(회원)   \\N  20대       4
2     2022-03-01 1201       일일(회원)   \\N  30대       1
3     2022-03-01 1201       일일(회원)   \\N  40대       1
4     2022-03-01 1201       일일(회원)   F    20대       1
5     2022-03-01 1201       일일(회원)   F    30대       1
6     2022-03-01 1201       일일(회원)   M    20대       1
7     2022-03-01 1201       일일(회원)   M    40대       1
8     2022-03-01 1201       일일(회원)   M    기타       1
9     2022-03-01 1201       정기         \\N  20대       2
10    2022-03-01 1201       정기         \\N  30대       1
11    2022-03-01 1201       정기         \\N  40대       2
12    2022-03-01 1201       정기         \\N  50대       4
13    2022-03-01 1201       정기         NA   30대       1
14    2022-03-01 1201       정기         NA   60대       1
15    2022-03-01 1201       정기         F    20대       3
16    2022-03-01 1201       정기         F    30대       3
17    2022-03-01 1201       정기         F    50대       1
18    2022-03-01 1201       정기         F    기타       2
19    2022-03-01 1201       정기         M    10대       1
20    2022-03-01 1201       정기         M    20대       4
21    2022-03-01 1201       정기         M    30대       5
22    2022-03-01 1201       정기         M    40대       1
23    2022-03-01 1201       정기         M    50대       1
24    2022-03-01 1201       정기         M    60대       1
25    2022-03-01 1203       일일(비회원) \\N  기타       1
26    2022-03-01 1203       일일(회원)   \\N  30대       1
27    2022-03-01 1203       일일(회원)   \\N  40대       1
28    2022-03-01 1203       일일(회원)   \\N  50대       1
29    2022-03-01 1203       일일(회원)   F    20대       2
30    2022-03-01 1203       일일(회원)   F    기타       1
⋮     ⋮          ⋮          ⋮            ⋮    ⋮          ⋮
94556 2022-03-31 4895       정기         M    40대       4
94557 2022-03-31 4895       정기         M    50대       5
94558 2022-03-31 4895       정기         M    기타       1
94559 2022-03-31 4896       일일(회원)   F    30대       1
94560 2022-03-31 4896       일일(회원)   M    30대       1
94561 2022-03-31 4896       정기         \\N  20대       1
94562 2022-03-31 4896       정기         M    20대       2
94563 2022-03-31 4896       정기         M    30대       1
94564 2022-03-31 4896       정기         M    40대       1
94565 2022-03-31 4897       일일(회원)   F    20대       1
94566 2022-03-31 4897       일일(회원)   F    30대       1
94567 2022-03-31 4897       일일(회원)   F    40대       1
94568 2022-03-31 4897       정기         \\N  20대       9
94569 2022-03-31 4897       정기         \\N  30대       2
94570 2022-03-31 4897       정기         \\N  40대       4
94571 2022-03-31 4897       정기         \\N  50대       1
94572 2022-03-31 4897       정기         \\N  60대       1
94573 2022-03-31 4897       정기         \\N  기타       2
94574 2022-03-31 4897       정기         NA   20대       3
94575 2022-03-31 4897       정기         F    10대       1
94576 2022-03-31 4897       정기         F    20대       2
94577 2022-03-31 4897       정기         F    30대       5
94578 2022-03-31 4897       정기         F    50대       1
94579 2022-03-31 4897       정기         F    기타       2
94580 2022-03-31 4897       정기         M    20대       7
94581 2022-03-31 4897       정기         M    30대       4
94582 2022-03-31 4897       정기         M    40대       2
94583 2022-03-31 4897       정기         M    50대       1
94584 2022-03-31 4897       정기         M    60대       1
94585 2022-03-31 4897       정기         M    기타       2

In [35]:
selected_DF03$`대여구분코드`<-ifelse(selected_DF03$`대여구분코드`=='정기',1,0)

In [36]:
selected_DF03$`성별`<-ifelse(selected_DF03$`성별`=='M',0,ifelse(selected_DF03$`성별`=='F',1,2))

In [37]:
selected_DF03$`연령대코드`<-ifelse(selected_DF03$`연령대코드`=='10대',0,ifelse(selected_DF03$`연령대코드`=='20대',1,ifelse(selected_DF03$`연령대코드`=='30대',2,ifelse(selected_DF03$`연령대코드`=='40대',3,ifelse(selected_DF03$`연령대코드`=='50대',4,ifelse(selected_DF03$`연령대코드`=='60대',5,ifelse(selected_DF03$`연령대코드`=='70대이상',6,7)))))))

In [38]:
selected_DF03

      대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수
1     2022-03-01 1201       0             2   1          4
2     2022-03-01 1201       0             2   2          1
3     2022-03-01 1201       0             2   3          1
4     2022-03-01 1201       0             1   1          1
5     2022-03-01 1201       0             1   2          1
6     2022-03-01 1201       0             0   1          1
7     2022-03-01 1201       0             0   3          1
8     2022-03-01 1201       0             0   7          1
9     2022-03-01 1201       1             2   1          2
10    2022-03-01 1201       1             2   2          1
11    2022-03-01 1201       1             2   3          2
12    2022-03-01 1201       1             2   4          4
13    2022-03-01 1201       1            NA   2          1
14    2022-03-01 1201       1            NA   5          1
15    2022-03-01 1201       1             1   1          3
16    2022-03-01 1201       1             1   2          3
17    2022-03-01 1201       1             1   4          1
18    2022-03-01 1201       1             1   7          2
19    2022-03-01 1201       1             0   0          1
20    2022-03-01 1201       1             0   1          4
21    2022-03-01 1201       1             0   2          5
22    2022-03-01 1201       1             0   3          1
23    2022-03-01 1201       1             0   4          1
24    2022-03-01 1201       1             0   5          1
25    2022-03-01 1203       0             2   7          1
26    2022-03-01 1203       0             2   2          1
27    2022-03-01 1203       0             2   3          1
28    2022-03-01 1203       0             2   4          1
29    2022-03-01 1203       0             1   1          2
30    2022-03-01 1203       0             1   7          1
⋮     ⋮          ⋮          ⋮            ⋮    ⋮          ⋮
94556 2022-03-31 4895       1             0   3          4
94557 2022-03-31 4895       1             0   4          5
94558 2022-03-31 4895       1             0   7          1
94559 2022-03-31 4896       0             1   2          1
94560 2022-03-31 4896       0             0   2          1
94561 2022-03-31 4896       1             2   1          1
94562 2022-03-31 4896       1             0   1          2
94563 2022-03-31 4896       1             0   2          1
94564 2022-03-31 4896       1             0   3          1
94565 2022-03-31 4897       0             1   1          1
94566 2022-03-31 4897       0             1   2          1
94567 2022-03-31 4897       0             1   3          1
94568 2022-03-31 4897       1             2   1          9
94569 2022-03-31 4897       1             2   2          2
94570 2022-03-31 4897       1             2   3          4
94571 2022-03-31 4897       1             2   4          1
94572 2022-03-31 4897       1             2   5          1
94573 2022-03-31 4897       1             2   7          2
94574 2022-03-31 4897       1            NA   1          3
94575 2022-03-31 4897       1             1   0          1
94576 2022-03-31 4897       1             1   1          2
94577 2022-03-31 4897       1             1   2          5
94578 2022-03-31 4897       1             1   4          1
94579 2022-03-31 4897       1             1   7          2
94580 2022-03-31 4897       1             0   1          7
94581 2022-03-31 4897       1             0   2          4
94582 2022-03-31 4897       1             0   3          2
94583 2022-03-31 4897       1             0   4          1
94584 2022-03-31 4897       1             0   5          1
94585 2022-03-31 4897       1             0   7          2

In [ ]:
write.csv(selected_DF03,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.03.csv",row.names=FALSE, na="")

In [39]:
selected_DF03$'평일/주말' <- ifelse(selected_DF03$대여일자 %in% date$date_time, date$weekend[match(selected_DF03$대여일자, date$date_time)], 2)
selected_DF03

      대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수 평일/주말
1     2022-03-01 1201       0             2   1          4        1
2     2022-03-01 1201       0             2   2          1        1
3     2022-03-01 1201       0             2   3          1        1
4     2022-03-01 1201       0             1   1          1        1
5     2022-03-01 1201       0             1   2          1        1
6     2022-03-01 1201       0             0   1          1        1
7     2022-03-01 1201       0             0   3          1        1
8     2022-03-01 1201       0             0   7          1        1
9     2022-03-01 1201       1             2   1          2        1
10    2022-03-01 1201       1             2   2          1        1
11    2022-03-01 1201       1             2   3          2        1
12    2022-03-01 1201       1             2   4          4        1
13    2022-03-01 1201       1            NA   2          1        1
14    2022-03-01 1201       1            NA   5          1        1
15    2022-03-01 1201       1             1   1          3        1
16    2022-03-01 1201       1             1   2          3        1
17    2022-03-01 1201       1             1   4          1        1
18    2022-03-01 1201       1             1   7          2        1
19    2022-03-01 1201       1             0   0          1        1
20    2022-03-01 1201       1             0   1          4        1
21    2022-03-01 1201       1             0   2          5        1
22    2022-03-01 1201       1             0   3          1        1
23    2022-03-01 1201       1             0   4          1        1
24    2022-03-01 1201       1             0   5          1        1
25    2022-03-01 1203       0             2   7          1        1
26    2022-03-01 1203       0             2   2          1        1
27    2022-03-01 1203       0             2   3          1        1
28    2022-03-01 1203       0             2   4          1        1
29    2022-03-01 1203       0             1   1          2        1
30    2022-03-01 1203       0             1   7          1        1
⋮     ⋮          ⋮          ⋮            ⋮    ⋮          ⋮        ⋮
94556 2022-03-31 4895       1             0   3          4        0
94557 2022-03-31 4895       1             0   4          5        0
94558 2022-03-31 4895       1             0   7          1        0
94559 2022-03-31 4896       0             1   2          1        0
94560 2022-03-31 4896       0             0   2          1        0
94561 2022-03-31 4896       1             2   1          1        0
94562 2022-03-31 4896       1             0   1          2        0
94563 2022-03-31 4896       1             0   2          1        0
94564 2022-03-31 4896       1             0   3          1        0
94565 2022-03-31 4897       0             1   1          1        0
94566 2022-03-31 4897       0             1   2          1        0
94567 2022-03-31 4897       0             1   3          1        0
94568 2022-03-31 4897       1             2   1          9        0
94569 2022-03-31 4897       1             2   2          2        0
94570 2022-03-31 4897       1             2   3          4        0
94571 2022-03-31 4897       1             2   4          1        0
94572 2022-03-31 4897       1             2   5          1        0
94573 2022-03-31 4897       1             2   7          2        0
94574 2022-03-31 4897       1            NA   1          3        0
94575 2022-03-31 4897       1             1   0          1        0
94576 2022-03-31 4897       1             1   1          2        0
94577 2022-03-31 4897       1             1   2          5        0
94578 2022-03-31 4897       1             1   4          1        0
94579 2022-03-31 4897       1             1   7          2        0
94580 2022-03-31 4897       1             0   1          7        0
94581 2022-03-31 4897       1             0   2          4        0
94582 2022-03-31 4897       1             0   3          2        0
94583 2022-03-31 4897       1             0   4          1        0
94584 2022-03-31 4897       1             0   5          1        0
94585 2022-03-31 4897       1             0   7          2        0

In [40]:
selected_DF03 <- selected_DF03 %>% select('평일/주말', '대여구분코드', '성별', '연령대코드', '이용건수')
selected_DF03

      평일/주말 대여구분코드 성별 연령대코드 이용건수
1     1         0             2   1          4
2     1         0             2   2          1
3     1         0             2   3          1
4     1         0             1   1          1
5     1         0             1   2          1
6     1         0             0   1          1
7     1         0             0   3          1
8     1         0             0   7          1
9     1         1             2   1          2
10    1         1             2   2          1
11    1         1             2   3          2
12    1         1             2   4          4
13    1         1            NA   2          1
14    1         1            NA   5          1
15    1         1             1   1          3
16    1         1             1   2          3
17    1         1             1   4          1
18    1         1             1   7          2
19    1         1             0   0          1
20    1         1             0   1          4
21    1         1             0   2          5
22    1         1             0   3          1
23    1         1             0   4          1
24    1         1             0   5          1
25    1         0             2   7          1
26    1         0             2   2          1
27    1         0             2   3          1
28    1         0             2   4          1
29    1         0             1   1          2
30    1         0             1   7          1
⋮     ⋮         ⋮            ⋮    ⋮          ⋮
94556 0         1             0   3          4
94557 0         1             0   4          5
94558 0         1             0   7          1
94559 0         0             1   2          1
94560 0         0             0   2          1
94561 0         1             2   1          1
94562 0         1             0   1          2
94563 0         1             0   2          1
94564 0         1             0   3          1
94565 0         0             1   1          1
94566 0         0             1   2          1
94567 0         0             1   3          1
94568 0         1             2   1          9
94569 0         1             2   2          2
94570 0         1             2   3          4
94571 0         1             2   4          1
94572 0         1             2   5          1
94573 0         1             2   7          2
94574 0         1            NA   1          3
94575 0         1             1   0          1
94576 0         1             1   1          2
94577 0         1             1   2          5
94578 0         1             1   4          1
94579 0         1             1   7          2
94580 0         1             0   1          7
94581 0         1             0   2          4
94582 0         1             0   3          2
94583 0         1             0   4          1
94584 0         1             0   5          1
94585 0         1             0   7          2

In [ ]:
summarized_data_03 <- selected_DF03 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data_03

   대여일자   이용건수_합계
1  2022-03-01 4531
2  2022-03-02 5751
3  2022-03-03 6389
4  2022-03-04 6045
5  2022-03-05 4971
6  2022-03-06 4869
7  2022-03-07 6039
8  2022-03-08 6781
9  2022-03-09 7872
10 2022-03-10 7406
11 2022-03-11 8147
12 2022-03-12 7332
13 2022-03-13 3222
14 2022-03-14 3958
15 2022-03-15 7589
16 2022-03-16 8151
17 2022-03-17 6186
18 2022-03-18 6555
19 2022-03-19 2823
20 2022-03-20 5646
21 2022-03-21 6962
22 2022-03-22 8018
23 2022-03-23 7189
24 2022-03-24 7660
25 2022-03-25 6933
26 2022-03-26 5480
27 2022-03-27 7942
28 2022-03-28 8918
29 2022-03-29 9494
30 2022-03-30 7807
31 2022-03-31 9397

## **4월 전처리**

In [41]:
#https://drive.google.com/file/d/1LIJ-8Jjo5V1LyE6gra-mv2LRUTsv6LIp/view?usp=sharing
system("gdown --id 1LIJ-8Jjo5V1LyE6gra-mv2LRUTsv6LIp")
system("ls",TRUE)

[1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
[2] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
[3] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
[4] "서울특별시 공공자전거 이용정보(일별)_22.04.csv"
[5] "일자별 날씨정보.csv"
[6] "sample_data"

In [42]:
DF04<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_22.04.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF04

Rows: 1487586 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): 대여소번호, 대여소, 대여구분코드, 성별, 연령대코드, 운동량, 탄소량
dbl  (3): 이용건수, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        대여일자   대여소번호 대여소                       대여구분코드 성별
1       2022-04-01 00005      상암센터 정비실              정기         F
2       2022-04-01 00005      상암센터 정비실              정기         M
3       2022-04-01 00102      102. 망원역 1번출구 앞       단체         M
4       2022-04-01 00102      102. 망원역 1번출구 앞       일일(비회원) \\N
5       2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   \\N
6       2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   \\N
7       2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   \\N
8       2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   NA
9       2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   F
10      2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   F
11      2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   F
12      2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   F
13      2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   M
14      2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   M
15      2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   M
16      2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   M
17      2022-04-01 00102      102. 망원역 1번출구 앞       일일(회원)   M
18      2022-04-01 00102      102. 망원역 1번출구 앞       정기         \\N
19      2022-04-01 00102      102. 망원역 1번출구 앞       정기         \\N
20      2022-04-01 00102      102. 망원역 1번출구 앞       정기         \\N
21      2022-04-01 00102      102. 망원역 1번출구 앞       정기         \\N
22      2022-04-01 00102      102. 망원역 1번출구 앞       정기         \\N
23      2022-04-01 00102      102. 망원역 1번출구 앞       정기         \\N
24      2022-04-01 00102      102. 망원역 1번출구 앞       정기         NA
25      2022-04-01 00102      102. 망원역 1번출구 앞       정기         NA
26      2022-04-01 00102      102. 망원역 1번출구 앞       정기         NA
27      2022-04-01 00102      102. 망원역 1번출구 앞       정기         F
28      2022-04-01 00102      102. 망원역 1번출구 앞       정기         F
29      2022-04-01 00102      102. 망원역 1번출구 앞       정기         F
30      2022-04-01 00102      102. 망원역 1번출구 앞       정기         F
⋮       ⋮          ⋮          ⋮                            ⋮            ⋮
1487557 2022-04-30 05851      5851. 도림천 건널목 위       정기         \\N
1487558 2022-04-30 05851      5851. 도림천 건널목 위       정기         \\N
1487559 2022-04-30 05851      5851. 도림천 건널목 위       정기         \\N
1487560 2022-04-30 05851      5851. 도림천 건널목 위       정기         F
1487561 2022-04-30 05851      5851. 도림천 건널목 위       정기         F
1487562 2022-04-30 05851      5851. 도림천 건널목 위       정기         F
1487563 2022-04-30 05851      5851. 도림천 건널목 위       정기         F
1487564 2022-04-30 05851      5851. 도림천 건널목 위       정기         M
1487565 2022-04-30 05851      5851. 도림천 건널목 위       정기         M
1487566 2022-04-30 05851      5851. 도림천 건널목 위       정기         M
1487567 2022-04-30 05851      5851. 도림천 건널목 위       정기         M
1487568 2022-04-30 05852      5852. 대림동현대2차 201동 앞 일일(비회원) \\N
1487569 2022-04-30 05852      5852. 대림동현대2차 201동 앞 일일(회원)   M
1487570 2022-04-30 05852      5852. 대림동현대2차 201동 앞 일일(회원)   M
1487571 2022-04-30 05852      5852. 대림동현대2차 201동 앞 일일(회원)   M
1487572 2022-04-30 05852      5852. 대림동현대2차 201동 앞 정기         F
1487573 2022-04-30 05852      5852. 대림동현대2차 201동 앞 정기         M
1487574 2022-04-30 05852      5852. 대림동현대2차 201동 앞 정기         M
1487575 2022-04-30 05852      5852. 대림동현대2차 201동 앞 정기         M
1487576 2022-04-30 09999      상담센터                     단체         F
1487577 2022-04-30 09999      상담센터                     일일(비회원) \\N
1487578 2022-04-30 09999      상담센터                     일일(회원)   \\N
1487579 2022-04-30 09999      상담센터                     일일(회원)   \\N
1487580 2022-04-30 09999      상담센터                     일일(회원)   F
1487581 2022-04-30 09999      상담센터                     일일(회원)   M
1487582 2022-04-30 09999      상담센터                     일일(회원)   M
1487583 2022-04-30 09999      상담센터                     정기         \\N
1487584 2022-04-30 09999      상담센터                     정기         \\N
1487585 2022-04-30 09999      상담센터                     정기         F
1487586 2022-04-30 09999      상담센터                     정기         M
        연령대코드 이용건수 운동량  탄소량 이동거리(M) 이용시간(분)
1       30대        1       35.79   0.34    1481.64     11
2       50대        1       89.39   1.05    4514.87     25
3       기타        7       606.00  6.28   27056.32    211
4       기타        6       1781.66 16.05  69216.96    455
5       10대        1       23.26   0.21     890.00      4
6       20대        4       535.52  5.22   22486.39    143
7       기타        1       308.64  3.01   12990.00     78
8       30대        1       180.10  1.62    6996.92     47
9       20대       11       1119.13 10.72  46259.29    499
10      30대        3       453.18  4.31   18564.78    181
11      40대        1       61.77   0.79    3391.18     22
12      기타        1       55.60   0.50    2160.00     21
13      10대        2       185.50  1.40    6012.65    126
14      20대        6       683.51  5.66   24409.65    200
15      30대        2       313.05  2.80   12102.60     45
16      40대        2       111.02  0.72    3110.00     33
17      기타        1       194.70  1.41    6070.00     32
18      20대       14       471.01  4.97   21418.25    301
19      30대        6       538.68  4.06   17460.66    187
20      40대        3       496.68  4.61   19848.08    154
21      50대        3       210.97  2.17    9340.76     65
22      70대이상    1       26.78   0.24    1040.55     13
23      기타        1       22.84   0.21     887.32      9
24      20대        1       21.41   0.19     831.78      4
25      30대        1       \\N     \\N        0.00     17
26      40대        1       96.82   1.13    4890.00     39
27      20대       18       967.13  9.97   42937.22    357
28      30대        9       304.71  3.27   14095.38    122
29      40대        2       83.21   0.90    3869.45     28
30      50대        3       200.67  1.77    7650.27     55
⋮       ⋮          ⋮        ⋮       ⋮      ⋮           ⋮
1487557 20대       3        200.61  1.75    7515.02     47
1487558 30대       2        190.99  1.70    7326.04     34
1487559 40대       1        58.21   0.49    2100.08     15
1487560 20대       3        602.82  5.83   25123.97    136
1487561 30대       3        405.54  3.10   13366.38    103
1487562 40대       2        20.95   0.19     838.48     11
1487563 기타       1        37.32   0.35    1520.00      7
1487564 20대       1        79.17   0.71    3075.76     29
1487565 30대       1        94.21   0.85    3660.00     21
1487566 40대       1        21.80   0.15     640.00      2
1487567 60대       1        21.48   0.18     786.12      5
1487568 기타       2        253.87  2.29    9862.72     76
1487569 20대       1        99.41   0.90    3862.27     22
1487570 30대       1        29.11   0.24    1050.00      4
1487571 기타       1        19.32   0.14     610.00      6
1487572 20대       1        82.33   0.88    3780.00     25
1487573 20대       2        216.15  1.94    8397.29     68
1487574 40대       1        14.67   0.13     570.00      8
1487575 50대       1        19.31   0.17     750.00      2
1487576 40대       1        121.70  1.37    5910.00     55
1487577 기타       1        210.57  1.90    8180.56      7
1487578 40대       1        48.91   0.45    1930.00     30
1487579 기타       1        144.94  1.42    6100.00     39
1487580 10대       1        168.62  1.52    6550.75     20
1487581 20대       2        491.45  4.43   19092.74     45
1487582 기타       1        0.00    0.00       0.00      1
1487583 20대       1        45.29   0.42    1815.48     53
1487584 30대       1        81.50   0.58    2510.00     41
1487585 20대       2        113.43  1.03    4460.00     43
1487586 기타       1        38.97   0.35    1514.18     11

In [ ]:
DF04$대여소번호 <- as.numeric(DF04$대여소번호)

In [ ]:
f_DF04<-DF04%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897,5751,5752,5753,5760,5756,5758,5759,5761,5763,5764,5765,5766,5767))
f_DF04

       대여일자   대여소번호 대여소                    대여구분코드 성별
1      2022-04-01 1201       1201. 가락시장역 3번 출구 일일(비회원) \\N
2      2022-04-01 1201       1201. 가락시장역 3번 출구 일일(회원)   \\N
3      2022-04-01 1201       1201. 가락시장역 3번 출구 일일(회원)   \\N
4      2022-04-01 1201       1201. 가락시장역 3번 출구 일일(회원)   NA
5      2022-04-01 1201       1201. 가락시장역 3번 출구 일일(회원)   F
6      2022-04-01 1201       1201. 가락시장역 3번 출구 일일(회원)   F
7      2022-04-01 1201       1201. 가락시장역 3번 출구 일일(회원)   F
8      2022-04-01 1201       1201. 가락시장역 3번 출구 일일(회원)   M
9      2022-04-01 1201       1201. 가락시장역 3번 출구 일일(회원)   M
10     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         \\N
11     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         \\N
12     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         \\N
13     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         \\N
14     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         NA
15     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         F
16     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         F
17     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         F
18     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         F
19     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         F
20     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         M
21     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         M
22     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         M
23     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         M
24     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         M
25     2022-04-01 1201       1201. 가락시장역 3번 출구 정기         M
26     2022-04-01 1203       1203. 밀리아나2빌딩 앞    일일(회원)   \\N
27     2022-04-01 1203       1203. 밀리아나2빌딩 앞    일일(회원)   \\N
28     2022-04-01 1203       1203. 밀리아나2빌딩 앞    일일(회원)   F
29     2022-04-01 1203       1203. 밀리아나2빌딩 앞    일일(회원)   F
30     2022-04-01 1203       1203. 밀리아나2빌딩 앞    일일(회원)   F
⋮      ⋮          ⋮          ⋮                         ⋮            ⋮
126095 2022-04-30 4897       4897. 잠실주공5단지1      단체         F
126096 2022-04-30 4897       4897. 잠실주공5단지1      일일(비회원) \\N
126097 2022-04-30 4897       4897. 잠실주공5단지1      일일(회원)   \\N
126098 2022-04-30 4897       4897. 잠실주공5단지1      일일(회원)   \\N
126099 2022-04-30 4897       4897. 잠실주공5단지1      일일(회원)   NA
126100 2022-04-30 4897       4897. 잠실주공5단지1      일일(회원)   F
126101 2022-04-30 4897       4897. 잠실주공5단지1      일일(회원)   F
126102 2022-04-30 4897       4897. 잠실주공5단지1      일일(회원)   F
126103 2022-04-30 4897       4897. 잠실주공5단지1      일일(회원)   M
126104 2022-04-30 4897       4897. 잠실주공5단지1      일일(회원)   M
126105 2022-04-30 4897       4897. 잠실주공5단지1      일일(회원)   M
126106 2022-04-30 4897       4897. 잠실주공5단지1      일일(회원)   M
126107 2022-04-30 4897       4897. 잠실주공5단지1      정기         \\N
126108 2022-04-30 4897       4897. 잠실주공5단지1      정기         \\N
126109 2022-04-30 4897       4897. 잠실주공5단지1      정기         \\N
126110 2022-04-30 4897       4897. 잠실주공5단지1      정기         \\N
126111 2022-04-30 4897       4897. 잠실주공5단지1      정기         \\N
126112 2022-04-30 4897       4897. 잠실주공5단지1      정기         \\N
126113 2022-04-30 4897       4897. 잠실주공5단지1      정기         NA
126114 2022-04-30 4897       4897. 잠실주공5단지1      정기         F
126115 2022-04-30 4897       4897. 잠실주공5단지1      정기         F
126116 2022-04-30 4897       4897. 잠실주공5단지1      정기         F
126117 2022-04-30 4897       4897. 잠실주공5단지1      정기         F
126118 2022-04-30 4897       4897. 잠실주공5단지1      정기         F
126119 2022-04-30 4897       4897. 잠실주공5단지1      정기         M
126120 2022-04-30 4897       4897. 잠실주공5단지1      정기         M
126121 2022-04-30 4897       4897. 잠실주공5단지1      정기         M
126122 2022-04-30 4897       4897. 잠실주공5단지1      정기         M
126123 2022-04-30 4897       4897. 잠실주공5단지1      정기         M
126124 2022-04-30 4897       4897. 잠실주공5단지1      정기         M
       연령대코드 이용건수 운동량  탄소량 이동거리(M) 이용시간(분)
1      기타        1       56.33   0.51    2188.56     12
2      20대        4       235.61  1.96    8443.39     98
3      30대        3       219.05  2.54   10938.68     88
4      30대        1       128.59  0.94    4059.08     19
5      30대        1       0.00    0.00       0.00      1
6      40대        1       28.66   0.26    1113.63     10
7      기타        1       22.39   0.20     870.00      4
8      30대        2       170.56  1.54    6626.17     39
9      50대        1       23.51   0.23     989.57      8
10     20대        5       223.26  4.96   21380.21    206
11     30대       11       634.58  5.63   24338.03    320
12     40대        4       196.51  1.59    6881.88     37
13     50대        3       115.00  0.96    4154.47     32
14     40대        2       50.69   0.37    1600.00     16
15     20대        4       203.96  1.84    7923.94    101
16     30대        9       270.14  2.47   10715.43     88
17     40대        4       178.25  1.92    8261.70    173
18     60대        2       73.22   0.77    3340.00     23
19     기타        2       34.01   0.31    1321.43     12
20     20대        5       129.16  1.13    4843.73    104
21     30대        8       428.31  3.40   14641.66    110
22     40대        3       146.90  1.09    4720.00     31
23     50대        2       351.73  2.50   10794.47     74
24     60대        1       95.98   0.80    3462.47     25
25     기타        2       114.49  0.99    4260.00     30
26     20대        6       363.84  3.39   14588.94    140
27     30대        1       95.24   0.86    3700.00     40
28     10대        1       38.39   0.47    2019.66     26
29     20대        5       309.51  3.14   13570.48    100
30     30대        2       202.58  2.16    9300.00     83
⋮      ⋮          ⋮        ⋮       ⋮      ⋮           ⋮
126095 기타        1       29.03   0.31    1357.52     10
126096 기타        2       160.78  1.45    6246.44     47
126097 20대        4       145.31  1.24    5306.57     39
126098 30대        1       0.05    0.00       1.52     16
126099 30대        1       137.14  0.77    3330.00     22
126100 20대        1       21.83   0.25    1059.93      5
126101 30대        1       27.90   0.30    1280.88      9
126102 40대        1       47.93   0.62    2689.92     18
126103 10대        1       13.58   0.11     463.50      3
126104 20대        3       84.08   0.69    2996.45     25
126105 30대        1       133.29  0.89    3824.93     24
126106 40대        1       264.56  1.99    8565.00     48
126107 20대       14       1028.19 9.52   41033.07    375
126108 30대        5       129.81  1.04    4498.56     34
126109 40대        3       51.43   0.40    1709.00     13
126110 50대        1       264.71  1.99    8570.00     38
126111 60대        1       119.35  1.21    5196.45     24
126112 기타        3       61.64   0.58    2522.37      9
126113 20대        1       39.31   0.32    1360.00     10
126114 10대        1       15.88   0.18     770.95      8
126115 20대        7       213.34  2.05    8877.14     76
126116 30대        6       715.40  8.25   35593.84    277
126117 40대        1       44.56   0.47    2009.34     17
126118 기타        5       430.63  3.83   16498.12     93
126119 20대       13       718.05  5.77   24829.96    304
126120 30대        5       243.72  2.05    8884.57    169
126121 40대        6       729.13  6.52   28126.87    290
126122 50대        5       483.55  3.80   16390.52    144
126123 60대        1       57.95   0.54    2322.90     19
126124 기타        3       126.20  1.01    4342.59     25

In [ ]:
selected_DF04 <- f_DF04 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대코드, 이용건수)
selected_DF04

       대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수
1      2022-04-01 1201       일일(비회원) \\N  기타        1
2      2022-04-01 1201       일일(회원)   \\N  20대        4
3      2022-04-01 1201       일일(회원)   \\N  30대        3
4      2022-04-01 1201       일일(회원)   NA   30대        1
5      2022-04-01 1201       일일(회원)   F    30대        1
6      2022-04-01 1201       일일(회원)   F    40대        1
7      2022-04-01 1201       일일(회원)   F    기타        1
8      2022-04-01 1201       일일(회원)   M    30대        2
9      2022-04-01 1201       일일(회원)   M    50대        1
10     2022-04-01 1201       정기         \\N  20대        5
11     2022-04-01 1201       정기         \\N  30대       11
12     2022-04-01 1201       정기         \\N  40대        4
13     2022-04-01 1201       정기         \\N  50대        3
14     2022-04-01 1201       정기         NA   40대        2
15     2022-04-01 1201       정기         F    20대        4
16     2022-04-01 1201       정기         F    30대        9
17     2022-04-01 1201       정기         F    40대        4
18     2022-04-01 1201       정기         F    60대        2
19     2022-04-01 1201       정기         F    기타        2
20     2022-04-01 1201       정기         M    20대        5
21     2022-04-01 1201       정기         M    30대        8
22     2022-04-01 1201       정기         M    40대        3
23     2022-04-01 1201       정기         M    50대        2
24     2022-04-01 1201       정기         M    60대        1
25     2022-04-01 1201       정기         M    기타        2
26     2022-04-01 1203       일일(회원)   \\N  20대        6
27     2022-04-01 1203       일일(회원)   \\N  30대        1
28     2022-04-01 1203       일일(회원)   F    10대        1
29     2022-04-01 1203       일일(회원)   F    20대        5
30     2022-04-01 1203       일일(회원)   F    30대        2
⋮      ⋮          ⋮          ⋮            ⋮    ⋮          ⋮
126095 2022-04-30 4897       단체         F    기타        1
126096 2022-04-30 4897       일일(비회원) \\N  기타        2
126097 2022-04-30 4897       일일(회원)   \\N  20대        4
126098 2022-04-30 4897       일일(회원)   \\N  30대        1
126099 2022-04-30 4897       일일(회원)   NA   30대        1
126100 2022-04-30 4897       일일(회원)   F    20대        1
126101 2022-04-30 4897       일일(회원)   F    30대        1
126102 2022-04-30 4897       일일(회원)   F    40대        1
126103 2022-04-30 4897       일일(회원)   M    10대        1
126104 2022-04-30 4897       일일(회원)   M    20대        3
126105 2022-04-30 4897       일일(회원)   M    30대        1
126106 2022-04-30 4897       일일(회원)   M    40대        1
126107 2022-04-30 4897       정기         \\N  20대       14
126108 2022-04-30 4897       정기         \\N  30대        5
126109 2022-04-30 4897       정기         \\N  40대        3
126110 2022-04-30 4897       정기         \\N  50대        1
126111 2022-04-30 4897       정기         \\N  60대        1
126112 2022-04-30 4897       정기         \\N  기타        3
126113 2022-04-30 4897       정기         NA   20대        1
126114 2022-04-30 4897       정기         F    10대        1
126115 2022-04-30 4897       정기         F    20대        7
126116 2022-04-30 4897       정기         F    30대        6
126117 2022-04-30 4897       정기         F    40대        1
126118 2022-04-30 4897       정기         F    기타        5
126119 2022-04-30 4897       정기         M    20대       13
126120 2022-04-30 4897       정기         M    30대        5
126121 2022-04-30 4897       정기         M    40대        6
126122 2022-04-30 4897       정기         M    50대        5
126123 2022-04-30 4897       정기         M    60대        1
126124 2022-04-30 4897       정기         M    기타        3

In [ ]:
selected_DF04$`대여구분코드`<-ifelse(selected_DF04$`대여구분코드`=='정기',1,0)

In [ ]:
selected_DF04$`성별`<-ifelse(selected_DF04$`성별`=='M',0,ifelse(selected_DF04$`성별`=='F',1,2))

In [ ]:
selected_DF04$`연령대코드`<-ifelse(selected_DF04$`연령대코드`=='10대',0,ifelse(selected_DF04$`연령대코드`=='20대',1,
ifelse(selected_DF04$`연령대코드`=='30대',2,ifelse(selected_DF04$`연령대코드`=='40대',3,ifelse(selected_DF04$`연령대코드`=='50대',4,
ifelse(selected_DF04$`연령대코드`=='60대',5,ifelse(selected_DF04$`연령대코드`=='70대이상',6,7)))))))

In [ ]:
selected_DF04

       대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수
1      2022-04-01 1201       0             2   7           1
2      2022-04-01 1201       0             2   1           4
3      2022-04-01 1201       0             2   2           3
4      2022-04-01 1201       0            NA   2           1
5      2022-04-01 1201       0             1   2           1
6      2022-04-01 1201       0             1   3           1
7      2022-04-01 1201       0             1   7           1
8      2022-04-01 1201       0             0   2           2
9      2022-04-01 1201       0             0   4           1
10     2022-04-01 1201       1             2   1           5
11     2022-04-01 1201       1             2   2          11
12     2022-04-01 1201       1             2   3           4
13     2022-04-01 1201       1             2   4           3
14     2022-04-01 1201       1            NA   3           2
15     2022-04-01 1201       1             1   1           4
16     2022-04-01 1201       1             1   2           9
17     2022-04-01 1201       1             1   3           4
18     2022-04-01 1201       1             1   5           2
19     2022-04-01 1201       1             1   7           2
20     2022-04-01 1201       1             0   1           5
21     2022-04-01 1201       1             0   2           8
22     2022-04-01 1201       1             0   3           3
23     2022-04-01 1201       1             0   4           2
24     2022-04-01 1201       1             0   5           1
25     2022-04-01 1201       1             0   7           2
26     2022-04-01 1203       0             2   1           6
27     2022-04-01 1203       0             2   2           1
28     2022-04-01 1203       0             1   0           1
29     2022-04-01 1203       0             1   1           5
30     2022-04-01 1203       0             1   2           2
⋮      ⋮          ⋮          ⋮            ⋮    ⋮          ⋮
126095 2022-04-30 4897       0             1   7           1
126096 2022-04-30 4897       0             2   7           2
126097 2022-04-30 4897       0             2   1           4
126098 2022-04-30 4897       0             2   2           1
126099 2022-04-30 4897       0            NA   2           1
126100 2022-04-30 4897       0             1   1           1
126101 2022-04-30 4897       0             1   2           1
126102 2022-04-30 4897       0             1   3           1
126103 2022-04-30 4897       0             0   0           1
126104 2022-04-30 4897       0             0   1           3
126105 2022-04-30 4897       0             0   2           1
126106 2022-04-30 4897       0             0   3           1
126107 2022-04-30 4897       1             2   1          14
126108 2022-04-30 4897       1             2   2           5
126109 2022-04-30 4897       1             2   3           3
126110 2022-04-30 4897       1             2   4           1
126111 2022-04-30 4897       1             2   5           1
126112 2022-04-30 4897       1             2   7           3
126113 2022-04-30 4897       1            NA   1           1
126114 2022-04-30 4897       1             1   0           1
126115 2022-04-30 4897       1             1   1           7
126116 2022-04-30 4897       1             1   2           6
126117 2022-04-30 4897       1             1   3           1
126118 2022-04-30 4897       1             1   7           5
126119 2022-04-30 4897       1             0   1          13
126120 2022-04-30 4897       1             0   2           5
126121 2022-04-30 4897       1             0   3           6
126122 2022-04-30 4897       1             0   4           5
126123 2022-04-30 4897       1             0   5           1
126124 2022-04-30 4897       1             0   7           3

In [ ]:
write.csv(selected_DF04,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.04.csv",row.names=FALSE, na="")

In [ ]:
selected_DF04$'평일/주말' <- ifelse(selected_DF04$대여일자 %in% date$date_time, date$weekend[match(selected_DF04$대여일자, date$date_time)], 2)
selected_DF04

       대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수 평일/주말
1      2022-04-01 1201       0             2   7           1       0
2      2022-04-01 1201       0             2   1           4       0
3      2022-04-01 1201       0             2   2           3       0
4      2022-04-01 1201       0            NA   2           1       0
5      2022-04-01 1201       0             1   2           1       0
6      2022-04-01 1201       0             1   3           1       0
7      2022-04-01 1201       0             1   7           1       0
8      2022-04-01 1201       0             0   2           2       0
9      2022-04-01 1201       0             0   4           1       0
10     2022-04-01 1201       1             2   1           5       0
11     2022-04-01 1201       1             2   2          11       0
12     2022-04-01 1201       1             2   3           4       0
13     2022-04-01 1201       1             2   4           3       0
14     2022-04-01 1201       1            NA   3           2       0
15     2022-04-01 1201       1             1   1           4       0
16     2022-04-01 1201       1             1   2           9       0
17     2022-04-01 1201       1             1   3           4       0
18     2022-04-01 1201       1             1   5           2       0
19     2022-04-01 1201       1             1   7           2       0
20     2022-04-01 1201       1             0   1           5       0
21     2022-04-01 1201       1             0   2           8       0
22     2022-04-01 1201       1             0   3           3       0
23     2022-04-01 1201       1             0   4           2       0
24     2022-04-01 1201       1             0   5           1       0
25     2022-04-01 1201       1             0   7           2       0
26     2022-04-01 1203       0             2   1           6       0
27     2022-04-01 1203       0             2   2           1       0
28     2022-04-01 1203       0             1   0           1       0
29     2022-04-01 1203       0             1   1           5       0
30     2022-04-01 1203       0             1   2           2       0
⋮      ⋮          ⋮          ⋮            ⋮    ⋮          ⋮        ⋮
126095 2022-04-30 4897       0             1   7           1       1
126096 2022-04-30 4897       0             2   7           2       1
126097 2022-04-30 4897       0             2   1           4       1
126098 2022-04-30 4897       0             2   2           1       1
126099 2022-04-30 4897       0            NA   2           1       1
126100 2022-04-30 4897       0             1   1           1       1
126101 2022-04-30 4897       0             1   2           1       1
126102 2022-04-30 4897       0             1   3           1       1
126103 2022-04-30 4897       0             0   0           1       1
126104 2022-04-30 4897       0             0   1           3       1
126105 2022-04-30 4897       0             0   2           1       1
126106 2022-04-30 4897       0             0   3           1       1
126107 2022-04-30 4897       1             2   1          14       1
126108 2022-04-30 4897       1             2   2           5       1
126109 2022-04-30 4897       1             2   3           3       1
126110 2022-04-30 4897       1             2   4           1       1
126111 2022-04-30 4897       1             2   5           1       1
126112 2022-04-30 4897       1             2   7           3       1
126113 2022-04-30 4897       1            NA   1           1       1
126114 2022-04-30 4897       1             1   0           1       1
126115 2022-04-30 4897       1             1   1           7       1
126116 2022-04-30 4897       1             1   2           6       1
126117 2022-04-30 4897       1             1   3           1       1
126118 2022-04-30 4897       1             1   7           5       1
126119 2022-04-30 4897       1             0   1          13       1
126120 2022-04-30 4897       1             0   2           5       1
126121 2022-04-30 4897       1             0   3           6       1
126122 2022-04-30 4897       1             0   4           5       1
126123 2022-04-30 4897       1             0   5           1       1
126124 2022-04-30 4897       1             0   7           3       1

In [ ]:
selected_DF04 <- selected_DF04 %>% select('평일/주말', '대여구분코드', '성별', '연령대코드', '이용건수')
selected_DF04

       평일/주말 대여구분코드 성별 연령대코드 이용건수
1      0         0             2   7           1
2      0         0             2   1           4
3      0         0             2   2           3
4      0         0            NA   2           1
5      0         0             1   2           1
6      0         0             1   3           1
7      0         0             1   7           1
8      0         0             0   2           2
9      0         0             0   4           1
10     0         1             2   1           5
11     0         1             2   2          11
12     0         1             2   3           4
13     0         1             2   4           3
14     0         1            NA   3           2
15     0         1             1   1           4
16     0         1             1   2           9
17     0         1             1   3           4
18     0         1             1   5           2
19     0         1             1   7           2
20     0         1             0   1           5
21     0         1             0   2           8
22     0         1             0   3           3
23     0         1             0   4           2
24     0         1             0   5           1
25     0         1             0   7           2
26     0         0             2   1           6
27     0         0             2   2           1
28     0         0             1   0           1
29     0         0             1   1           5
30     0         0             1   2           2
⋮      ⋮         ⋮            ⋮    ⋮          ⋮
126095 1         0             1   7           1
126096 1         0             2   7           2
126097 1         0             2   1           4
126098 1         0             2   2           1
126099 1         0            NA   2           1
126100 1         0             1   1           1
126101 1         0             1   2           1
126102 1         0             1   3           1
126103 1         0             0   0           1
126104 1         0             0   1           3
126105 1         0             0   2           1
126106 1         0             0   3           1
126107 1         1             2   1          14
126108 1         1             2   2           5
126109 1         1             2   3           3
126110 1         1             2   4           1
126111 1         1             2   5           1
126112 1         1             2   7           3
126113 1         1            NA   1           1
126114 1         1             1   0           1
126115 1         1             1   1           7
126116 1         1             1   2           6
126117 1         1             1   3           1
126118 1         1             1   7           5
126119 1         1             0   1          13
126120 1         1             0   2           5
126121 1         1             0   3           6
126122 1         1             0   4           5
126123 1         1             0   5           1
126124 1         1             0   7           3

In [ ]:
summarized_data_04 <- selected_DF04 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data_04

   대여일자   이용건수_합계
1  2022-04-01 10384
2  2022-04-02 10142
3  2022-04-03 11015
4  2022-04-04 10356
5  2022-04-05 10736
6  2022-04-06 11537
7  2022-04-07 11373
8  2022-04-08 13396
9  2022-04-09 15153
10 2022-04-10 15429
11 2022-04-11 13688
12 2022-04-12 11123
13 2022-04-13  6252
14 2022-04-14 10249
15 2022-04-15 12408
16 2022-04-16 12348
17 2022-04-17 12412
18 2022-04-18 12133
19 2022-04-19 13056
20 2022-04-20 13008
21 2022-04-21 12982
22 2022-04-22 11639
23 2022-04-23 13405
24 2022-04-24 12404
25 2022-04-25 11139
26 2022-04-26 13293
27 2022-04-27 13707
28 2022-04-28 13713
29 2022-04-29 10364
30 2022-04-30 11479

## **5월 전처리**

In [ ]:
#https://drive.google.com/file/d/1H5rGpyiNy0up_6heh8O_YVBAxy8e5fAT/view?usp=sharing
system("gdown --id 1H5rGpyiNy0up_6heh8O_YVBAxy8e5fAT")
system("ls",TRUE)

[1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
[2] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
[3] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.02.csv"
[4] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
[5] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.03.csv"
[6] "서울특별시 공공자전거 이용정보(일별)_22.04.csv"
[7] "서울특별시 공공자전거 이용정보(일별)_22.05.csv"
[8] "sample_data"

In [ ]:
DF05<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_22.05.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF05

Rows: 1669729 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): 대여소번호, 대여소, 대여구분코드, 성별, 연령대코드, 운동량, 탄소량
dbl  (3): 이용건수, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        대여일자   대여소번호 대여소                    대여구분코드   성별
1       2022-05-01 00003      중랑센터                  정기권         M
2       2022-05-01 00102      102. 망원역 1번출구 앞    단체권         \\N
3       2022-05-01 00102      102. 망원역 1번출구 앞    단체권         \\N
4       2022-05-01 00102      102. 망원역 1번출구 앞    단체권         F
5       2022-05-01 00102      102. 망원역 1번출구 앞    일일권(비회원) \\N
6       2022-05-01 00102      102. 망원역 1번출구 앞    일일권         \\N
7       2022-05-01 00102      102. 망원역 1번출구 앞    일일권         \\N
8       2022-05-01 00102      102. 망원역 1번출구 앞    일일권         \\N
9       2022-05-01 00102      102. 망원역 1번출구 앞    일일권         F
10      2022-05-01 00102      102. 망원역 1번출구 앞    일일권         F
11      2022-05-01 00102      102. 망원역 1번출구 앞    일일권         F
12      2022-05-01 00102      102. 망원역 1번출구 앞    일일권         M
13      2022-05-01 00102      102. 망원역 1번출구 앞    일일권         M
14      2022-05-01 00102      102. 망원역 1번출구 앞    일일권         M
15      2022-05-01 00102      102. 망원역 1번출구 앞    일일권         M
16      2022-05-01 00102      102. 망원역 1번출구 앞    일일권         M
17      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         \\N
18      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         \\N
19      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         \\N
20      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         \\N
21      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         \\N
22      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         NA
23      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         NA
24      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         NA
25      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         F
26      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         F
27      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         F
28      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         F
29      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         M
30      2022-05-01 00102      102. 망원역 1번출구 앞    정기권         M
⋮       ⋮          ⋮          ⋮                         ⋮              ⋮
1669700 2022-05-31 05853      5853. 여의도역2번출구 앞  일일권         M
1669701 2022-05-31 05853      5853. 여의도역2번출구 앞  일일권         M
1669702 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         \\N
1669703 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         \\N
1669704 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         \\N
1669705 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         \\N
1669706 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         \\N
1669707 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         \\N
1669708 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         NA
1669709 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         NA
1669710 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         NA
1669711 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         F
1669712 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         F
1669713 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         F
1669714 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         M
1669715 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         M
1669716 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         M
1669717 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         M
1669718 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         M
1669719 2022-05-31 05853      5853. 여의도역2번출구 앞  정기권         M
1669720 2022-05-31 09992      사대문센터                단체권         M
1669721 2022-05-31 09998      9998. 영남주차장 정비센터 정기권         \\N
1669722 2022-05-31 09999      상담센터                  단체권         M
1669723 2022-05-31 09999      상담센터                  일일권         \\N
1669724 2022-05-31 09999      상담센터                  일일권         \\N
1669725 2022-05-31 09999      상담센터                  일일권         M
1669726 2022-05-31 09999      상담센터                  일일권         M
1669727 2022-05-31 09999      상담센터                  정기권         \\N
1669728 2022-05-31 09999      상담센터                  정기권         M
1669729 2022-05-31 99999      99999. 영남단말기정비     정기권         \\N
        연령대코드 이용건수 운동량  탄소량 이동거리(M) 이용시간(분)
1       40대        1       151.98  1.17    5050.00     27
2       20대        3       91.76   0.94    4064.94     43
3       40대        1       77.87   0.86    3710.00     38
4       20대        2       162.88  1.94    8394.12     58
5       기타        2       193.78  1.75    7528.39     52
6       20대       16       1058.21 9.30   40064.36    533
7       30대        9       1009.90 9.84   42420.17    384
8       40대        2       131.07  1.33    5732.79     68
9       20대        6       779.41  7.03   30280.16    268
10      30대        6       195.87  2.03    8767.45    135
11      40대        3       337.70  3.05   13119.58    159
12      10대        1       154.63  1.33    5742.33     76
13      20대       14       1514.21 12.39  53384.81    505
14      30대        6       379.66  2.95   12749.83    105
15      40대        1       235.52  1.84    7930.00     58
16      기타        2       322.78  2.74   11790.82     74
17      20대       14       840.55  8.25   35568.15    334
18      30대        9       588.24  5.31   22869.92    175
19      40대        2       77.34   0.52    2255.35     15
20      50대        1       46.33   0.42    1800.07     12
21      60대        1       21.62   0.19     840.00      7
22      20대        1       202.39  1.25    5379.86    102
23      40대        1       19.95   0.18     775.03      6
24      60대        1       47.64   0.43    1850.91     10
25      20대       17       1250.96 11.93  51396.55    436
26      30대        8       639.35  5.94   25582.12    269
27      40대        3       186.27  1.75    7541.35     62
28      기타        2       67.94   0.68    2941.90     43
29      20대       10       532.55  4.30   18500.51    233
30      30대        9       534.66  4.14   17816.76    137
⋮       ⋮          ⋮        ⋮       ⋮      ⋮           ⋮
1669700 40대        1       63.67   0.44    1891.52     18
1669701 50대        1       559.47  4.10   17660.00     98
1669702 20대        3       270.16  2.33   10039.11     87
1669703 30대        4       164.85  1.41    6065.65     52
1669704 40대        4       383.51  3.72   16020.80    163
1669705 50대        2       83.17   0.55    2347.02     98
1669706 70대이상    1       19.25   0.17     747.72      5
1669707 기타        1       35.16   0.34    1480.00     10
1669708 20대        1       209.74  1.76    7566.37    122
1669709 30대        1       34.43   0.29    1260.00      7
1669710 40대        1       226.17  1.79    7717.90     44
1669711 20대        6       207.04  2.05    8838.65    164
1669712 30대        2       583.45  4.61   19858.48     95
1669713 기타        1       18.39   0.25    1080.00      7
1669714 20대        4       130.18  1.13    4896.78     34
1669715 30대       18       1349.17 10.75  46220.84    378
1669716 40대        4       143.72  1.18    5074.24     25
1669717 50대        4       68.45   0.56    2352.00     15
1669718 70대이상    3       157.69  1.36    5855.78    135
1669719 기타        2       342.38  2.78   12012.02     49
1669720 40대        1       76.65   0.55    2360.53     25
1669721 기타        2       0.00    0.00       0.00      0
1669722 10대        2       241.56  2.12    9104.32     13
1669723 20대        1       215.99  2.30    9916.75     56
1669724 40대        1       193.05  1.74    7500.00     49
1669725 20대        1       25.31   0.18     770.00      7
1669726 50대        1       18.02   0.16     700.00      5
1669727 30대        2       329.88  3.16   13631.74     69
1669728 50대        1       81.25   0.57    2442.63     16
1669729 기타        2       0.00    0.00       0.00      0

In [ ]:
DF05$대여소번호 <- as.numeric(DF05$대여소번호)

In [ ]:
f_DF05<-DF05%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897,5751,5752,5753,5760,5756,5758,5759,5761,5763,5764,5765,5766,5767))
f_DF05

       대여일자   대여소번호 대여소                         대여구분코드   성별
1      2022-05-01 1201       1201. 가락시장역 3번 출구      일일권(비회원) \\N
2      2022-05-01 1201       1201. 가락시장역 3번 출구      일일권         \\N
3      2022-05-01 1201       1201. 가락시장역 3번 출구      일일권         \\N
4      2022-05-01 1201       1201. 가락시장역 3번 출구      일일권         \\N
5      2022-05-01 1201       1201. 가락시장역 3번 출구      일일권         F
6      2022-05-01 1201       1201. 가락시장역 3번 출구      일일권         F
7      2022-05-01 1201       1201. 가락시장역 3번 출구      일일권         F
8      2022-05-01 1201       1201. 가락시장역 3번 출구      일일권         M
9      2022-05-01 1201       1201. 가락시장역 3번 출구      일일권         M
10     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         \\N
11     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         \\N
12     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         \\N
13     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         \\N
14     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         \\N
15     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         F
16     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         F
17     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         F
18     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         F
19     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         F
20     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         M
21     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         M
22     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         M
23     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         M
24     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         M
25     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         M
26     2022-05-01 1201       1201. 가락시장역 3번 출구      정기권         M
27     2022-05-01 1203       1203. 밀리아나2빌딩 앞         일일권         \\N
28     2022-05-01 1203       1203. 밀리아나2빌딩 앞         일일권         \\N
29     2022-05-01 1203       1203. 밀리아나2빌딩 앞         일일권         \\N
30     2022-05-01 1203       1203. 밀리아나2빌딩 앞         일일권         F
⋮      ⋮          ⋮          ⋮                              ⋮              ⋮
142019 2022-05-31 5752       5752. 풍납백제문화공원 옆 인근 정기권         F
142020 2022-05-31 5752       5752. 풍납백제문화공원 옆 인근 정기권         F
142021 2022-05-31 5752       5752. 풍납백제문화공원 옆 인근 정기권         M
142022 2022-05-31 5752       5752. 풍납백제문화공원 옆 인근 정기권         M
142023 2022-05-31 5752       5752. 풍납백제문화공원 옆 인근 정기권         M
142024 2022-05-31 5752       5752. 풍납백제문화공원 옆 인근 정기권         M
142025 2022-05-31 5752       5752. 풍납백제문화공원 옆 인근 정기권         M
142026 2022-05-31 5753       5753. 호반써밋                 일일권(비회원) \\N
142027 2022-05-31 5753       5753. 호반써밋                 일일권         \\N
142028 2022-05-31 5753       5753. 호반써밋                 일일권         M
142029 2022-05-31 5753       5753. 호반써밋                 일일권         M
142030 2022-05-31 5753       5753. 호반써밋                 일일권         M
142031 2022-05-31 5753       5753. 호반써밋                 정기권         \\N
142032 2022-05-31 5753       5753. 호반써밋                 정기권         \\N
142033 2022-05-31 5753       5753. 호반써밋                 정기권         \\N
142034 2022-05-31 5753       5753. 호반써밋                 정기권         \\N
142035 2022-05-31 5753       5753. 호반써밋                 정기권         \\N
142036 2022-05-31 5753       5753. 호반써밋                 정기권         \\N
142037 2022-05-31 5753       5753. 호반써밋                 정기권         NA
142038 2022-05-31 5753       5753. 호반써밋                 정기권         F
142039 2022-05-31 5753       5753. 호반써밋                 정기권         F
142040 2022-05-31 5753       5753. 호반써밋                 정기권         F
142041 2022-05-31 5753       5753. 호반써밋                 정기권         F
142042 2022-05-31 5753       5753. 호반써밋                 정기권         F
142043 2022-05-31 5753       5753. 호반써밋                 정기권         M
142044 2022-05-31 5753       5753. 호반써밋                 정기권         M
142045 2022-05-31 5753       5753. 호반써밋                 정기권         M
142046 2022-05-31 5753       5753. 호반써밋                 정기권         M
142047 2022-05-31 5753       5753. 호반써밋                 정기권         M
142048 2022-05-31 5753       5753. 호반써밋                 정기권         M
       연령대코드 이용건수 운동량 탄소량 이동거리(M) 이용시간(분)
1      기타        2       230.85 2.08    8968.37     67
2      20대        3       385.13 3.24   13962.40     97
3      30대        1       171.14 1.35    5840.05     41
4      기타        1       146.04 1.43    6146.45     61
5      10대        2       133.76 1.35    5843.08     35
6      20대        1       35.61  0.38    1634.91     12
7      30대        2       94.93  0.93    4010.09     54
8      10대        4       178.17 1.55    6665.27     47
9      30대        3       296.40 2.31    9919.94    138
10     10대        1       56.60  0.51    2198.77     41
11     20대        5       288.03 2.20    9470.29     94
12     30대       12       938.88 8.55   36882.24    285
13     40대        1       51.46  0.42    1804.85     17
14     50대        1       36.29  0.33    1410.00      7
15     20대        6       301.57 3.20   13774.54    114
16     30대        2       139.68 1.29    5586.02     59
17     40대        1       9.58   0.10     410.00      8
18     50대        2       288.41 3.32   14309.53     69
19     기타        1       32.30  0.29    1254.82      5
20     10대        1       27.33  0.23     972.17      7
21     20대        2       59.64  0.48    2032.23     14
22     30대        3       417.53 3.38   14562.69     92
23     40대        3       228.87 2.00    8603.86     57
24     50대        5       621.59 5.30   22850.78    135
25     60대        1       56.68  0.54    2308.38     11
26     기타        2       34.35  0.27    1157.50     23
27     20대        6       326.19 3.20   13802.52    124
28     40대        1       36.59  0.24    1050.00      6
29     기타        1       0.00   0.67    2876.90     21
30     20대        1       79.77  0.92    3950.00     29
⋮      ⋮          ⋮        ⋮      ⋮      ⋮           ⋮
142019 60대       1        354.44 3.19   13770.00     91
142020 기타       1        0.00   0.00       0.00     18
142021 20대       2        108.70 0.91    3921.52     20
142022 30대       8        348.69 2.71   11696.94    207
142023 40대       4        327.16 2.28    9786.56     93
142024 50대       2        222.40 1.67    7200.00     45
142025 60대       2        258.15 2.32   10029.23     66
142026 기타       1        33.70  0.30    1309.30     10
142027 10대       1        25.53  0.24    1040.00      5
142028 20대       1        71.71  0.62    2663.12     22
142029 30대       1        53.46  0.42    1800.00     13
142030 50대       1        96.95  0.78    3353.67     23
142031 20대       4        101.17 0.93    3959.03     36
142032 30대       6        415.33 3.21   13872.99    147
142033 40대       2        41.83  0.38    1640.00      8
142034 50대       2        218.07 1.58    6790.00     37
142035 60대       1        136.63 1.08    4662.50     27
142036 기타       1        38.56  0.38    1623.03     64
142037 20대       1        30.93  0.25    1070.00      5
142038 20대       1        77.75  0.83    3570.00     39
142039 30대       1        206.44 1.86    8020.33     48
142040 40대       1        57.19  0.59    2533.75     52
142041 50대       3        240.31 2.14    9244.89     66
142042 기타       2        98.42  0.77    3313.76     48
142043 20대       2        46.62  0.35    1478.99      7
142044 30대       4        257.47 2.01    8678.64     77
142045 40대       7        827.84 5.63   24320.50    245
142046 50대       2        185.51 1.65    7098.67     30
142047 60대       2        61.19  0.54    2319.70     41
142048 기타       1        84.88  0.65    2820.25     17

In [ ]:
selected_DF05 <- f_DF05 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대코드, 이용건수)
selected_DF05

       대여일자   대여소번호 대여구분코드   성별 연령대코드 이용건수
1      2022-05-01 1201       일일권(비회원) \\N  기타        2
2      2022-05-01 1201       일일권         \\N  20대        3
3      2022-05-01 1201       일일권         \\N  30대        1
4      2022-05-01 1201       일일권         \\N  기타        1
5      2022-05-01 1201       일일권         F    10대        2
6      2022-05-01 1201       일일권         F    20대        1
7      2022-05-01 1201       일일권         F    30대        2
8      2022-05-01 1201       일일권         M    10대        4
9      2022-05-01 1201       일일권         M    30대        3
10     2022-05-01 1201       정기권         \\N  10대        1
11     2022-05-01 1201       정기권         \\N  20대        5
12     2022-05-01 1201       정기권         \\N  30대       12
13     2022-05-01 1201       정기권         \\N  40대        1
14     2022-05-01 1201       정기권         \\N  50대        1
15     2022-05-01 1201       정기권         F    20대        6
16     2022-05-01 1201       정기권         F    30대        2
17     2022-05-01 1201       정기권         F    40대        1
18     2022-05-01 1201       정기권         F    50대        2
19     2022-05-01 1201       정기권         F    기타        1
20     2022-05-01 1201       정기권         M    10대        1
21     2022-05-01 1201       정기권         M    20대        2
22     2022-05-01 1201       정기권         M    30대        3
23     2022-05-01 1201       정기권         M    40대        3
24     2022-05-01 1201       정기권         M    50대        5
25     2022-05-01 1201       정기권         M    60대        1
26     2022-05-01 1201       정기권         M    기타        2
27     2022-05-01 1203       일일권         \\N  20대        6
28     2022-05-01 1203       일일권         \\N  40대        1
29     2022-05-01 1203       일일권         \\N  기타        1
30     2022-05-01 1203       일일권         F    20대        1
⋮      ⋮          ⋮          ⋮              ⋮    ⋮          ⋮
142019 2022-05-31 5752       정기권         F    60대       1
142020 2022-05-31 5752       정기권         F    기타       1
142021 2022-05-31 5752       정기권         M    20대       2
142022 2022-05-31 5752       정기권         M    30대       8
142023 2022-05-31 5752       정기권         M    40대       4
142024 2022-05-31 5752       정기권         M    50대       2
142025 2022-05-31 5752       정기권         M    60대       2
142026 2022-05-31 5753       일일권(비회원) \\N  기타       1
142027 2022-05-31 5753       일일권         \\N  10대       1
142028 2022-05-31 5753       일일권         M    20대       1
142029 2022-05-31 5753       일일권         M    30대       1
142030 2022-05-31 5753       일일권         M    50대       1
142031 2022-05-31 5753       정기권         \\N  20대       4
142032 2022-05-31 5753       정기권         \\N  30대       6
142033 2022-05-31 5753       정기권         \\N  40대       2
142034 2022-05-31 5753       정기권         \\N  50대       2
142035 2022-05-31 5753       정기권         \\N  60대       1
142036 2022-05-31 5753       정기권         \\N  기타       1
142037 2022-05-31 5753       정기권         NA   20대       1
142038 2022-05-31 5753       정기권         F    20대       1
142039 2022-05-31 5753       정기권         F    30대       1
142040 2022-05-31 5753       정기권         F    40대       1
142041 2022-05-31 5753       정기권         F    50대       3
142042 2022-05-31 5753       정기권         F    기타       2
142043 2022-05-31 5753       정기권         M    20대       2
142044 2022-05-31 5753       정기권         M    30대       4
142045 2022-05-31 5753       정기권         M    40대       7
142046 2022-05-31 5753       정기권         M    50대       2
142047 2022-05-31 5753       정기권         M    60대       2
142048 2022-05-31 5753       정기권         M    기타       1

In [ ]:
selected_DF05$`대여구분코드`<- ifelse(selected_DF05$`대여구분코드`=='정기권',1,0)

In [ ]:
selected_DF05$`성별`<-ifelse(selected_DF05$`성별`=='M',0,ifelse(selected_DF05$`성별`=='F',1,2))

In [ ]:
selected_DF05$`연령대코드`<-ifelse(selected_DF05$`연령대코드`=='10대',0,ifelse(selected_DF05$`연령대코드`=='20대',1,
ifelse(selected_DF05$`연령대코드`=='30대',2,ifelse(selected_DF05$`연령대코드`=='40대',3,ifelse(selected_DF05$`연령대코드`=='50대',4,
ifelse(selected_DF05$`연령대코드`=='60대',5,ifelse(selected_DF05$`연령대코드`=='70대이상',6,7)))))))

In [ ]:
selected_DF05

       대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수
1      2022-05-01 1201       0            2    7           2
2      2022-05-01 1201       0            2    1           3
3      2022-05-01 1201       0            2    2           1
4      2022-05-01 1201       0            2    7           1
5      2022-05-01 1201       0            1    0           2
6      2022-05-01 1201       0            1    1           1
7      2022-05-01 1201       0            1    2           2
8      2022-05-01 1201       0            0    0           4
9      2022-05-01 1201       0            0    2           3
10     2022-05-01 1201       1            2    0           1
11     2022-05-01 1201       1            2    1           5
12     2022-05-01 1201       1            2    2          12
13     2022-05-01 1201       1            2    3           1
14     2022-05-01 1201       1            2    4           1
15     2022-05-01 1201       1            1    1           6
16     2022-05-01 1201       1            1    2           2
17     2022-05-01 1201       1            1    3           1
18     2022-05-01 1201       1            1    4           2
19     2022-05-01 1201       1            1    7           1
20     2022-05-01 1201       1            0    0           1
21     2022-05-01 1201       1            0    1           2
22     2022-05-01 1201       1            0    2           3
23     2022-05-01 1201       1            0    3           3
24     2022-05-01 1201       1            0    4           5
25     2022-05-01 1201       1            0    5           1
26     2022-05-01 1201       1            0    7           2
27     2022-05-01 1203       0            2    1           6
28     2022-05-01 1203       0            2    3           1
29     2022-05-01 1203       0            2    7           1
30     2022-05-01 1203       0            1    1           1
⋮      ⋮          ⋮          ⋮            ⋮    ⋮          ⋮
142019 2022-05-31 5752       1             1   5          1
142020 2022-05-31 5752       1             1   7          1
142021 2022-05-31 5752       1             0   1          2
142022 2022-05-31 5752       1             0   2          8
142023 2022-05-31 5752       1             0   3          4
142024 2022-05-31 5752       1             0   4          2
142025 2022-05-31 5752       1             0   5          2
142026 2022-05-31 5753       0             2   7          1
142027 2022-05-31 5753       0             2   0          1
142028 2022-05-31 5753       0             0   1          1
142029 2022-05-31 5753       0             0   2          1
142030 2022-05-31 5753       0             0   4          1
142031 2022-05-31 5753       1             2   1          4
142032 2022-05-31 5753       1             2   2          6
142033 2022-05-31 5753       1             2   3          2
142034 2022-05-31 5753       1             2   4          2
142035 2022-05-31 5753       1             2   5          1
142036 2022-05-31 5753       1             2   7          1
142037 2022-05-31 5753       1            NA   1          1
142038 2022-05-31 5753       1             1   1          1
142039 2022-05-31 5753       1             1   2          1
142040 2022-05-31 5753       1             1   3          1
142041 2022-05-31 5753       1             1   4          3
142042 2022-05-31 5753       1             1   7          2
142043 2022-05-31 5753       1             0   1          2
142044 2022-05-31 5753       1             0   2          4
142045 2022-05-31 5753       1             0   3          7
142046 2022-05-31 5753       1             0   4          2
142047 2022-05-31 5753       1             0   5          2
142048 2022-05-31 5753       1             0   7          1

In [ ]:
write.csv(selected_DF05,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.05.csv",row.names=FALSE, na="")

In [ ]:
selected_DF05$'평일/주말' <- ifelse(selected_DF05$대여일자 %in% date$date_time, date$weekend[match(selected_DF05$대여일자, date$date_time)], 2)
selected_DF05

       대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수 평일/주말
1      2022-05-01 1201       0            2    7           2       1
2      2022-05-01 1201       0            2    1           3       1
3      2022-05-01 1201       0            2    2           1       1
4      2022-05-01 1201       0            2    7           1       1
5      2022-05-01 1201       0            1    0           2       1
6      2022-05-01 1201       0            1    1           1       1
7      2022-05-01 1201       0            1    2           2       1
8      2022-05-01 1201       0            0    0           4       1
9      2022-05-01 1201       0            0    2           3       1
10     2022-05-01 1201       1            2    0           1       1
11     2022-05-01 1201       1            2    1           5       1
12     2022-05-01 1201       1            2    2          12       1
13     2022-05-01 1201       1            2    3           1       1
14     2022-05-01 1201       1            2    4           1       1
15     2022-05-01 1201       1            1    1           6       1
16     2022-05-01 1201       1            1    2           2       1
17     2022-05-01 1201       1            1    3           1       1
18     2022-05-01 1201       1            1    4           2       1
19     2022-05-01 1201       1            1    7           1       1
20     2022-05-01 1201       1            0    0           1       1
21     2022-05-01 1201       1            0    1           2       1
22     2022-05-01 1201       1            0    2           3       1
23     2022-05-01 1201       1            0    3           3       1
24     2022-05-01 1201       1            0    4           5       1
25     2022-05-01 1201       1            0    5           1       1
26     2022-05-01 1201       1            0    7           2       1
27     2022-05-01 1203       0            2    1           6       1
28     2022-05-01 1203       0            2    3           1       1
29     2022-05-01 1203       0            2    7           1       1
30     2022-05-01 1203       0            1    1           1       1
⋮      ⋮          ⋮          ⋮            ⋮    ⋮          ⋮        ⋮
142019 2022-05-31 5752       1             1   5          1        0
142020 2022-05-31 5752       1             1   7          1        0
142021 2022-05-31 5752       1             0   1          2        0
142022 2022-05-31 5752       1             0   2          8        0
142023 2022-05-31 5752       1             0   3          4        0
142024 2022-05-31 5752       1             0   4          2        0
142025 2022-05-31 5752       1             0   5          2        0
142026 2022-05-31 5753       0             2   7          1        0
142027 2022-05-31 5753       0             2   0          1        0
142028 2022-05-31 5753       0             0   1          1        0
142029 2022-05-31 5753       0             0   2          1        0
142030 2022-05-31 5753       0             0   4          1        0
142031 2022-05-31 5753       1             2   1          4        0
142032 2022-05-31 5753       1             2   2          6        0
142033 2022-05-31 5753       1             2   3          2        0
142034 2022-05-31 5753       1             2   4          2        0
142035 2022-05-31 5753       1             2   5          1        0
142036 2022-05-31 5753       1             2   7          1        0
142037 2022-05-31 5753       1            NA   1          1        0
142038 2022-05-31 5753       1             1   1          1        0
142039 2022-05-31 5753       1             1   2          1        0
142040 2022-05-31 5753       1             1   3          1        0
142041 2022-05-31 5753       1             1   4          3        0
142042 2022-05-31 5753       1             1   7          2        0
142043 2022-05-31 5753       1             0   1          2        0
142044 2022-05-31 5753       1             0   2          4        0
142045 2022-05-31 5753       1             0   3          7        0
142046 2022-05-31 5753       1             0   4          2        0
142047 2022-05-31 5753       1             0   5          2        0
142048 2022-05-31 5753       1             0   7          1        0

In [ ]:
selected_DF05 <- selected_DF05 %>% select('평일/주말', '대여구분코드', '성별', '연령대코드', '이용건수')
selected_DF05

       평일/주말 대여구분코드 성별 연령대코드 이용건수
1      1         0            2    7           2
2      1         0            2    1           3
3      1         0            2    2           1
4      1         0            2    7           1
5      1         0            1    0           2
6      1         0            1    1           1
7      1         0            1    2           2
8      1         0            0    0           4
9      1         0            0    2           3
10     1         1            2    0           1
11     1         1            2    1           5
12     1         1            2    2          12
13     1         1            2    3           1
14     1         1            2    4           1
15     1         1            1    1           6
16     1         1            1    2           2
17     1         1            1    3           1
18     1         1            1    4           2
19     1         1            1    7           1
20     1         1            0    0           1
21     1         1            0    1           2
22     1         1            0    2           3
23     1         1            0    3           3
24     1         1            0    4           5
25     1         1            0    5           1
26     1         1            0    7           2
27     1         0            2    1           6
28     1         0            2    3           1
29     1         0            2    7           1
30     1         0            1    1           1
⋮      ⋮         ⋮            ⋮    ⋮          ⋮
142019 0         1             1   5          1
142020 0         1             1   7          1
142021 0         1             0   1          2
142022 0         1             0   2          8
142023 0         1             0   3          4
142024 0         1             0   4          2
142025 0         1             0   5          2
142026 0         0             2   7          1
142027 0         0             2   0          1
142028 0         0             0   1          1
142029 0         0             0   2          1
142030 0         0             0   4          1
142031 0         1             2   1          4
142032 0         1             2   2          6
142033 0         1             2   3          2
142034 0         1             2   4          2
142035 0         1             2   5          1
142036 0         1             2   7          1
142037 0         1            NA   1          1
142038 0         1             1   1          1
142039 0         1             1   2          1
142040 0         1             1   3          1
142041 0         1             1   4          3
142042 0         1             1   7          2
142043 0         1             0   1          2
142044 0         1             0   2          4
142045 0         1             0   3          7
142046 0         1             0   4          2
142047 0         1             0   5          2
142048 0         1             0   7          1

In [ ]:
summarized_data_05 <- selected_DF05 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data_05

   대여일자   이용건수_합계
1  2022-05-01 11691
2  2022-05-02 13337
3  2022-05-03 14107
4  2022-05-04 15143
5  2022-05-05 15204
6  2022-05-06 14865
7  2022-05-07 13199
8  2022-05-08  7852
9  2022-05-09 14482
10 2022-05-10 15366
11 2022-05-11 15168
12 2022-05-12 15460
13 2022-05-13 15815
14 2022-05-14 14295
15 2022-05-15 14254
16 2022-05-16 14562
17 2022-05-17 15330
18 2022-05-18 13436
19 2022-05-19 15238
20 2022-05-20 15929
21 2022-05-21 14657
22 2022-05-22 13887
23 2022-05-23 14321
24 2022-05-24 15672
25 2022-05-25 12272
26 2022-05-26 15349
27 2022-05-27 17067
28 2022-05-28 15883
29 2022-05-29 14163
30 2022-05-30 14127
31 2022-05-31 16460

## **6월 전처리**

In [ ]:
#https://drive.google.com/file/d/1rqmBkWRneMg3Oy10xLNn_JEz3TXNrBHm/view?usp=sharing
system("gdown --id 1rqmBkWRneMg3Oy10xLNn_JEz3TXNrBHm")
system("ls",TRUE)

 [1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [2] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [3] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [4] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [5] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [6] "서울특별시 공공자전거 이용정보(일별)_22.04.csv"
 [7] "서울특별시 공공자전거 이용정보(일별)_22.05.csv"
 [8] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.05.csv"
 [9] "서울특별시 공공자전거 이용정보(일별)_22.06.csv"
[10] "sample_data"

In [ ]:
DF06<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_22.06.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF06

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 1475868 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): 대여소번호, 대여소, 대여구분코드, 성별, 연령대코드
dbl  (5): 이용건수, 운동량, 탄소량, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        대여일자   대여소번호 대여소
1       2022-06-01 00003      중랑센터
2       2022-06-01 00102      102. 망원역 1번출구 앞
3       2022-06-01 00102      102. 망원역 1번출구 앞
4       2022-06-01 00102      102. 망원역 1번출구 앞
5       2022-06-01 00102      102. 망원역 1번출구 앞
6       2022-06-01 00102      102. 망원역 1번출구 앞
7       2022-06-01 00102      102. 망원역 1번출구 앞
8       2022-06-01 00102      102. 망원역 1번출구 앞
9       2022-06-01 00102      102. 망원역 1번출구 앞
10      2022-06-01 00102      102. 망원역 1번출구 앞
11      2022-06-01 00102      102. 망원역 1번출구 앞
12      2022-06-01 00102      102. 망원역 1번출구 앞
13      2022-06-01 00102      102. 망원역 1번출구 앞
14      2022-06-01 00102      102. 망원역 1번출구 앞
15      2022-06-01 00102      102. 망원역 1번출구 앞
16      2022-06-01 00102      102. 망원역 1번출구 앞
17      2022-06-01 00102      102. 망원역 1번출구 앞
18      2022-06-01 00102      102. 망원역 1번출구 앞
19      2022-06-01 00102      102. 망원역 1번출구 앞
20      2022-06-01 00102      102. 망원역 1번출구 앞
21      2022-06-01 00102      102. 망원역 1번출구 앞
22      2022-06-01 00102      102. 망원역 1번출구 앞
23      2022-06-01 00102      102. 망원역 1번출구 앞
24      2022-06-01 00102      102. 망원역 1번출구 앞
25      2022-06-01 00102      102. 망원역 1번출구 앞
26      2022-06-01 00102      102. 망원역 1번출구 앞
27      2022-06-01 00102      102. 망원역 1번출구 앞
28      2022-06-01 00102      102. 망원역 1번출구 앞
29      2022-06-01 00102      102. 망원역 1번출구 앞
30      2022-06-01 00102      102. 망원역 1번출구 앞
⋮       ⋮          ⋮          ⋮
1475839 2022-06-30 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
1475840 2022-06-30 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
1475841 2022-06-30 05301      5301. 상계주공1단지 버스정류장 옆(대원빌딩 앞)
1475842 2022-06-30 05305      5305. 대륜E&S 서울지사 앞
1475843 2022-06-30 05305      5305. 대륜E&S 서울지사 앞
1475844 2022-06-30 05305      5305. 대륜E&S 서울지사 앞
1475845 2022-06-30 05306      5306. 동신아파트 후문 옆
1475846 2022-06-30 05306      5306. 동신아파트 후문 옆
1475847 2022-06-30 05752      5752. 풍납백제문화공원 옆 인근
1475848 2022-06-30 05752      5752. 풍납백제문화공원 옆 인근
1475849 2022-06-30 05752      5752. 풍납백제문화공원 옆 인근
1475850 2022-06-30 05753      5753. 호반써밋
1475851 2022-06-30 05753      5753. 호반써밋
1475852 2022-06-30 05753      5753. 호반써밋
1475853 2022-06-30 05851      5851. 도림천 건널목 위
1475854 2022-06-30 05851      5851. 도림천 건널목 위
1475855 2022-06-30 05853      5853. 여의도역2번출구 앞
1475856 2022-06-30 05853      5853. 여의도역2번출구 앞
1475857 2022-06-30 05853      5853. 여의도역2번출구 앞
1475858 2022-06-30 05853      5853. 여의도역2번출구 앞
1475859 2022-06-30 05854      5854. 신한금융투자 앞
1475860 2022-06-30 05854      5854. 신한금융투자 앞
1475861 2022-06-30 05854      5854. 신한금융투자 앞
1475862 2022-06-30 05854      5854. 신한금융투자 앞
1475863 2022-06-30 05854      5854. 신한금융투자 앞
1475864 2022-06-30 05854      5854. 신한금융투자 앞
1475865 2022-06-30 05855      5855. 하이투자증권 앞
1475866 2022-06-30 05855      5855. 하이투자증권 앞
1475867 2022-06-30 09999      상담센터
1475868 2022-06-30 09999      상담센터
        대여구분코드   성별 연령대코드 이용건수 운동량  탄소량 이동거리(M)
1       정기권         M    50대        1         54.69  0.43    1841.50
2       단체권         \\N  20대        2        246.76  2.63   11329.76
3       일일권(비회원) \\N  기타        6        689.20  6.21   26775.46
4       일일권         \\N  20대       12        679.04  6.09   26277.80
5       일일권         \\N  30대        3        292.92  2.61   11260.00
6       일일권         \\N  40대        2        400.33  3.58   15430.00
7       일일권         NA   20대        2         97.20  0.77    3334.69
8       일일권         F    20대       12        755.46  8.44   36344.45
9       일일권         F    30대        3        354.92  3.24   13928.96
10      일일권         F    40대        1          5.46  0.07     287.50
11      일일권         F    기타        2        383.00  3.45   14879.56
12      일일권         M    20대       12       1495.67 12.37   53312.35
13      일일권         M    30대        5        343.35  2.55   10968.04
14      일일권         M    40대        2        304.72  2.58   11120.00
15      일일권         M    기타        1         68.83  0.62    2673.94
16      정기권         \\N  10대        1         75.85  0.55    2364.76
17      정기권         \\N  20대       37       2667.67 23.94  103349.97
18      정기권         \\N  30대       21       1526.99 13.39   57776.55
19      정기권         \\N  40대        4        261.63  2.14    9223.55
20      정기권         \\N  50대        1         42.75  0.29    1270.00
21      정기권         \\N  60대        1         19.68  0.13     571.29
22      정기권         NA   20대        3        129.25  1.23    5305.86
23      정기권         NA   30대        1         42.13  0.31    1330.00
24      정기권         F    20대       14        500.65  5.31   22880.73
25      정기권         F    30대       16       1309.33 13.04   56142.95
26      정기권         F    40대        6        339.51  3.22   13898.87
27      정기권         F    50대        1        184.00  1.12    4840.00
28      정기권         F    기타        6        433.30  4.41   18980.68
29      정기권         M    10대        1        366.17  3.25   14010.00
30      정기권         M    20대       20       1400.11 11.91   51351.88
⋮       ⋮              ⋮    ⋮          ⋮        ⋮       ⋮      ⋮
1475839 일일권         NA   30대       1         28.11  0.25   1092.20
1475840 정기권         M    20대       1         35.77  0.32   1389.64
1475841 정기권         M    40대       1         92.31  0.60   2590.00
1475842 일일권         M    20대       1         18.32  0.15    660.97
1475843 정기권         \\N  30대       1         59.54  0.42   1790.00
1475844 정기권         M    40대       1         58.61  0.34   1480.00
1475845 일일권         F    10대       1         45.60  0.41   1771.59
1475846 정기권         M    10대       1         43.97  0.33   1441.94
1475847 정기권         \\N  20대       1         24.75  0.21    892.76
1475848 정기권         \\N  30대       1         33.37  0.23    980.00
1475849 정기권         M    30대       1         29.80  0.29   1254.06
1475850 정기권         NA   40대       1         14.70  0.13    545.78
1475851 정기권         M    20대       1         33.88  0.29   1240.00
1475852 정기권         M    40대       2        208.65  1.48   6404.29
1475853 일일권         M    기타       1        211.32  1.55   6670.59
1475854 정기권         F    40대       1        140.48  1.50   6450.00
1475855 일일권         M    30대       2        126.04  1.12   4844.80
1475856 정기권         \\N  30대       1         22.51  0.18    778.53
1475857 정기권         \\N  40대       1         15.32  0.12    496.11
1475858 정기권         M    20대       1        135.43  1.10   4750.00
1475859 정기권         F    20대       1         34.41  0.31   1336.72
1475860 정기권         F    40대       1        119.99  1.17   5050.00
1475861 정기권         F    기타       1         77.84  0.91   3931.50
1475862 정기권         M    30대       2         68.89  0.39   1698.21
1475863 정기권         M    40대       1         34.44  0.30   1298.03
1475864 정기권         M    60대       1         37.89  0.31   1347.73
1475865 일일권         F    30대       1         57.78  0.66   2860.97
1475866 정기권         M    30대       1         19.66  0.15    636.60
1475867 정기권         \\N  40대       1            NA    NA      0.00
1475868 정기권         M    40대       1        119.99  0.70   3030.00
        이용시간(분)
1         11
2        132
3        205
4        337
5         96
6         91
7         25
8        455
9        170
10         4
11       165
12       495
13       101
14       104
15        28
16        13
17      1421
18       549
19       117
20        10
21        44
22        81
23        11
24       291
25       411
26       257
27        27
28       224
29        77
30       845
⋮       ⋮
1475839   8
1475840   7
1475841  14
1475842   4
1475843  18
1475844  11
1475845   9
1475846   6
1475847  15
1475848   5
1475849   5
1475850   3
1475851   7
1475852 129
1475853  66
1475854  58
1475855 468
1475856   9
1475857   4
1475858  76
1475859   9
1475860  28
1475861  27
1475862  13
1475863  10
1475864  14
1475865  16
1475866   3
1475867   2
1475868  27

In [ ]:
DF06$대여소번호 <- as.numeric(DF06$대여소번호)

In [ ]:
f_DF06<-DF06%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897,5751,5752,5753,5760,5756,5758,5759,5761,5763,5764,5765,5766,5767))
f_DF06

       대여일자   대여소번호 대여소
1      2022-06-01 1201       1201. 가락시장역 3번 출구
2      2022-06-01 1201       1201. 가락시장역 3번 출구
3      2022-06-01 1201       1201. 가락시장역 3번 출구
4      2022-06-01 1201       1201. 가락시장역 3번 출구
5      2022-06-01 1201       1201. 가락시장역 3번 출구
6      2022-06-01 1201       1201. 가락시장역 3번 출구
7      2022-06-01 1201       1201. 가락시장역 3번 출구
8      2022-06-01 1201       1201. 가락시장역 3번 출구
9      2022-06-01 1201       1201. 가락시장역 3번 출구
10     2022-06-01 1201       1201. 가락시장역 3번 출구
11     2022-06-01 1201       1201. 가락시장역 3번 출구
12     2022-06-01 1201       1201. 가락시장역 3번 출구
13     2022-06-01 1201       1201. 가락시장역 3번 출구
14     2022-06-01 1201       1201. 가락시장역 3번 출구
15     2022-06-01 1201       1201. 가락시장역 3번 출구
16     2022-06-01 1201       1201. 가락시장역 3번 출구
17     2022-06-01 1201       1201. 가락시장역 3번 출구
18     2022-06-01 1201       1201. 가락시장역 3번 출구
19     2022-06-01 1201       1201. 가락시장역 3번 출구
20     2022-06-01 1201       1201. 가락시장역 3번 출구
21     2022-06-01 1201       1201. 가락시장역 3번 출구
22     2022-06-01 1201       1201. 가락시장역 3번 출구
23     2022-06-01 1201       1201. 가락시장역 3번 출구
24     2022-06-01 1201       1201. 가락시장역 3번 출구
25     2022-06-01 1201       1201. 가락시장역 3번 출구
26     2022-06-01 1201       1201. 가락시장역 3번 출구
27     2022-06-01 1201       1201. 가락시장역 3번 출구
28     2022-06-01 1201       1201. 가락시장역 3번 출구
29     2022-06-01 1201       1201. 가락시장역 3번 출구
30     2022-06-01 1201       1201. 가락시장역 3번 출구
⋮      ⋮          ⋮          ⋮
126216 2022-06-30 4882       4882. 위례포레샤인18단지 1802동
126217 2022-06-30 4883       4883. 위례포레샤인18단지 1812동
126218 2022-06-30 4884       4884. H비즈니스파크
126219 2022-06-30 4884       4884. H비즈니스파크
126220 2022-06-30 4884       4884. H비즈니스파크
126221 2022-06-30 4884       4884. H비즈니스파크
126222 2022-06-30 4886       4886. 배명고등학교 건너편
126223 2022-06-30 4886       4886. 배명고등학교 건너편
126224 2022-06-30 4886       4886. 배명고등학교 건너편
126225 2022-06-30 4888       4888. 둔촌오륜역 2번출구
126226 2022-06-30 4889       4889. 마천역 1번 출구 인근②
126227 2022-06-30 4889       4889. 마천역 1번 출구 인근②
126228 2022-06-30 4891       4891. 위례포레샤인17단지 위례대로 방면
126229 2022-06-30 4892       4892. 성내유수지 체육공원
126230 2022-06-30 4892       4892. 성내유수지 체육공원
126231 2022-06-30 4895       4895. 위례포레샤인15단지 상가
126232 2022-06-30 4895       4895. 위례포레샤인15단지 상가
126233 2022-06-30 4895       4895. 위례포레샤인15단지 상가
126234 2022-06-30 4896       4896. 위례포레샤인15단지
126235 2022-06-30 4897       4897. 잠실주공5단지1
126236 2022-06-30 4897       4897. 잠실주공5단지1
126237 2022-06-30 4897       4897. 잠실주공5단지1
126238 2022-06-30 4897       4897. 잠실주공5단지1
126239 2022-06-30 4897       4897. 잠실주공5단지1
126240 2022-06-30 5752       5752. 풍납백제문화공원 옆 인근
126241 2022-06-30 5752       5752. 풍납백제문화공원 옆 인근
126242 2022-06-30 5752       5752. 풍납백제문화공원 옆 인근
126243 2022-06-30 5753       5753. 호반써밋
126244 2022-06-30 5753       5753. 호반써밋
126245 2022-06-30 5753       5753. 호반써밋
       대여구분코드   성별 연령대코드 이용건수 운동량  탄소량 이동거리(M)
1      단체권         M    40대        3        392.17  3.54  15235.86
2      일일권(비회원) \\N  기타        1         68.21  0.61   2650.00
3      일일권(비회원) F    기타        1         32.69  0.29   1270.00
4      일일권         \\N  20대        9        451.85  4.41  18970.89
5      일일권         \\N  30대        7        687.59  5.80  25054.97
6      일일권         \\N  40대        1        338.58  2.64  11400.00
7      일일권         F    10대        1         45.44  0.59   2550.00
8      일일권         F    20대        2        163.52  1.48   6352.99
9      일일권         F    30대        1         14.75  0.16    689.93
10     일일권         F    40대        1         70.50  0.69   2967.16
11     일일권         F    기타        1         68.67  0.67   2890.02
12     일일권         M    20대        4        240.59  2.23   9632.81
13     일일권         M    30대        5        254.49  2.12   9156.77
14     일일권         M    40대        1         25.03  0.18    790.00
15     일일권         M    기타        1        591.95  4.45  19164.41
16     정기권         \\N  20대       10       1501.69 12.85  55444.42
17     정기권         \\N  30대       10        606.39  5.33  22937.30
18     정기권         \\N  40대        3        135.45  1.17   5060.00
19     정기권         \\N  50대        3        214.62  1.94   8360.11
20     정기권         \\N  60대        3        127.15  1.02   4430.00
21     정기권         \\N  기타        1         19.07  0.20    860.00
22     정기권         F    20대        4        132.35  1.38   5976.75
23     정기권         F    30대        7        311.00  3.03  13120.97
24     정기권         F    40대        3         66.72  0.70   3042.49
25     정기권         F    50대        2        168.71  1.62   6992.11
26     정기권         F    기타        3        134.94  1.29   5540.61
27     정기권         M    20대        6        372.48  3.11  13404.22
28     정기권         M    30대       14        628.12  5.25  22730.07
29     정기권         M    40대        9        559.75  4.62  19991.08
30     정기권         M    50대        6        400.96  3.36  14533.03
⋮      ⋮              ⋮    ⋮          ⋮        ⋮       ⋮      ⋮
126216 정기권         M    20대       1         39.28  0.25   1090.00
126217 정기권         \\N  50대       1         53.28  0.48   2070.00
126218 정기권         \\N  30대       2        130.01  1.05   4537.71
126219 정기권         \\N  40대       1        207.41  1.54   6630.00
126220 정기권         F    30대       1         44.94  0.41   1745.88
126221 정기권         M    30대       2         82.95  0.72   3103.84
126222 정기권         \\N  20대       1         27.80  0.25   1080.00
126223 정기권         F    30대       1         65.89  0.59   2560.00
126224 정기권         M    40대       3        113.68  1.56   6740.00
126225 정기권         M    10대       1         37.84  0.44   1910.94
126226 정기권         M    10대       1         23.42  0.22    938.74
126227 정기권         M    50대       1         78.96  0.63   2694.67
126228 정기권         M    50대       1         41.30  0.35   1490.00
126229 정기권         F    50대       1         24.35  0.25   1060.00
126230 정기권         M    10대       1         39.37  0.23    974.76
126231 정기권         M    30대       2         49.50  0.42   1837.98
126232 정기권         M    40대       1         47.01  0.39   1696.05
126233 정기권         M    50대       1         82.40  0.71   3060.00
126234 정기권         M    기타       1         20.20  0.17    750.00
126235 정기권         \\N  20대       1         16.43  0.14    610.00
126236 정기권         \\N  40대       1         17.39  0.14    610.00
126237 정기권         M    20대       2         73.51  0.56   2397.15
126238 정기권         M    40대       1         16.45  0.14    620.00
126239 정기권         M    기타       1         25.02  0.21    890.00
126240 정기권         \\N  20대       1         24.75  0.21    892.76
126241 정기권         \\N  30대       1         33.37  0.23    980.00
126242 정기권         M    30대       1         29.80  0.29   1254.06
126243 정기권         NA   40대       1         14.70  0.13    545.78
126244 정기권         M    20대       1         33.88  0.29   1240.00
126245 정기권         M    40대       2        208.65  1.48   6404.29
       이용시간(분)
1      105
2       29
3       10
4      559
5      164
6       54
7       22
8      102
9        7
10      30
11      31
12      61
13     143
14       5
15      87
16     282
17     215
18      38
19     100
20      32
21      10
22      41
23     114
24      21
25      43
26      30
27      84
28     147
29     120
30      84
⋮      ⋮
126216   5
126217  17
126218  93
126219  47
126220  10
126221  22
126222   4
126223  14
126224 139
126225  14
126226   7
126227  75
126228   6
126229   9
126230   8
126231  14
126232  12
126233  20
126234   5
126235   3
126236   3
126237  19
126238   2
126239  14
126240  15
126241   5
126242   5
126243   3
126244   7
126245 129

In [ ]:
selected_DF06 <- f_DF06 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대코드, 이용건수)
selected_DF06

       대여일자   대여소번호 대여구분코드   성별 연령대코드 이용건수
1      2022-06-01 1201       단체권         M    40대        3
2      2022-06-01 1201       일일권(비회원) \\N  기타        1
3      2022-06-01 1201       일일권(비회원) F    기타        1
4      2022-06-01 1201       일일권         \\N  20대        9
5      2022-06-01 1201       일일권         \\N  30대        7
6      2022-06-01 1201       일일권         \\N  40대        1
7      2022-06-01 1201       일일권         F    10대        1
8      2022-06-01 1201       일일권         F    20대        2
9      2022-06-01 1201       일일권         F    30대        1
10     2022-06-01 1201       일일권         F    40대        1
11     2022-06-01 1201       일일권         F    기타        1
12     2022-06-01 1201       일일권         M    20대        4
13     2022-06-01 1201       일일권         M    30대        5
14     2022-06-01 1201       일일권         M    40대        1
15     2022-06-01 1201       일일권         M    기타        1
16     2022-06-01 1201       정기권         \\N  20대       10
17     2022-06-01 1201       정기권         \\N  30대       10
18     2022-06-01 1201       정기권         \\N  40대        3
19     2022-06-01 1201       정기권         \\N  50대        3
20     2022-06-01 1201       정기권         \\N  60대        3
21     2022-06-01 1201       정기권         \\N  기타        1
22     2022-06-01 1201       정기권         F    20대        4
23     2022-06-01 1201       정기권         F    30대        7
24     2022-06-01 1201       정기권         F    40대        3
25     2022-06-01 1201       정기권         F    50대        2
26     2022-06-01 1201       정기권         F    기타        3
27     2022-06-01 1201       정기권         M    20대        6
28     2022-06-01 1201       정기권         M    30대       14
29     2022-06-01 1201       정기권         M    40대        9
30     2022-06-01 1201       정기권         M    50대        6
⋮      ⋮          ⋮          ⋮              ⋮    ⋮          ⋮
126216 2022-06-30 4882       정기권         M    20대       1
126217 2022-06-30 4883       정기권         \\N  50대       1
126218 2022-06-30 4884       정기권         \\N  30대       2
126219 2022-06-30 4884       정기권         \\N  40대       1
126220 2022-06-30 4884       정기권         F    30대       1
126221 2022-06-30 4884       정기권         M    30대       2
126222 2022-06-30 4886       정기권         \\N  20대       1
126223 2022-06-30 4886       정기권         F    30대       1
126224 2022-06-30 4886       정기권         M    40대       3
126225 2022-06-30 4888       정기권         M    10대       1
126226 2022-06-30 4889       정기권         M    10대       1
126227 2022-06-30 4889       정기권         M    50대       1
126228 2022-06-30 4891       정기권         M    50대       1
126229 2022-06-30 4892       정기권         F    50대       1
126230 2022-06-30 4892       정기권         M    10대       1
126231 2022-06-30 4895       정기권         M    30대       2
126232 2022-06-30 4895       정기권         M    40대       1
126233 2022-06-30 4895       정기권         M    50대       1
126234 2022-06-30 4896       정기권         M    기타       1
126235 2022-06-30 4897       정기권         \\N  20대       1
126236 2022-06-30 4897       정기권         \\N  40대       1
126237 2022-06-30 4897       정기권         M    20대       2
126238 2022-06-30 4897       정기권         M    40대       1
126239 2022-06-30 4897       정기권         M    기타       1
126240 2022-06-30 5752       정기권         \\N  20대       1
126241 2022-06-30 5752       정기권         \\N  30대       1
126242 2022-06-30 5752       정기권         M    30대       1
126243 2022-06-30 5753       정기권         NA   40대       1
126244 2022-06-30 5753       정기권         M    20대       1
126245 2022-06-30 5753       정기권         M    40대       2

In [ ]:
selected_DF06$`대여구분코드`<-ifelse(selected_DF06$`대여구분코드`=='정기권',1,0)

In [ ]:
selected_DF06$`성별`<-ifelse(selected_DF06$`성별`=='M',0,ifelse(selected_DF06$`성별`=='F',1,2))

In [ ]:
selected_DF06$`연령대코드`<-ifelse(selected_DF06$`연령대코드`=='10대',0,ifelse(selected_DF06$`연령대코드`=='20대',1,
ifelse(selected_DF06$`연령대코드`=='30대',2,ifelse(selected_DF06$`연령대코드`=='40대',3,ifelse(selected_DF06 $`연령대코드`=='50대',4,
ifelse(selected_DF06$`연령대코드`=='60대',5,ifelse(selected_DF06$`연령대코드`=='70대이상',6,7)))))))

In [ ]:
selected_DF06

       대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수
1      2022-06-01 1201       0            0    3           3
2      2022-06-01 1201       0            2    7           1
3      2022-06-01 1201       0            1    7           1
4      2022-06-01 1201       0            2    1           9
5      2022-06-01 1201       0            2    2           7
6      2022-06-01 1201       0            2    3           1
7      2022-06-01 1201       0            1    0           1
8      2022-06-01 1201       0            1    1           2
9      2022-06-01 1201       0            1    2           1
10     2022-06-01 1201       0            1    3           1
11     2022-06-01 1201       0            1    7           1
12     2022-06-01 1201       0            0    1           4
13     2022-06-01 1201       0            0    2           5
14     2022-06-01 1201       0            0    3           1
15     2022-06-01 1201       0            0    7           1
16     2022-06-01 1201       1            2    1          10
17     2022-06-01 1201       1            2    2          10
18     2022-06-01 1201       1            2    3           3
19     2022-06-01 1201       1            2    4           3
20     2022-06-01 1201       1            2    5           3
21     2022-06-01 1201       1            2    7           1
22     2022-06-01 1201       1            1    1           4
23     2022-06-01 1201       1            1    2           7
24     2022-06-01 1201       1            1    3           3
25     2022-06-01 1201       1            1    4           2
26     2022-06-01 1201       1            1    7           3
27     2022-06-01 1201       1            0    1           6
28     2022-06-01 1201       1            0    2          14
29     2022-06-01 1201       1            0    3           9
30     2022-06-01 1201       1            0    4           6
⋮      ⋮          ⋮          ⋮            ⋮    ⋮          ⋮
126216 2022-06-30 4882       1             0   1          1
126217 2022-06-30 4883       1             2   4          1
126218 2022-06-30 4884       1             2   2          2
126219 2022-06-30 4884       1             2   3          1
126220 2022-06-30 4884       1             1   2          1
126221 2022-06-30 4884       1             0   2          2
126222 2022-06-30 4886       1             2   1          1
126223 2022-06-30 4886       1             1   2          1
126224 2022-06-30 4886       1             0   3          3
126225 2022-06-30 4888       1             0   0          1
126226 2022-06-30 4889       1             0   0          1
126227 2022-06-30 4889       1             0   4          1
126228 2022-06-30 4891       1             0   4          1
126229 2022-06-30 4892       1             1   4          1
126230 2022-06-30 4892       1             0   0          1
126231 2022-06-30 4895       1             0   2          2
126232 2022-06-30 4895       1             0   3          1
126233 2022-06-30 4895       1             0   4          1
126234 2022-06-30 4896       1             0   7          1
126235 2022-06-30 4897       1             2   1          1
126236 2022-06-30 4897       1             2   3          1
126237 2022-06-30 4897       1             0   1          2
126238 2022-06-30 4897       1             0   3          1
126239 2022-06-30 4897       1             0   7          1
126240 2022-06-30 5752       1             2   1          1
126241 2022-06-30 5752       1             2   2          1
126242 2022-06-30 5752       1             0   2          1
126243 2022-06-30 5753       1            NA   3          1
126244 2022-06-30 5753       1             0   1          1
126245 2022-06-30 5753       1             0   3          2

In [ ]:
write.csv(selected_DF06,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.06.csv",row.names=FALSE, na="")

In [ ]:
selected_DF06$'평일/주말' <- ifelse(selected_DF06$대여일자 %in% date$date_time, date$weekend[match(selected_DF06$대여일자, date$date_time)], 2)
selected_DF06

       대여일자   대여소번호 대여구분코드 성별 연령대코드 이용건수 평일/주말
1      2022-06-01 1201       0            0    3           3       1
2      2022-06-01 1201       0            2    7           1       1
3      2022-06-01 1201       0            1    7           1       1
4      2022-06-01 1201       0            2    1           9       1
5      2022-06-01 1201       0            2    2           7       1
6      2022-06-01 1201       0            2    3           1       1
7      2022-06-01 1201       0            1    0           1       1
8      2022-06-01 1201       0            1    1           2       1
9      2022-06-01 1201       0            1    2           1       1
10     2022-06-01 1201       0            1    3           1       1
11     2022-06-01 1201       0            1    7           1       1
12     2022-06-01 1201       0            0    1           4       1
13     2022-06-01 1201       0            0    2           5       1
14     2022-06-01 1201       0            0    3           1       1
15     2022-06-01 1201       0            0    7           1       1
16     2022-06-01 1201       1            2    1          10       1
17     2022-06-01 1201       1            2    2          10       1
18     2022-06-01 1201       1            2    3           3       1
19     2022-06-01 1201       1            2    4           3       1
20     2022-06-01 1201       1            2    5           3       1
21     2022-06-01 1201       1            2    7           1       1
22     2022-06-01 1201       1            1    1           4       1
23     2022-06-01 1201       1            1    2           7       1
24     2022-06-01 1201       1            1    3           3       1
25     2022-06-01 1201       1            1    4           2       1
26     2022-06-01 1201       1            1    7           3       1
27     2022-06-01 1201       1            0    1           6       1
28     2022-06-01 1201       1            0    2          14       1
29     2022-06-01 1201       1            0    3           9       1
30     2022-06-01 1201       1            0    4           6       1
⋮      ⋮          ⋮          ⋮            ⋮    ⋮          ⋮        ⋮
126216 2022-06-30 4882       1             0   1          1        0
126217 2022-06-30 4883       1             2   4          1        0
126218 2022-06-30 4884       1             2   2          2        0
126219 2022-06-30 4884       1             2   3          1        0
126220 2022-06-30 4884       1             1   2          1        0
126221 2022-06-30 4884       1             0   2          2        0
126222 2022-06-30 4886       1             2   1          1        0
126223 2022-06-30 4886       1             1   2          1        0
126224 2022-06-30 4886       1             0   3          3        0
126225 2022-06-30 4888       1             0   0          1        0
126226 2022-06-30 4889       1             0   0          1        0
126227 2022-06-30 4889       1             0   4          1        0
126228 2022-06-30 4891       1             0   4          1        0
126229 2022-06-30 4892       1             1   4          1        0
126230 2022-06-30 4892       1             0   0          1        0
126231 2022-06-30 4895       1             0   2          2        0
126232 2022-06-30 4895       1             0   3          1        0
126233 2022-06-30 4895       1             0   4          1        0
126234 2022-06-30 4896       1             0   7          1        0
126235 2022-06-30 4897       1             2   1          1        0
126236 2022-06-30 4897       1             2   3          1        0
126237 2022-06-30 4897       1             0   1          2        0
126238 2022-06-30 4897       1             0   3          1        0
126239 2022-06-30 4897       1             0   7          1        0
126240 2022-06-30 5752       1             2   1          1        0
126241 2022-06-30 5752       1             2   2          1        0
126242 2022-06-30 5752       1             0   2          1        0
126243 2022-06-30 5753       1            NA   3          1        0
126244 2022-06-30 5753       1             0   1          1        0
126245 2022-06-30 5753       1             0   3          2        0

In [ ]:
selected_DF06 <- selected_DF06 %>% select('평일/주말', '대여구분코드', '성별', '연령대코드', '이용건수')
selected_DF06

       평일/주말 대여구분코드 성별 연령대코드 이용건수
1      1         0            0    3           3
2      1         0            2    7           1
3      1         0            1    7           1
4      1         0            2    1           9
5      1         0            2    2           7
6      1         0            2    3           1
7      1         0            1    0           1
8      1         0            1    1           2
9      1         0            1    2           1
10     1         0            1    3           1
11     1         0            1    7           1
12     1         0            0    1           4
13     1         0            0    2           5
14     1         0            0    3           1
15     1         0            0    7           1
16     1         1            2    1          10
17     1         1            2    2          10
18     1         1            2    3           3
19     1         1            2    4           3
20     1         1            2    5           3
21     1         1            2    7           1
22     1         1            1    1           4
23     1         1            1    2           7
24     1         1            1    3           3
25     1         1            1    4           2
26     1         1            1    7           3
27     1         1            0    1           6
28     1         1            0    2          14
29     1         1            0    3           9
30     1         1            0    4           6
⋮      ⋮         ⋮            ⋮    ⋮          ⋮
126216 0         1             0   1          1
126217 0         1             2   4          1
126218 0         1             2   2          2
126219 0         1             2   3          1
126220 0         1             1   2          1
126221 0         1             0   2          2
126222 0         1             2   1          1
126223 0         1             1   2          1
126224 0         1             0   3          3
126225 0         1             0   0          1
126226 0         1             0   0          1
126227 0         1             0   4          1
126228 0         1             0   4          1
126229 0         1             1   4          1
126230 0         1             0   0          1
126231 0         1             0   2          2
126232 0         1             0   3          1
126233 0         1             0   4          1
126234 0         1             0   7          1
126235 0         1             2   1          1
126236 0         1             2   3          1
126237 0         1             0   1          2
126238 0         1             0   3          1
126239 0         1             0   7          1
126240 0         1             2   1          1
126241 0         1             2   2          1
126242 0         1             0   2          1
126243 0         1            NA   3          1
126244 0         1             0   1          1
126245 0         1             0   3          2

In [ ]:
summarized_data_06 <- selected_DF06 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data_06

   대여일자   이용건수_합계
1  2022-06-01 15998
2  2022-06-02 15081
3  2022-06-03 15674
4  2022-06-04 14631
5  2022-06-05 11030
6  2022-06-06 13085
7  2022-06-07 15815
8  2022-06-08 15982
9  2022-06-09 14056
10 2022-06-10 14371
11 2022-06-11 14836
12 2022-06-12 13733
13 2022-06-13 14918
14 2022-06-14 13183
15 2022-06-15  5332
16 2022-06-16 13352
17 2022-06-17 16292
18 2022-06-18 14272
19 2022-06-19 13107
20 2022-06-20 15530
21 2022-06-21 15362
22 2022-06-22 15384
23 2022-06-23  5107
24 2022-06-24 13718
25 2022-06-25 13235
26 2022-06-26 11099
27 2022-06-27  8014
28 2022-06-28 11001
29 2022-06-29  4529
30 2022-06-30   785

## **7월 전처리**

In [ ]:
#https://drive.google.com/file/d/1qqaS9AfVJvDd4FH0fniZTMxujGKjEXC2/view?usp=sharing
system("gdown --id 1qqaS9AfVJvDd4FH0fniZTMxujGKjEXC2")
system("ls",TRUE)

 [1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [2] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [3] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [4] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [5] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [6] "서울특별시 공공자전거 이용정보(일별)_22.04.csv"
 [7] "서울특별시 공공자전거 이용정보(일별)_22.05.csv"
 [8] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.05.csv"
 [9] "서울특별시 공공자전거 이용정보(일별)_22.06.csv"
[10] "서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[11] "sample_data"

In [ ]:
DF07<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_22.07.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF07

Rows: 1877903 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): 대여소번호, 대여소, 대여구분코드, 성별, 연령대, 운동량, 탄소량
dbl  (3): 이용건수, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        대여일자   대여소번호 대여소
1       2022-07-01 00731      731. 서울시 도로환경관리센터
2       2022-07-01 00733      733. 신정이펜하우스314동
3       2022-07-01 00734      734. 신트리공원 입구
4       2022-07-01 00735      735. 영도초등학교
5       2022-07-01 00739      739. 신월사거리
6       2022-07-01 00742      742. 등촌역 5번 출구 뒤
7       2022-07-01 00745      745. 강서초등학교
8       2022-07-01 00746      746. 목동2단지 상가
9       2022-07-01 00505      505. 자양사거리 광진아크로텔 앞
10      2022-07-01 00942      942. 상림마을 생태공원
11      2022-07-01 00947      947. 연신내 선일하이츠빌 정류소
12      2022-07-01 00950      950. 구산역 2번 출구 예일여고 버스정류장
13      2022-07-01 01026      1026. 대명초교 입구 교차로
14      2022-07-01 01028      1028. 포레스 주상복합 빌딩
15      2022-07-01 01029      1029. 성내어울터
16      2022-07-01 01031      1031. 올림픽로 836(아리수로)
17      2022-07-01 01032      1032. 선사고등학교
18      2022-07-01 01036      1036. 고덕동 주양쇼핑
19      2022-07-01 01037      1037. 강일리버파크 6단지
20      2022-07-01 01044      1044. 굽은다리역
21      2022-07-01 01151      1151. 마곡역1번출구
22      2022-07-01 01152      1152. 마곡역교차로
23      2022-07-01 01153      1153. 발산역 1번, 9번 인근 대여소
24      2022-07-01 01251      1251. 석촌역 2번출구
25      2022-07-01 01271      1271. 송파도서관
26      2022-07-01 01442      1442. 중랑구 중소기업 창업센터
27      2022-07-01 01447      1447. 면목역 3번출구
28      2022-07-01 01527      1527. 미아역 1번 출구 뒤
29      2022-07-01 01643      1643. 태릉입구역 8번출구
30      2022-07-01 01650      1650. 중계근린공원내
⋮       ⋮          ⋮          ⋮
1877874 2022-07-31 00207      207. 여의나루역 1번출구 앞
1877875 2022-07-31 01214      1214. 오금역 7번 출구 인근
1877876 2022-07-31 02206      2206. 언남초등학교 앞
1877877 2022-07-31 02221      2221. 방일초교 마을버스 정류장
1877878 2022-07-31 02244      2244.교육개발원입구 교차로
1877879 2022-07-31 02262      2262. 한신16차아파트 119동 앞
1877880 2022-07-31 00403      403. 부엉이공원 앞
1877881 2022-07-31 02327      2327. 뱅뱅사거리 랜드마크타워 앞
1877882 2022-07-31 02332      2332. 선릉역3번출구
1877883 2022-07-31 01018      1018. 둔촌 주공 GS 맞은편
1877884 2022-07-31 01103      1103. 방화역 4번출구앞
1877885 2022-07-31 01414      1414. 사가정역 2번출구
1877886 2022-07-31 01416      1416. 상봉역 3번출구
1877887 2022-07-31 01428      1428. 원묵고등학교
1877888 2022-07-31 02263      2263. 바우뫼문화복지회관
1877889 2022-07-31 02119      2119. 중앙동 동진빌딩
1877890 2022-07-31 00107      107. 신한은행 서교동지점
1877891 2022-07-31 01249      1249. 아주중학교건너편
1877892 2022-07-31 01914      1914. 대림역4번출구
1877893 2022-07-31 02026      2026. 흑석역 4번출구
1877894 2022-07-31 01955      1955. 디지털입구 교차로
1877895 2022-07-31 01440      1440. 면목2동 사거리
1877896 2022-07-31 01305      1305. 성북구청
1877897 2022-07-31 02356      2356. 강남구청
1877898 2022-07-31 01642      1642. 서울여대 남문
1877899 2022-07-31 00500      500. 어린이대공원역 3번출구 앞
1877900 2022-07-31 01640      1640. 한내근린공원 북측
1877901 2022-07-31 01149      1149. 신방화역환승주차장
1877902 2022-07-31 03500      3500. 군자역2번출구
1877903 2022-07-31 00722      722. 경서농협 버스정류장(우리은행신정동지점방향)
        대여구분코드 성별 연령대 이용건수 운동량 탄소량 이동거리(M)
1       정기권       NA   ~10대  2        53.63  0.50    2150.00
2       정기권       NA   ~10대  1        25.06  0.23    1004.30
3       정기권       NA   ~10대  2        368.82 3.02   13032.28
4       정기권       NA   ~10대  2        57.64  0.50    2173.08
5       정기권       NA   ~10대  3        73.58  0.69    2940.00
6       정기권       NA   ~10대  1        73.10  0.66    2840.00
7       정기권       NA   ~10대  1        32.87  0.39    1660.00
8       정기권       NA   ~10대  4        294.40 2.54   10966.89
9       정기권       NA   ~10대  2        100.57 1.02    4397.36
10      정기권       NA   ~10대  1        12.27  0.13     563.46
11      정기권       NA   ~10대  1        26.36  0.26    1109.32
12      정기권       NA   ~10대  1        62.87  0.58    2520.00
13      정기권       NA   ~10대  2        199.66 1.82    7878.05
14      정기권       NA   ~10대  1        16.13  0.19     814.43
15      정기권       NA   ~10대  1        52.05  0.49    2120.00
16      정기권       NA   ~10대  1        13.64  0.12     530.00
17      정기권       NA   ~10대  1        44.16  0.38    1640.00
18      정기권       NA   ~10대  1        107.85 0.32    1361.80
19      정기권       NA   ~10대  1        35.78  0.32    1390.00
20      정기권       NA   ~10대  1        24.18  0.22     953.94
21      정기권       NA   ~10대  1        5.56   0.06     260.00
22      정기권       NA   ~10대  3        127.22 1.10    4754.22
23      정기권       NA   ~10대  9        665.62 5.95   25647.92
24      정기권       NA   ~10대  1        28.06  0.22     944.92
25      정기권       NA   ~10대  1        46.34  0.42    1800.50
26      정기권       NA   ~10대  1        11.02  0.13     580.00
27      정기권       NA   ~10대  1        30.55  0.42    1794.19
28      정기권       NA   ~10대  1        0.00   0.00       0.00
29      정기권       NA   ~10대  2        38.70  0.28    1212.27
30      정기권       NA   ~10대  5        134.72 1.36    5898.03
⋮       ⋮            ⋮    ⋮      ⋮        ⋮      ⋮      ⋮
1877874 정기권       M    기타   1        75.40  0.63    2720.00
1877875 정기권       M    기타   1        129.79 1.01    4370.00
1877876 정기권       M    기타   1        106.33 0.83    3580.00
1877877 정기권       M    기타   1        123.31 1.20    5190.00
1877878 정기권       M    기타   1        111.25 1.02    4389.48
1877879 정기권       M    기타   1        128.30 1.25    5400.00
1877880 정기권       M    기타   1        121.44 1.02    4380.79
1877881 정기권       M    기타   1        754.31 4.65   20050.76
1877882 정기권       M    기타   1        162.06 1.20    5180.26
1877883 정기권       M    기타   1        16.63  0.14     617.42
1877884 정기권       M    기타   2        148.01 1.41    6038.19
1877885 정기권       M    기타   1        115.88 1.04    4501.86
1877886 정기권       M    기타   2        85.72  0.78    3330.00
1877887 정기권       M    기타   1        52.05  0.49    2120.00
1877888 정기권       M    기타   1        27.32  0.27    1150.00
1877889 정기권       M    기타   1        47.88  0.43    1860.00
1877890 정기권       M    기타   1        79.58  0.65    2791.15
1877891 정기권       M    기타   1        36.81  0.33    1430.00
1877892 정기권       M    기타   1        33.09  0.23     971.58
1877893 정기권       M    기타   1        0.00   0.00       0.00
1877894 정기권       M    기타   1        18.75  0.11     473.42
1877895 정기권       M    기타   1        262.94 1.93    8300.00
1877896 정기권       M    기타   1        182.95 1.43    6160.00
1877897 정기권       M    기타   1        223.05 1.65    7130.00
1877898 정기권       M    기타   1        29.63  0.30    1312.48
1877899 정기권       M    기타   1        39.36  0.33    1420.00
1877900 정기권       M    기타   1        346.72 3.13   13470.00
1877901 정기권       M    기타   1        40.87  0.40    1720.00
1877902 정기권       M    기타   2        110.67 1.04    4449.62
1877903 정기권       M    기타   1        24.12  0.21     909.15
        이용시간(분)
1        20
2         5
3        75
4        21
5        15
6        16
7        15
8        71
9        30
10        3
11        4
12       23
13       54
14        5
15       11
16        8
17       15
18        7
19        8
20       21
21        1
22       52
23      292
24       13
25       16
26        5
27       19
28        1
29        9
30       91
⋮       ⋮
1877874  49
1877875  25
1877876  22
1877877  37
1877878  24
1877879  50
1877880  24
1877881 107
1877882  69
1877883   4
1877884  41
1877885  89
1877886  14
1877887  86
1877888   5
1877889  12
1877890 133
1877891   9
1877892   5
1877893   2
1877894   4
1877895 175
1877896  25
1877897  80
1877898   8
1877899   5
1877900  93
1877901  11
1877902 147
1877903   7

In [ ]:
DF07$대여소번호 <- as.numeric(DF07$대여소번호)

In [ ]:
f_DF07<-DF07%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897,5751,5752,5753,5760,5756,5758,5759,5761,5763,5764,5765,5766,5767))
f_DF07

       대여일자   대여소번호 대여소                               대여구분코드
1      2022-07-01 1251       1251. 석촌역 2번출구                 정기권
2      2022-07-01 1271       1271. 송파도서관                     정기권
3      2022-07-01 1282       1282. 송파소방서 맞은편(성내4교)     정기권
4      2022-07-01 1293       1293. 석촌호수 서호 사거리           정기권
5      2022-07-01 2621       2621. 한성백제역 2번 출구            정기권
6      2022-07-01 2620       2620. 송파나루역 4번 출구옆          정기권
7      2022-07-01 2630       2630.서울방이동 고분군               정기권
8      2022-07-01 2647       2647.잠실 자전거 수리센터 앞         정기권
9      2022-07-01 2648       2648.헬리오시티 112동 앞             정기권
10     2022-07-01 2655       2655.송이공원                        정기권
11     2022-07-01 4461       4461. 한양3차아파트 3동 앞           정기권
12     2022-07-01 4465       4465. 건영아파트앞 사거리            정기권
13     2022-07-01 4467       4467. 한림연예예술고등학교           정기권
14     2022-07-01 4478       4478. 문정근린공원2                  정기권
15     2022-07-01 4491       4491. 장지역 1번출구                 정기권
16     2022-07-01 4493       4493. 마천사거리 2                   정기권
17     2022-07-01 4852       4852. 서울복합물류 게이트 1          정기권
18     2022-07-01 4872       4872. 개롱역 3번 출구 뒤             정기권
19     2022-07-01 1209       1209. 잠실나루역 (2번 출구 쪽)       정기권
20     2022-07-01 1215       1215. 올림픽공원역 1번출구 앞        정기권
21     2022-07-01 1232       1232. 잠실주공 521동 건너편          정기권
22     2022-07-01 1233       1233. 잠실3거리(갤러리아팰리스)      정기권
23     2022-07-01 1207       1207. 마천중앙시장                   정기권
24     2022-07-01 1218       1218. 방이역 4번출구                 정기권
25     2022-07-01 1230       1230. 송파중학교 정문                정기권
26     2022-07-01 1251       1251. 석촌역 2번출구                 정기권
27     2022-07-01 1251       1251. 석촌역 2번출구                 정기권
28     2022-07-01 1253       1253. 오금역 3번 출구 뒤             정기권
29     2022-07-01 1256       1256. 문정현대아파트 교차로          정기권
30     2022-07-01 1257       1257. 가락시장역 사거리              정기권
⋮      ⋮          ⋮          ⋮                                    ⋮
157562 2022-07-31 1247       1247. 문정 법조단지11                정기권
157563 2022-07-31 2615       2615. 테라타워2                      정기권
157564 2022-07-31 2634       2634.위례포레샤인아파트 2318동       정기권
157565 2022-07-31 2656       2656.풍납동 아이파크 107동 앞        정기권
157566 2022-07-31 4859       4859. 잠실나루 나들목                정기권
157567 2022-07-31 1208       1208. 풍납현대아파트쉼터             정기권
157568 2022-07-31 1264       1264. 천호역 10번 출구 앞            정기권
157569 2022-07-31 1269       1269. 리센츠아파트                   정기권
157570 2022-07-31 1297       1297. 석촌호수교차로(동호 팔각정 앞) 정기권
157571 2022-07-31 1299       1299. 송파소방서 (방이119안전센터)   정기권
157572 2022-07-31 2616       2616. 거여동 사거리                  정기권
157573 2022-07-31 2622       2622. 올림픽공원역 3번출구           정기권
157574 2022-07-31 2642       2642.마천동 성내천 쉼터              정기권
157575 2022-07-31 2630       2630.서울방이동 고분군               정기권
157576 2022-07-31 2646       2646.레이크펠리스101동앞             정기권
157577 2022-07-31 2651       2651.경찰병원역 3번출구 앞           정기권
157578 2022-07-31 2653       2653.올림픽공원사거리(선수촌아파트)  정기권
157579 2022-07-31 2657       2657.송파 파인타운 11단지            정기권
157580 2022-07-31 4452       4452. 삼성SDS                        정기권
157581 2022-07-31 4467       4467. 한림연예예술고등학교           정기권
157582 2022-07-31 4478       4478. 문정근린공원2                  정기권
157583 2022-07-31 4481       4481. 올림픽공원 북2문 2             정기권
157584 2022-07-31 4496       4496. 잠실 파크리오 120동 앞         정기권
157585 2022-07-31 4864       4864. 송파사거리                     정기권
157586 2022-07-31 4865       4865. 한성백제역 1번출구 뒤          정기권
157587 2022-07-31 4873       4873. 개롱역사거리 2번 출구          정기권
157588 2022-07-31 5752       5752. 풍납백제문화공원 옆 인근       정기권
157589 2022-07-31 1208       1208. 풍납현대아파트쉼터             정기권
157590 2022-07-31 1214       1214. 오금역 7번 출구 인근           정기권
157591 2022-07-31 1249       1249. 아주중학교건너편               정기권
       성별 연령대   이용건수 운동량 탄소량 이동거리(M) 이용시간(분)
1      NA   ~10대     1       28.06  0.22     944.92     13
2      NA   ~10대     1       46.34  0.42    1800.50     16
3      NA   ~10대     1       73.24  0.55    2371.23     14
4      NA   ~10대     1       23.47  0.24    1022.04      7
5      NA   ~10대     1       81.12  0.61    2626.31     54
6      NA   ~10대     3       148.89 1.38    5967.48     47
7      NA   ~10대     2       119.89 1.07    4640.59     27
8      NA   ~10대     1       83.54  0.67    2890.00     22
9      NA   ~10대     2       59.26  0.61    2642.88     15
10     NA   ~10대     2       81.11  0.78    3327.48     68
11     NA   ~10대     1       17.43  0.16     709.77      5
12     NA   ~10대     1       18.60  0.20     870.00      5
13     NA   ~10대     1       25.72  0.23     999.03     10
14     NA   ~10대     1       42.99  0.39    1670.00     17
15     NA   ~10대     1       14.22  0.19     834.95      8
16     NA   ~10대     1       21.62  0.19     840.00      8
17     NA   ~10대     1       100.08 0.75    3240.00     16
18     NA   ~10대     1       9.61   0.10     425.92      2
19     NA   ~10대     1       92.74  0.77    3298.44     64
20     NA   ~10대     2       78.91  0.85    3689.86     21
21     NA   ~10대     1       152.09 1.68    7246.32     51
22     NA   ~10대     1       17.19  0.21     904.36      6
23     NA   ~10대     1       38.61  0.35    1500.00     12
24     NA   ~10대     1       60.73  0.58    2513.99     55
25     NA   ~10대     1       33.04  0.24    1030.00      4
26     NA   20대     20       953.96 8.90   38307.29    270
27     NA   20대      1       10.57  0.11     460.00      3
28     NA   20대      9       335.16 3.20   13802.71    138
29     NA   20대      7       315.67 3.60   15542.35    107
30     NA   20대      3       219.16 1.97    8486.07     61
⋮      ⋮    ⋮        ⋮        ⋮      ⋮      ⋮           ⋮
157562 M    60대     1        43.65  0.35    1510.00     10
157563 M    70대이상 1        63.32  0.57    2460.00     86
157564 M    70대이상 1        103.69 0.93    4028.25     49
157565 M    70대이상 1        36.88  0.31    1349.60     14
157566 M    70대이상 1        490.03 4.78   20624.17    102
157567 M    70대이상 1        331.90 2.59   11175.17    111
157568 M    기타     1        98.33  0.89    3820.00     21
157569 M    기타     1        96.83  1.00    4290.00     20
157570 M    기타     1        22.91  0.21     890.00      5
157571 M    기타     2        426.75 3.34   14415.93    103
157572 M    기타     1        19.25  0.20     852.91      6
157573 M    기타     1        222.24 1.69    7288.42     68
157574 M    기타     3        574.83 4.07   17560.24    110
157575 M    기타     1        107.40 0.97    4172.52     24
157576 M    기타     1        26.77  0.24    1040.00      8
157577 M    기타     1        88.03  0.79    3420.00     28
157578 M    기타     1        92.31  0.60    2590.00     12
157579 M    기타     1        236.17 1.98    8520.00     35
157580 M    기타     1        24.17  0.19     813.83      4
157581 M    기타     1        250.71 2.26    9740.00     57
157582 M    기타     1        44.24  0.34    1470.00     33
157583 M    기타     3        169.50 1.40    6065.36     46
157584 M    기타     1        28.09  0.27    1144.05      9
157585 M    기타     2        77.54  0.69    2955.93     23
157586 M    기타     2        122.90 1.16    4980.94     26
157587 M    기타     1        339.57 2.84   12250.00     82
157588 M    기타     1        218.90 1.47    6353.63     49
157589 M    기타     2        170.08 1.43    6135.85     45
157590 M    기타     1        129.79 1.01    4370.00     25
157591 M    기타     1        36.81  0.33    1430.00      9

In [ ]:
selected_DF07 <- f_DF07 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대, 이용건수)
selected_DF07

       대여일자   대여소번호 대여구분코드 성별 연령대   이용건수
1      2022-07-01 1251       정기권       NA   ~10대     1
2      2022-07-01 1271       정기권       NA   ~10대     1
3      2022-07-01 1282       정기권       NA   ~10대     1
4      2022-07-01 1293       정기권       NA   ~10대     1
5      2022-07-01 2621       정기권       NA   ~10대     1
6      2022-07-01 2620       정기권       NA   ~10대     3
7      2022-07-01 2630       정기권       NA   ~10대     2
8      2022-07-01 2647       정기권       NA   ~10대     1
9      2022-07-01 2648       정기권       NA   ~10대     2
10     2022-07-01 2655       정기권       NA   ~10대     2
11     2022-07-01 4461       정기권       NA   ~10대     1
12     2022-07-01 4465       정기권       NA   ~10대     1
13     2022-07-01 4467       정기권       NA   ~10대     1
14     2022-07-01 4478       정기권       NA   ~10대     1
15     2022-07-01 4491       정기권       NA   ~10대     1
16     2022-07-01 4493       정기권       NA   ~10대     1
17     2022-07-01 4852       정기권       NA   ~10대     1
18     2022-07-01 4872       정기권       NA   ~10대     1
19     2022-07-01 1209       정기권       NA   ~10대     1
20     2022-07-01 1215       정기권       NA   ~10대     2
21     2022-07-01 1232       정기권       NA   ~10대     1
22     2022-07-01 1233       정기권       NA   ~10대     1
23     2022-07-01 1207       정기권       NA   ~10대     1
24     2022-07-01 1218       정기권       NA   ~10대     1
25     2022-07-01 1230       정기권       NA   ~10대     1
26     2022-07-01 1251       정기권       NA   20대     20
27     2022-07-01 1251       정기권       NA   20대      1
28     2022-07-01 1253       정기권       NA   20대      9
29     2022-07-01 1256       정기권       NA   20대      7
30     2022-07-01 1257       정기권       NA   20대      3
⋮      ⋮          ⋮          ⋮            ⋮    ⋮        ⋮
157562 2022-07-31 1247       정기권       M    60대     1
157563 2022-07-31 2615       정기권       M    70대이상 1
157564 2022-07-31 2634       정기권       M    70대이상 1
157565 2022-07-31 2656       정기권       M    70대이상 1
157566 2022-07-31 4859       정기권       M    70대이상 1
157567 2022-07-31 1208       정기권       M    70대이상 1
157568 2022-07-31 1264       정기권       M    기타     1
157569 2022-07-31 1269       정기권       M    기타     1
157570 2022-07-31 1297       정기권       M    기타     1
157571 2022-07-31 1299       정기권       M    기타     2
157572 2022-07-31 2616       정기권       M    기타     1
157573 2022-07-31 2622       정기권       M    기타     1
157574 2022-07-31 2642       정기권       M    기타     3
157575 2022-07-31 2630       정기권       M    기타     1
157576 2022-07-31 2646       정기권       M    기타     1
157577 2022-07-31 2651       정기권       M    기타     1
157578 2022-07-31 2653       정기권       M    기타     1
157579 2022-07-31 2657       정기권       M    기타     1
157580 2022-07-31 4452       정기권       M    기타     1
157581 2022-07-31 4467       정기권       M    기타     1
157582 2022-07-31 4478       정기권       M    기타     1
157583 2022-07-31 4481       정기권       M    기타     3
157584 2022-07-31 4496       정기권       M    기타     1
157585 2022-07-31 4864       정기권       M    기타     2
157586 2022-07-31 4865       정기권       M    기타     2
157587 2022-07-31 4873       정기권       M    기타     1
157588 2022-07-31 5752       정기권       M    기타     1
157589 2022-07-31 1208       정기권       M    기타     2
157590 2022-07-31 1214       정기권       M    기타     1
157591 2022-07-31 1249       정기권       M    기타     1

In [ ]:
selected_DF07$`대여구분코드`<-ifelse(selected_DF07$`대여구분코드`=='정기권',1,0)

In [ ]:
selected_DF07$`성별`<-ifelse(selected_DF07$`성별`=='M',0,ifelse(selected_DF01$`성별`=='F',1,2))

In [ ]:
selected_DF07$`연령대`<-ifelse(selected_DF07$`연령대`=='~10대',0,ifelse(selected_DF07$`연령대`=='20대',1,
ifelse(selected_DF07$`연령대`=='30대',2,ifelse(selected_DF07$`연령대`=='40대',3,ifelse(selected_DF07$`연령대`=='50대',4,
ifelse(selected_DF07$`연령대`=='60대',5,ifelse(selected_DF07$`연령대`=='70대이상',6,7)))))))

In [ ]:
selected_DF07

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수
1      2022-07-01 1251       1            NA   0       1
2      2022-07-01 1271       1            NA   0       1
3      2022-07-01 1282       1            NA   0       1
4      2022-07-01 1293       1            NA   0       1
5      2022-07-01 2621       1            NA   0       1
6      2022-07-01 2620       1            NA   0       3
7      2022-07-01 2630       1            NA   0       2
8      2022-07-01 2647       1            NA   0       1
9      2022-07-01 2648       1            NA   0       2
10     2022-07-01 2655       1            NA   0       2
11     2022-07-01 4461       1            NA   0       1
12     2022-07-01 4465       1            NA   0       1
13     2022-07-01 4467       1            NA   0       1
14     2022-07-01 4478       1            NA   0       1
15     2022-07-01 4491       1            NA   0       1
16     2022-07-01 4493       1            NA   0       1
17     2022-07-01 4852       1            NA   0       1
18     2022-07-01 4872       1            NA   0       1
19     2022-07-01 1209       1            NA   0       1
20     2022-07-01 1215       1            NA   0       2
21     2022-07-01 1232       1            NA   0       1
22     2022-07-01 1233       1            NA   0       1
23     2022-07-01 1207       1            NA   0       1
24     2022-07-01 1218       1            NA   0       1
25     2022-07-01 1230       1            NA   0       1
26     2022-07-01 1251       1            NA   1      20
27     2022-07-01 1251       1            NA   1       1
28     2022-07-01 1253       1            NA   1       9
29     2022-07-01 1256       1            NA   1       7
30     2022-07-01 1257       1            NA   1       3
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮
157562 2022-07-31 1247       1            0    5      1
157563 2022-07-31 2615       1            0    6      1
157564 2022-07-31 2634       1            0    6      1
157565 2022-07-31 2656       1            0    6      1
157566 2022-07-31 4859       1            0    6      1
157567 2022-07-31 1208       1            0    6      1
157568 2022-07-31 1264       1            0    7      1
157569 2022-07-31 1269       1            0    7      1
157570 2022-07-31 1297       1            0    7      1
157571 2022-07-31 1299       1            0    7      2
157572 2022-07-31 2616       1            0    7      1
157573 2022-07-31 2622       1            0    7      1
157574 2022-07-31 2642       1            0    7      3
157575 2022-07-31 2630       1            0    7      1
157576 2022-07-31 2646       1            0    7      1
157577 2022-07-31 2651       1            0    7      1
157578 2022-07-31 2653       1            0    7      1
157579 2022-07-31 2657       1            0    7      1
157580 2022-07-31 4452       1            0    7      1
157581 2022-07-31 4467       1            0    7      1
157582 2022-07-31 4478       1            0    7      1
157583 2022-07-31 4481       1            0    7      3
157584 2022-07-31 4496       1            0    7      1
157585 2022-07-31 4864       1            0    7      2
157586 2022-07-31 4865       1            0    7      2
157587 2022-07-31 4873       1            0    7      1
157588 2022-07-31 5752       1            0    7      1
157589 2022-07-31 1208       1            0    7      2
157590 2022-07-31 1214       1            0    7      1
157591 2022-07-31 1249       1            0    7      1

In [ ]:
write.csv(selected_DF07,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.07.csv",row.names=FALSE, na="")

In [ ]:
selected_DF07$'평일/주말' <- ifelse(selected_DF07$대여일자 %in% date$date_time, date$weekend[match(selected_DF07$대여일자, date$date_time)], 2)
selected_DF07

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수 평일/주말
1      2022-07-01 1251       1            NA   0       1       0
2      2022-07-01 1271       1            NA   0       1       0
3      2022-07-01 1282       1            NA   0       1       0
4      2022-07-01 1293       1            NA   0       1       0
5      2022-07-01 2621       1            NA   0       1       0
6      2022-07-01 2620       1            NA   0       3       0
7      2022-07-01 2630       1            NA   0       2       0
8      2022-07-01 2647       1            NA   0       1       0
9      2022-07-01 2648       1            NA   0       2       0
10     2022-07-01 2655       1            NA   0       2       0
11     2022-07-01 4461       1            NA   0       1       0
12     2022-07-01 4465       1            NA   0       1       0
13     2022-07-01 4467       1            NA   0       1       0
14     2022-07-01 4478       1            NA   0       1       0
15     2022-07-01 4491       1            NA   0       1       0
16     2022-07-01 4493       1            NA   0       1       0
17     2022-07-01 4852       1            NA   0       1       0
18     2022-07-01 4872       1            NA   0       1       0
19     2022-07-01 1209       1            NA   0       1       0
20     2022-07-01 1215       1            NA   0       2       0
21     2022-07-01 1232       1            NA   0       1       0
22     2022-07-01 1233       1            NA   0       1       0
23     2022-07-01 1207       1            NA   0       1       0
24     2022-07-01 1218       1            NA   0       1       0
25     2022-07-01 1230       1            NA   0       1       0
26     2022-07-01 1251       1            NA   1      20       0
27     2022-07-01 1251       1            NA   1       1       0
28     2022-07-01 1253       1            NA   1       9       0
29     2022-07-01 1256       1            NA   1       7       0
30     2022-07-01 1257       1            NA   1       3       0
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮        ⋮
157562 2022-07-31 1247       1            0    5      1        1
157563 2022-07-31 2615       1            0    6      1        1
157564 2022-07-31 2634       1            0    6      1        1
157565 2022-07-31 2656       1            0    6      1        1
157566 2022-07-31 4859       1            0    6      1        1
157567 2022-07-31 1208       1            0    6      1        1
157568 2022-07-31 1264       1            0    7      1        1
157569 2022-07-31 1269       1            0    7      1        1
157570 2022-07-31 1297       1            0    7      1        1
157571 2022-07-31 1299       1            0    7      2        1
157572 2022-07-31 2616       1            0    7      1        1
157573 2022-07-31 2622       1            0    7      1        1
157574 2022-07-31 2642       1            0    7      3        1
157575 2022-07-31 2630       1            0    7      1        1
157576 2022-07-31 2646       1            0    7      1        1
157577 2022-07-31 2651       1            0    7      1        1
157578 2022-07-31 2653       1            0    7      1        1
157579 2022-07-31 2657       1            0    7      1        1
157580 2022-07-31 4452       1            0    7      1        1
157581 2022-07-31 4467       1            0    7      1        1
157582 2022-07-31 4478       1            0    7      1        1
157583 2022-07-31 4481       1            0    7      3        1
157584 2022-07-31 4496       1            0    7      1        1
157585 2022-07-31 4864       1            0    7      2        1
157586 2022-07-31 4865       1            0    7      2        1
157587 2022-07-31 4873       1            0    7      1        1
157588 2022-07-31 5752       1            0    7      1        1
157589 2022-07-31 1208       1            0    7      2        1
157590 2022-07-31 1214       1            0    7      1        1
157591 2022-07-31 1249       1            0    7      1        1

In [ ]:
selected_DF07 <- selected_DF07 %>% select('평일/주말', '대여구분코드', '성별', '연령대', '이용건수')
selected_DF07

       평일/주말 대여구분코드 성별 연령대 이용건수
1      0         1            NA   0       1
2      0         1            NA   0       1
3      0         1            NA   0       1
4      0         1            NA   0       1
5      0         1            NA   0       1
6      0         1            NA   0       3
7      0         1            NA   0       2
8      0         1            NA   0       1
9      0         1            NA   0       2
10     0         1            NA   0       2
11     0         1            NA   0       1
12     0         1            NA   0       1
13     0         1            NA   0       1
14     0         1            NA   0       1
15     0         1            NA   0       1
16     0         1            NA   0       1
17     0         1            NA   0       1
18     0         1            NA   0       1
19     0         1            NA   0       1
20     0         1            NA   0       2
21     0         1            NA   0       1
22     0         1            NA   0       1
23     0         1            NA   0       1
24     0         1            NA   0       1
25     0         1            NA   0       1
26     0         1            NA   1      20
27     0         1            NA   1       1
28     0         1            NA   1       9
29     0         1            NA   1       7
30     0         1            NA   1       3
⋮      ⋮         ⋮            ⋮    ⋮      ⋮
157562 1         1            0    5      1
157563 1         1            0    6      1
157564 1         1            0    6      1
157565 1         1            0    6      1
157566 1         1            0    6      1
157567 1         1            0    6      1
157568 1         1            0    7      1
157569 1         1            0    7      1
157570 1         1            0    7      1
157571 1         1            0    7      2
157572 1         1            0    7      1
157573 1         1            0    7      1
157574 1         1            0    7      3
157575 1         1            0    7      1
157576 1         1            0    7      1
157577 1         1            0    7      1
157578 1         1            0    7      1
157579 1         1            0    7      1
157580 1         1            0    7      1
157581 1         1            0    7      1
157582 1         1            0    7      1
157583 1         1            0    7      3
157584 1         1            0    7      1
157585 1         1            0    7      2
157586 1         1            0    7      2
157587 1         1            0    7      1
157588 1         1            0    7      1
157589 1         1            0    7      2
157590 1         1            0    7      1
157591 1         1            0    7      1

In [ ]:
summarized_data_07 <- selected_DF07 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data_07

   대여일자   이용건수_합계
1  2022-07-01 13849
2  2022-07-02 11868
3  2022-07-03  9920
4  2022-07-04 12717
5  2022-07-05 11972
6  2022-07-06 12426
7  2022-07-07 10477
8  2022-07-08 13563
9  2022-07-09 12213
10 2022-07-10  9253
11 2022-07-11 11765
12 2022-07-12 14389
13 2022-07-13  1758
14 2022-07-14 13404
15 2022-07-15 15178
16 2022-07-16  7983
17 2022-07-17 11633
18 2022-07-18 14314
19 2022-07-19 14150
20 2022-07-20 12628
21 2022-07-21  8510
22 2022-07-22 12452
23 2022-07-23  7400
24 2022-07-24  9724
25 2022-07-25 12596
26 2022-07-26 13759
27 2022-07-27 13648
28 2022-07-28 13198
29 2022-07-29 12648
30 2022-07-30  9234
31 2022-07-31  2522

## **8월 전처리**

In [ ]:
#https://drive.google.com/file/d/13wqd65Ldzco32g5tSYWjQRRslhAwZtkH/view?usp=sharing
system("gdown --id 13wqd65Ldzco32g5tSYWjQRRslhAwZtkH")
system("ls",TRUE)

 [1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [2] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [3] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [4] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [5] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [6] "서울특별시 공공자전거 이용정보(일별)_22.04.csv"
 [7] "서울특별시 공공자전거 이용정보(일별)_22.05.csv"
 [8] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.05.csv"
 [9] "서울특별시 공공자전거 이용정보(일별)_22.06.csv"
[10] "서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[11] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[12] "서울특별시 공공자전거 이용정보(일별)_22.08.csv"
[13] "sample_data"

In [ ]:
DF08<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_22.08.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF08

Rows: 1717135 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): 대여소번호, 대여소, 대여구분코드, 성별, 연령대, 운동량, 탄소량
dbl  (3): 이용건수, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        대여일자   대여소번호 대여소
1       2022-08-01 00731      731. 서울시 도로환경관리센터
2       2022-08-01 00734      734. 신트리공원 입구
3       2022-08-01 00735      735. 영도초등학교
4       2022-08-01 00740      740. 으뜸공원
5       2022-08-01 00746      746. 목동2단지 상가
6       2022-08-01 00746      746. 목동2단지 상가
7       2022-08-01 00748      748. 목동운동장
8       2022-08-01 00949      949. 연신내역 1번 출구
9       2022-08-01 00950      950. 구산역 2번 출구 예일여고 버스정류장
10      2022-08-01 00953      953. 서울연신초등학교
11      2022-08-01 01023      1023. 한국종합기술사옥 앞
12      2022-08-01 01041      1041. 묘곡초등학교
13      2022-08-01 01044      1044. 굽은다리역
14      2022-08-01 01150      1150. 송정역 1번출구
15      2022-08-01 01151      1151. 마곡역1번출구
16      2022-08-01 01153      1153. 발산역 1번, 9번 인근 대여소
17      2022-08-01 01155      1155. 기쁜우리복지관
18      2022-08-01 01260      1260. 방이동 한양3차아파트 옆
19      2022-08-01 01263      1263. 장지공영차고지
20      2022-08-01 01442      1442. 중랑구 중소기업 창업센터
21      2022-08-01 01447      1447. 면목역 3번출구
22      2022-08-01 01447      1447. 면목역 3번출구
23      2022-08-01 01650      1650. 중계근린공원내
24      2022-08-01 01653      1653. 노원역1번출구
25      2022-08-01 01654      1654. 당고개입구 오거리
26      2022-08-01 01655      1655. 공릉1단지아파트
27      2022-08-01 01656      1656. 중앙하이츠 아파트 입구
28      2022-08-01 01659      1659. 중계동 을지중학교
29      2022-08-01 01713      1713. 쌍문동 이안아파트 앞
30      2022-08-01 01714      1714. 도봉문화정보도서관 삼거리
⋮       ⋮          ⋮          ⋮
1717106 2022-08-31 02211      2211. 서초구립반포도서관 앞
1717107 2022-08-31 02248      2248. 서초리슈빌S 글로벌 앞
1717108 2022-08-31 00417      417. DMC역 2번출구 옆
1717109 2022-08-31 01303      1303. 돈암초교 입구
1717110 2022-08-31 02264      2264. 이수역 1번출구
1717111 2022-08-31 01955      1955. 디지털입구 교차로
1717112 2022-08-31 01955      1955. 디지털입구 교차로
1717113 2022-08-31 00446      446. 상명대입구
1717114 2022-08-31 00414      414. 상암동주민센터 옆
1717115 2022-08-31 00449      449. 일성아파트
1717116 2022-08-31 01305      1305. 성북구청
1717117 2022-08-31 01501      1501. 미아역 3번,4번 출구 사이
1717118 2022-08-31 00415      415. DMC역 9번출구 앞
1717119 2022-08-31 02347      2347. 두산건설 본사
1717120 2022-08-31 02352      2352. 서울본부세관(건설회관 앞)
1717121 2022-08-31 02353      2353. 강남구청역 2번출구 뒤
1717122 2022-08-31 01642      1642. 서울여대 남문
1717123 2022-08-31 02111      2111. 서울대입구역 1번출구
1717124 2022-08-31 00594      594. 중랑물재생센터(서울새활용플라자)
1717125 2022-08-31 01640      1640. 한내근린공원 북측
1717126 2022-08-31 00591      591. 건국대학교 (행정관)
1717127 2022-08-31 00592      592. 건국대학교 학생회관
1717128 2022-08-31 01149      1149. 신방화역환승주차장
1717129 2022-08-31 03500      3500. 군자역2번출구
1717130 2022-08-31 03501      3501. 광진구청 앞
1717131 2022-08-31 03504      3504. 원일교회
1717132 2022-08-31 03505      3505. 신양초교앞 교차로
1717133 2022-08-31 00426      426. 서울신용보증재단
1717134 2022-08-31 00722      722. 경서농협 버스정류장(우리은행신정동지점방향)
1717135 2022-08-31 00723      723. SBS방송국
        대여구분코드 성별 연령대 이용건수 운동량 탄소량 이동거리(M)
1       정기권       NA   ~10대  1        49.28  0.36   1555.52
2       정기권       NA   ~10대  1        205.54 1.88   8110.00
3       정기권       NA   ~10대  3        86.36  1.02   4352.71
4       정기권       NA   ~10대  1        37.21  0.38   1619.99
5       정기권       NA   ~10대  2        66.16  0.48   2070.00
6       정기권       NA   ~10대  1        12.82  0.09    390.00
7       정기권       NA   ~10대  2        113.99 1.04   4486.81
8       정기권       NA   ~10대  1        14.67  0.13    570.00
9       정기권       NA   ~10대  1        51.47  0.50   2166.24
10      정기권       NA   ~10대  1        28.27  0.28   1190.00
11      정기권       NA   ~10대  1        9.41   0.10    440.00
12      정기권       NA   ~10대  1        20.45  0.12    501.46
13      정기권       NA   ~10대  3        109.30 1.01   4313.49
14      정기권       NA   ~10대  1        57.33  0.52   2227.43
15      정기권       NA   ~10대  1        10.45  0.10    440.00
16      정기권       NA   ~10대  2        62.05  0.60   2558.17
17      정기권       NA   ~10대  1        118.39 0.94   4040.00
18      정기권       NA   ~10대  1        35.12  0.33   1430.37
19      정기권       NA   ~10대  1        20.66  0.24   1043.32
20      정기권       NA   ~10대  2        67.97  0.50   2119.18
21      정기권       NA   ~10대  1        24.23  0.24   1019.85
22      정기권       NA   ~10대  1        15.21  0.19    800.00
23      정기권       NA   ~10대  3        36.20  0.40   1702.51
24      정기권       NA   ~10대  2        85.59  0.84   3624.31
25      정기권       NA   ~10대  1        2.20   0.02     88.03
26      정기권       NA   ~10대  2        37.09  0.31   1320.72
27      정기권       NA   ~10대  3        71.33  0.72   3127.92
28      정기권       NA   ~10대  2        47.53  0.95   4079.44
29      정기권       NA   ~10대  1        37.65  0.38   1639.40
30      정기권       NA   ~10대  1        48.06  0.38   1640.00
⋮       ⋮            ⋮    ⋮      ⋮        ⋮      ⋮      ⋮
1717106 정기권       M    기타   2        82.42  0.72    3103.09
1717107 정기권       M    기타   1        60.53  0.47    2038.00
1717108 정기권       M    기타   1        37.42  0.31    1350.00
1717109 정기권       M    기타   1        36.81  0.33    1430.00
1717110 정기권       M    기타   2        134.80 1.17    5011.03
1717111 정기권       M    기타   4        389.79 3.37   14540.00
1717112 정기권       M    기타   1        238.10 2.15    9250.00
1717113 정기권       M    기타   1        221.18 1.64    7070.00
1717114 정기권       M    기타   2        423.64 3.34   14400.00
1717115 정기권       M    기타   1        77.19  0.73    3143.85
1717116 정기권       M    기타   1        275.23 2.15    9267.07
1717117 정기권       M    기타   1        64.09  0.58    2490.00
1717118 정기권       M    기타   1        43.09  0.27    1170.00
1717119 정기권       M    기타   1        19.68  0.16     710.00
1717120 정기권       M    기타   1        98.70  0.64    2738.98
1717121 정기권       M    기타   1        43.52  0.36    1570.00
1717122 정기권       M    기타   1        50.71  0.46    1970.00
1717123 정기권       M    기타   1        28.89  0.20     868.42
1717124 정기권       M    기타   2        74.47  0.70    2985.07
1717125 정기권       M    기타   2        325.54 2.93   12647.20
1717126 정기권       M    기타   1        19.03  0.13     545.97
1717127 정기권       M    기타   3        156.90 1.16    5020.00
1717128 정기권       M    기타   1        84.73  0.61    2609.44
1717129 정기권       M    기타   2        147.43 1.38    5958.57
1717130 정기권       M    기타   3        264.34 1.85    7981.29
1717131 정기권       M    기타   2        94.42  0.82    3498.25
1717132 정기권       M    기타   1        0.00   0.00       0.00
1717133 정기권       M    기타   1        29.94  0.24    1050.00
1717134 정기권       M    기타   1        27.42  0.25    1065.39
1717135 정기권       M    기타   2        284.26 2.09    9010.72
        이용시간(분)
1         9
2        42
3        28
4        56
5        33
6         9
7        36
8         2
9        16
10        9
11        4
12        3
13       57
14       15
15        2
16       23
17       21
18       11
19        8
20       16
21       10
22        9
23      110
24       34
25        5
26        7
27       51
28       32
29        8
30        7
⋮       ⋮
1717106 104
1717107  27
1717108   4
1717109  18
1717110  37
1717111 211
1717112  45
1717113  51
1717114  92
1717115  15
1717116  49
1717117  13
1717118   4
1717119 146
1717120  23
1717121  16
1717122   8
1717123  56
1717124  86
1717125  85
1717126   3
1717127  95
1717128  15
1717129 142
1717130  98
1717131  29
1717132   1
1717133   8
1717134   6
1717135  53

In [ ]:
DF08$대여소번호 <- as.numeric(DF08$대여소번호)

In [ ]:
f_DF08<-DF08%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897,5751,5752,5753,5760,5756,5758,5759,5761,5763,5764,5765,5766,5767))
f_DF08

       대여일자   대여소번호 대여소                               대여구분코드
1      2022-08-01 1260       1260. 방이동 한양3차아파트 옆        정기권
2      2022-08-01 1263       1263. 장지공영차고지                 정기권
3      2022-08-01 1275       1275. 거여초등학교 옆                정기권
4      2022-08-01 1282       1282. 송파소방서 맞은편(성내4교)     정기권
5      2022-08-01 2606       2606. 위례동주민센터 맞은편 근린공원 정기권
6      2022-08-01 2608       2608. 송파구청                       정기권
7      2022-08-01 2614       2614. 가락고등학교 앞                정기권
8      2022-08-01 2622       2622. 올림픽공원역 3번출구           정기권
9      2022-08-01 2620       2620. 송파나루역 4번 출구옆          정기권
10     2022-08-01 2642       2642.마천동 성내천 쉼터              정기권
11     2022-08-01 2625       2625.가락종합 사회복지관             정기권
12     2022-08-01 2628       2628.문정역 1번출구                  정기권
13     2022-08-01 2630       2630.서울방이동 고분군               정기권
14     2022-08-01 2646       2646.레이크펠리스101동앞             정기권
15     2022-08-01 2657       2657.송파 파인타운 11단지            정기권
16     2022-08-01 4452       4452. 삼성SDS                        정기권
17     2022-08-01 4457       4457. 아산병원 기숙사 부근           정기권
18     2022-08-01 4458       4458. 가락2동주민센터 인근           정기권
19     2022-08-01 4468       4468. 가락1동주민센터                정기권
20     2022-08-01 4493       4493. 마천사거리 2                   정기권
21     2022-08-01 4859       4859. 잠실나루 나들목                정기권
22     2022-08-01 4871       4871. 오금동 대림아파트 정문         정기권
23     2022-08-01 4872       4872. 개롱역 3번 출구 뒤             정기권
24     2022-08-01 4873       4873. 개롱역사거리 2번 출구          정기권
25     2022-08-01 4879       4879. 마천청소년센터                 정기권
26     2022-08-01 1220       1220. 잠실근린공원                   정기권
27     2022-08-01 1229       1229. 송파체육문화회관 앞            정기권
28     2022-08-01 1203       1203. 밀리아나2빌딩 앞               정기권
29     2022-08-01 1207       1207. 마천중앙시장                   정기권
30     2022-08-01 1212       1212. 송파역 2번 출구앞              정기권
⋮      ⋮          ⋮          ⋮                                    ⋮
145833 2022-08-31 4870       4870. 몽촌토성역 3번 출구            정기권
145834 2022-08-31 4871       4871. 오금동 대림아파트 정문         정기권
145835 2022-08-31 4874       4874. 탄천1교 하부보도               정기권
145836 2022-08-31 4875       4875. 위례포레샤인13단지             정기권
145837 2022-08-31 4893       4893. 문정법조단지12                 정기권
145838 2022-08-31 4886       4886. 배명고등학교 건너편            정기권
145839 2022-08-31 4897       4897. 잠실주공5단지1                 정기권
145840 2022-08-31 4892       4892. 성내유수지 체육공원            정기권
145841 2022-08-31 1206       1206. 9호선종합운동장역 9번출구      정기권
145842 2022-08-31 1208       1208. 풍납현대아파트쉼터             정기권
145843 2022-08-31 1209       1209. 잠실나루역 (2번 출구 쪽)       정기권
145844 2022-08-31 1215       1215. 올림픽공원역 1번출구 앞        정기권
145845 2022-08-31 1222       1222. 잠실새내역 5번 출구 뒤         정기권
145846 2022-08-31 1224       1224. 아시아지하보도 2번 출구        정기권
145847 2022-08-31 1229       1229. 송파체육문화회관 앞            정기권
145848 2022-08-31 1232       1232. 잠실주공 521동 건너편          정기권
145849 2022-08-31 1235       1235. 잠실트리지움310동 옆           정기권
145850 2022-08-31 1203       1203. 밀리아나2빌딩 앞               정기권
145851 2022-08-31 1214       1214. 오금역 7번 출구 인근           정기권
145852 2022-08-31 1201       1201. 가락시장역 3번 출구            정기권
145853 2022-08-31 1231       1231. 잠실역 6번출구                 정기권
145854 2022-08-31 1231       1231. 잠실역 6번출구                 정기권
145855 2022-08-31 1210       1210. 롯데월드타워(잠실역2번출구 쪽) 정기권
145856 2022-08-31 1218       1218. 방이역 4번출구                 정기권
145857 2022-08-31 1228       1228. 마천사거리                     정기권
145858 2022-08-31 1243       1243. 문정 법조단지7                 정기권
145859 2022-08-31 1246       1246. 문정 법조단지10                정기권
145860 2022-08-31 1248       1248. 방이초등학교                   정기권
145861 2022-08-31 1249       1249. 아주중학교건너편               정기권
145862 2022-08-31 1249       1249. 아주중학교건너편               정기권
       성별 연령대 이용건수 운동량  탄소량 이동거리(M) 이용시간(분)
1      NA   ~10대  1        35.12   0.33   1430.37     11
2      NA   ~10대  1        20.66   0.24   1043.32      8
3      NA   ~10대  2        123.26  1.51   6484.92     42
4      NA   ~10대  1        32.13   0.29   1248.34      9
5      NA   ~10대  1        64.35   0.58   2500.00     14
6      NA   ~10대  1        48.44   0.46   1972.99     12
7      NA   ~10대  1        17.74   0.16    668.62      4
8      NA   ~10대  1        29.31   0.21    891.76      6
9      NA   ~10대  1        26.25   0.24   1020.00      8
10     NA   ~10대  1        36.50   0.33   1418.14     59
11     NA   ~10대  1        0.00    0.00      0.00      1
12     NA   ~10대  1        25.13   0.33   1410.00     10
13     NA   ~10대  2        48.35   0.49   2120.00     18
14     NA   ~10대  1        21.20   0.19    823.59      7
15     NA   ~10대  2        44.91   0.59   2520.00     19
16     NA   ~10대  1        26.40   0.26   1130.00      9
17     NA   ~10대  1        27.55   0.31   1338.00     14
18     NA   ~10대  2        48.82   0.56   2403.56     16
19     NA   ~10대  1        25.07   0.28   1217.29      8
20     NA   ~10대  1        30.60   0.32   1380.00     29
21     NA   ~10대  1        \\N     \\N       0.00     30
22     NA   ~10대  1        80.22   0.57   2440.58     13
23     NA   ~10대  1        23.06   0.24   1040.00     10
24     NA   ~10대  2        33.29   0.41   1751.34     19
25     NA   ~10대  1        42.50   0.28   1219.57      7
26     NA   ~10대  1        21.38   0.20    870.98      7
27     NA   ~10대  2        69.83   0.61   2644.39     16
28     NA   ~10대  1        21.38   0.25   1080.00      5
29     NA   ~10대  1        254.24  2.13   9171.58     76
30     NA   ~10대  3        183.72  2.07   8883.59     58
⋮      ⋮    ⋮      ⋮        ⋮       ⋮      ⋮           ⋮
145833 M    기타   2        138.12  1.24    5366.10     38
145834 M    기타   1        31.11   0.24    1033.83      6
145835 M    기타   1        62.19   0.52    2243.55     62
145836 M    기타   1        50.12   0.39    1687.53      8
145837 M    기타   4        1364.61 8.93   38454.14    229
145838 M    기타   1        14.69   0.12     530.00      5
145839 M    기타   1        30.12   0.27    1170.00      7
145840 M    기타   1        49.97   0.45    1941.25     16
145841 M    기타   1        24.95   0.19     840.00      4
145842 M    기타   1        0.67    0.01      24.15     10
145843 M    기타   2        66.98   0.49    2114.42     19
145844 M    기타   1        81.66   0.70    3032.67     94
145845 M    기타   2        241.12  1.95    8409.46     61
145846 M    기타   1        \\N     \\N        0.00    119
145847 M    기타   1        184.38  1.13    4850.00     71
145848 M    기타   1        51.47   0.41    1756.38     27
145849 M    기타   1        26.07   0.20     877.88     12
145850 M    기타   2        151.56  1.28    5538.65     29
145851 M    기타   1        53.19   0.46    1975.11     14
145852 M    기타   1        17.22   0.16     668.88      7
145853 M    기타   3        904.00  8.15   35120.25    131
145854 M    기타   1        9.08    0.07     310.00     60
145855 M    기타   3        265.12  2.10    9068.28    120
145856 M    기타   1        52.51   0.47    2040.00     16
145857 M    기타   1        208.84  1.29    5551.29     26
145858 M    기타   1        92.07   0.83    3576.89     17
145859 M    기타   1        25.29   0.29    1252.23     13
145860 M    기타   1        38.08   0.34    1479.59     86
145861 M    기타   1        22.69   0.18     763.97      6
145862 M    기타   1        44.58   0.41    1787.07     29

In [ ]:
selected_DF08 <- f_DF08 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대, 이용건수)
selected_DF08

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수
1      2022-08-01 1260       정기권       NA   ~10대  1
2      2022-08-01 1263       정기권       NA   ~10대  1
3      2022-08-01 1275       정기권       NA   ~10대  2
4      2022-08-01 1282       정기권       NA   ~10대  1
5      2022-08-01 2606       정기권       NA   ~10대  1
6      2022-08-01 2608       정기권       NA   ~10대  1
7      2022-08-01 2614       정기권       NA   ~10대  1
8      2022-08-01 2622       정기권       NA   ~10대  1
9      2022-08-01 2620       정기권       NA   ~10대  1
10     2022-08-01 2642       정기권       NA   ~10대  1
11     2022-08-01 2625       정기권       NA   ~10대  1
12     2022-08-01 2628       정기권       NA   ~10대  1
13     2022-08-01 2630       정기권       NA   ~10대  2
14     2022-08-01 2646       정기권       NA   ~10대  1
15     2022-08-01 2657       정기권       NA   ~10대  2
16     2022-08-01 4452       정기권       NA   ~10대  1
17     2022-08-01 4457       정기권       NA   ~10대  1
18     2022-08-01 4458       정기권       NA   ~10대  2
19     2022-08-01 4468       정기권       NA   ~10대  1
20     2022-08-01 4493       정기권       NA   ~10대  1
21     2022-08-01 4859       정기권       NA   ~10대  1
22     2022-08-01 4871       정기권       NA   ~10대  1
23     2022-08-01 4872       정기권       NA   ~10대  1
24     2022-08-01 4873       정기권       NA   ~10대  2
25     2022-08-01 4879       정기권       NA   ~10대  1
26     2022-08-01 1220       정기권       NA   ~10대  1
27     2022-08-01 1229       정기권       NA   ~10대  2
28     2022-08-01 1203       정기권       NA   ~10대  1
29     2022-08-01 1207       정기권       NA   ~10대  1
30     2022-08-01 1212       정기권       NA   ~10대  3
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮
145833 2022-08-31 4870       정기권       M    기타   2
145834 2022-08-31 4871       정기권       M    기타   1
145835 2022-08-31 4874       정기권       M    기타   1
145836 2022-08-31 4875       정기권       M    기타   1
145837 2022-08-31 4893       정기권       M    기타   4
145838 2022-08-31 4886       정기권       M    기타   1
145839 2022-08-31 4897       정기권       M    기타   1
145840 2022-08-31 4892       정기권       M    기타   1
145841 2022-08-31 1206       정기권       M    기타   1
145842 2022-08-31 1208       정기권       M    기타   1
145843 2022-08-31 1209       정기권       M    기타   2
145844 2022-08-31 1215       정기권       M    기타   1
145845 2022-08-31 1222       정기권       M    기타   2
145846 2022-08-31 1224       정기권       M    기타   1
145847 2022-08-31 1229       정기권       M    기타   1
145848 2022-08-31 1232       정기권       M    기타   1
145849 2022-08-31 1235       정기권       M    기타   1
145850 2022-08-31 1203       정기권       M    기타   2
145851 2022-08-31 1214       정기권       M    기타   1
145852 2022-08-31 1201       정기권       M    기타   1
145853 2022-08-31 1231       정기권       M    기타   3
145854 2022-08-31 1231       정기권       M    기타   1
145855 2022-08-31 1210       정기권       M    기타   3
145856 2022-08-31 1218       정기권       M    기타   1
145857 2022-08-31 1228       정기권       M    기타   1
145858 2022-08-31 1243       정기권       M    기타   1
145859 2022-08-31 1246       정기권       M    기타   1
145860 2022-08-31 1248       정기권       M    기타   1
145861 2022-08-31 1249       정기권       M    기타   1
145862 2022-08-31 1249       정기권       M    기타   1

In [ ]:
selected_DF08$`대여구분코드`<-ifelse(selected_DF08$`대여구분코드`=='정기권',1,0)

In [ ]:
selected_DF08$`성별`<-ifelse(selected_DF08$`성별`=='M',0,ifelse(selected_DF08$`성별`=='F',1,2))

In [ ]:
selected_DF08$`연령대`<-ifelse(selected_DF08$`연령대`=='~10대',0,ifelse(selected_DF08$`연령대`=='20대',1,
ifelse(selected_DF08$`연령대`=='30대',2,ifelse(selected_DF08$`연령대`=='40대',3,ifelse(selected_DF08$`연령대`=='50대',4,
ifelse(selected_DF08$`연령대`=='60대',5,ifelse(selected_DF08$`연령대`=='70대이상',6,7)))))))

In [ ]:
selected_DF08

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수
1      2022-08-01 1260       1            NA   0      1
2      2022-08-01 1263       1            NA   0      1
3      2022-08-01 1275       1            NA   0      2
4      2022-08-01 1282       1            NA   0      1
5      2022-08-01 2606       1            NA   0      1
6      2022-08-01 2608       1            NA   0      1
7      2022-08-01 2614       1            NA   0      1
8      2022-08-01 2622       1            NA   0      1
9      2022-08-01 2620       1            NA   0      1
10     2022-08-01 2642       1            NA   0      1
11     2022-08-01 2625       1            NA   0      1
12     2022-08-01 2628       1            NA   0      1
13     2022-08-01 2630       1            NA   0      2
14     2022-08-01 2646       1            NA   0      1
15     2022-08-01 2657       1            NA   0      2
16     2022-08-01 4452       1            NA   0      1
17     2022-08-01 4457       1            NA   0      1
18     2022-08-01 4458       1            NA   0      2
19     2022-08-01 4468       1            NA   0      1
20     2022-08-01 4493       1            NA   0      1
21     2022-08-01 4859       1            NA   0      1
22     2022-08-01 4871       1            NA   0      1
23     2022-08-01 4872       1            NA   0      1
24     2022-08-01 4873       1            NA   0      2
25     2022-08-01 4879       1            NA   0      1
26     2022-08-01 1220       1            NA   0      1
27     2022-08-01 1229       1            NA   0      2
28     2022-08-01 1203       1            NA   0      1
29     2022-08-01 1207       1            NA   0      1
30     2022-08-01 1212       1            NA   0      3
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮
145833 2022-08-31 4870       1            0    7      2
145834 2022-08-31 4871       1            0    7      1
145835 2022-08-31 4874       1            0    7      1
145836 2022-08-31 4875       1            0    7      1
145837 2022-08-31 4893       1            0    7      4
145838 2022-08-31 4886       1            0    7      1
145839 2022-08-31 4897       1            0    7      1
145840 2022-08-31 4892       1            0    7      1
145841 2022-08-31 1206       1            0    7      1
145842 2022-08-31 1208       1            0    7      1
145843 2022-08-31 1209       1            0    7      2
145844 2022-08-31 1215       1            0    7      1
145845 2022-08-31 1222       1            0    7      2
145846 2022-08-31 1224       1            0    7      1
145847 2022-08-31 1229       1            0    7      1
145848 2022-08-31 1232       1            0    7      1
145849 2022-08-31 1235       1            0    7      1
145850 2022-08-31 1203       1            0    7      2
145851 2022-08-31 1214       1            0    7      1
145852 2022-08-31 1201       1            0    7      1
145853 2022-08-31 1231       1            0    7      3
145854 2022-08-31 1231       1            0    7      1
145855 2022-08-31 1210       1            0    7      3
145856 2022-08-31 1218       1            0    7      1
145857 2022-08-31 1228       1            0    7      1
145858 2022-08-31 1243       1            0    7      1
145859 2022-08-31 1246       1            0    7      1
145860 2022-08-31 1248       1            0    7      1
145861 2022-08-31 1249       1            0    7      1
145862 2022-08-31 1249       1            0    7      1

In [ ]:
write.csv(selected_DF08,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.08.csv",row.names=FALSE, na="")

In [ ]:
selected_DF08$'평일/주말' <- ifelse(selected_DF08$대여일자 %in% date$date_time, date$weekend[match(selected_DF08$대여일자, date$date_time)], 2)
selected_DF08

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수 평일/주말
1      2022-08-01 1260       1            NA   0      1        0
2      2022-08-01 1263       1            NA   0      1        0
3      2022-08-01 1275       1            NA   0      2        0
4      2022-08-01 1282       1            NA   0      1        0
5      2022-08-01 2606       1            NA   0      1        0
6      2022-08-01 2608       1            NA   0      1        0
7      2022-08-01 2614       1            NA   0      1        0
8      2022-08-01 2622       1            NA   0      1        0
9      2022-08-01 2620       1            NA   0      1        0
10     2022-08-01 2642       1            NA   0      1        0
11     2022-08-01 2625       1            NA   0      1        0
12     2022-08-01 2628       1            NA   0      1        0
13     2022-08-01 2630       1            NA   0      2        0
14     2022-08-01 2646       1            NA   0      1        0
15     2022-08-01 2657       1            NA   0      2        0
16     2022-08-01 4452       1            NA   0      1        0
17     2022-08-01 4457       1            NA   0      1        0
18     2022-08-01 4458       1            NA   0      2        0
19     2022-08-01 4468       1            NA   0      1        0
20     2022-08-01 4493       1            NA   0      1        0
21     2022-08-01 4859       1            NA   0      1        0
22     2022-08-01 4871       1            NA   0      1        0
23     2022-08-01 4872       1            NA   0      1        0
24     2022-08-01 4873       1            NA   0      2        0
25     2022-08-01 4879       1            NA   0      1        0
26     2022-08-01 1220       1            NA   0      1        0
27     2022-08-01 1229       1            NA   0      2        0
28     2022-08-01 1203       1            NA   0      1        0
29     2022-08-01 1207       1            NA   0      1        0
30     2022-08-01 1212       1            NA   0      3        0
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮        ⋮
145833 2022-08-31 4870       1            0    7      2        0
145834 2022-08-31 4871       1            0    7      1        0
145835 2022-08-31 4874       1            0    7      1        0
145836 2022-08-31 4875       1            0    7      1        0
145837 2022-08-31 4893       1            0    7      4        0
145838 2022-08-31 4886       1            0    7      1        0
145839 2022-08-31 4897       1            0    7      1        0
145840 2022-08-31 4892       1            0    7      1        0
145841 2022-08-31 1206       1            0    7      1        0
145842 2022-08-31 1208       1            0    7      1        0
145843 2022-08-31 1209       1            0    7      2        0
145844 2022-08-31 1215       1            0    7      1        0
145845 2022-08-31 1222       1            0    7      2        0
145846 2022-08-31 1224       1            0    7      1        0
145847 2022-08-31 1229       1            0    7      1        0
145848 2022-08-31 1232       1            0    7      1        0
145849 2022-08-31 1235       1            0    7      1        0
145850 2022-08-31 1203       1            0    7      2        0
145851 2022-08-31 1214       1            0    7      1        0
145852 2022-08-31 1201       1            0    7      1        0
145853 2022-08-31 1231       1            0    7      3        0
145854 2022-08-31 1231       1            0    7      1        0
145855 2022-08-31 1210       1            0    7      3        0
145856 2022-08-31 1218       1            0    7      1        0
145857 2022-08-31 1228       1            0    7      1        0
145858 2022-08-31 1243       1            0    7      1        0
145859 2022-08-31 1246       1            0    7      1        0
145860 2022-08-31 1248       1            0    7      1        0
145861 2022-08-31 1249       1            0    7      1        0
145862 2022-08-31 1249       1            0    7      1        0

In [ ]:
selected_DF08 <- selected_DF08 %>% select('평일/주말', '대여구분코드', '성별', '연령대', '이용건수')
selected_DF08

       평일/주말 대여구분코드 성별 연령대 이용건수
1      0         1            NA   0      1
2      0         1            NA   0      1
3      0         1            NA   0      2
4      0         1            NA   0      1
5      0         1            NA   0      1
6      0         1            NA   0      1
7      0         1            NA   0      1
8      0         1            NA   0      1
9      0         1            NA   0      1
10     0         1            NA   0      1
11     0         1            NA   0      1
12     0         1            NA   0      1
13     0         1            NA   0      2
14     0         1            NA   0      1
15     0         1            NA   0      2
16     0         1            NA   0      1
17     0         1            NA   0      1
18     0         1            NA   0      2
19     0         1            NA   0      1
20     0         1            NA   0      1
21     0         1            NA   0      1
22     0         1            NA   0      1
23     0         1            NA   0      1
24     0         1            NA   0      2
25     0         1            NA   0      1
26     0         1            NA   0      1
27     0         1            NA   0      2
28     0         1            NA   0      1
29     0         1            NA   0      1
30     0         1            NA   0      3
⋮      ⋮         ⋮            ⋮    ⋮      ⋮
145833 0         1            0    7      2
145834 0         1            0    7      1
145835 0         1            0    7      1
145836 0         1            0    7      1
145837 0         1            0    7      4
145838 0         1            0    7      1
145839 0         1            0    7      1
145840 0         1            0    7      1
145841 0         1            0    7      1
145842 0         1            0    7      1
145843 0         1            0    7      2
145844 0         1            0    7      1
145845 0         1            0    7      2
145846 0         1            0    7      1
145847 0         1            0    7      1
145848 0         1            0    7      1
145849 0         1            0    7      1
145850 0         1            0    7      2
145851 0         1            0    7      1
145852 0         1            0    7      1
145853 0         1            0    7      3
145854 0         1            0    7      1
145855 0         1            0    7      3
145856 0         1            0    7      1
145857 0         1            0    7      1
145858 0         1            0    7      1
145859 0         1            0    7      1
145860 0         1            0    7      1
145861 0         1            0    7      1
145862 0         1            0    7      1

In [ ]:
summarized_data_08 <- selected_DF08 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data_08

   대여일자   이용건수_합계
1  2022-08-01  9862
2  2022-08-02  6010
3  2022-08-03  9297
4  2022-08-04 12536
5  2022-08-05 12366
6  2022-08-06  8715
7  2022-08-07  8497
8  2022-08-08  1866
9  2022-08-09    24
10 2022-08-10  8662
11 2022-08-11  8545
12 2022-08-12 12475
13 2022-08-13  7975
14 2022-08-14  7617
15 2022-08-15  7468
16 2022-08-16 13021
17 2022-08-17 13391
18 2022-08-18 13962
19 2022-08-19  6913
20 2022-08-20 11604
21 2022-08-21 10997
22 2022-08-22 12667
23 2022-08-23 12718
24 2022-08-24 14958
25 2022-08-25 10993
26 2022-08-26 15222
27 2022-08-27 16519
28 2022-08-28 15478
29 2022-08-29  9258
30 2022-08-30  1274
31 2022-08-31 14077

## **9월 전처리**

In [ ]:
 #https://drive.google.com/file/d/1OohUX0yKk61WomlhmV9bfbqcF4gGiO14/view?usp=sharing
system("gdown --id 1OohUX0yKk61WomlhmV9bfbqcF4gGiO14")
system("ls",TRUE)

 [1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [2] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [3] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [4] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [5] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [6] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [7] "서울특별시 공공자전거 이용정보(일별)_22.04.csv"
 [8] "서울특별시 공공자전거 이용정보(일별)_22.05.csv"
 [9] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.05.csv"
[10] "서울특별시 공공자전거 이용정보(일별)_22.06.csv"
[11] "서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[12] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[13] "서울특별시 공공자전거 이용정보(일별)_22.08.csv"
[14] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.08.csv"
[15] "서울특별시 공공자전거 이용정보(일별)_2209.csv"
[16] "sample_data"

In [ ]:
DF09<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_2209.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF09

Rows: 2050121 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): 대여소번호, 대여소, 대여구분코드, 성별, 연령대, 운동량, 탄소량
dbl  (3): 이용건수, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        대여일자   대여소번호 대여소
1       2022-09-01 00729      729. 서부식자재마트 건너편
2       2022-09-01 00733      733. 신정이펜하우스314동
3       2022-09-01 00734      734. 신트리공원 입구
4       2022-09-01 00735      735. 영도초등학교
5       2022-09-01 00736      736. 오솔길공원
6       2022-09-01 00742      742. 등촌역 5번 출구 뒤
7       2022-09-01 00746      746. 목동2단지 상가
8       2022-09-01 00747      747. 목동3단지 상가
9       2022-09-01 00748      748. 목동운동장
10      2022-09-01 00505      505. 자양사거리 광진아크로텔 앞
11      2022-09-01 00946      946. 독바위역
12      2022-09-01 00948      948. 디지털미디어 시티역 4번출구(DMC역)
13      2022-09-01 00949      949. 연신내역 1번 출구
14      2022-09-01 00950      950. 구산역 2번 출구 예일여고 버스정류장
15      2022-09-01 01023      1023. 한국종합기술사옥 앞
16      2022-09-01 01035      1035. 고덕역 4번출구
17      2022-09-01 01036      1036. 고덕동 주양쇼핑
18      2022-09-01 01041      1041. 묘곡초등학교
19      2022-09-01 00509      509. 이마트 버스정류소 옆
20      2022-09-01 01044      1044. 굽은다리역
21      2022-09-01 01150      1150. 송정역 1번출구
22      2022-09-01 01151      1151. 마곡역1번출구
23      2022-09-01 01151      1151. 마곡역1번출구
24      2022-09-01 01152      1152. 마곡역교차로
25      2022-09-01 01153      1153. 발산역 1번, 9번 인근 대여소
26      2022-09-01 01153      1153. 발산역 1번, 9번 인근 대여소
27      2022-09-01 01155      1155. 기쁜우리복지관
28      2022-09-01 01251      1251. 석촌역 2번출구
29      2022-09-01 01260      1260. 방이동 한양3차아파트 옆
30      2022-09-01 00511      511. 서울숲역 5번 출구 옆
⋮       ⋮          ⋮          ⋮
2050092 2022-09-30 01931      1931. 개봉역2번출구 A
2050093 2022-09-30 02211      2211. 서초구립반포도서관 앞
2050094 2022-09-30 02211      2211. 서초구립반포도서관 앞
2050095 2022-09-30 00417      417. DMC역 2번출구 옆
2050096 2022-09-30 01221      1221. 삼전역 4번출구
2050097 2022-09-30 02264      2264. 이수역 1번출구
2050098 2022-09-30 01955      1955. 디지털입구 교차로
2050099 2022-09-30 00414      414. 상암동주민센터 옆
2050100 2022-09-30 00389      389. 을지로4가역 1번출구
2050101 2022-09-30 01305      1305. 성북구청
2050102 2022-09-30 00415      415. DMC역 9번출구 앞
2050103 2022-09-30 02139      2139. 서울신성초등학교
2050104 2022-09-30 02156      2156. 신림푸르지오아파트
2050105 2022-09-30 02353      2353. 강남구청역 2번출구 뒤
2050106 2022-09-30 01642      1642. 서울여대 남문
2050107 2022-09-30 00500      500. 어린이대공원역 3번출구 앞
2050108 2022-09-30 01641      1641. 한내근린공원 남측
2050109 2022-09-30 01640      1640. 한내근린공원 북측
2050110 2022-09-30 00591      591. 건국대학교 (행정관)
2050111 2022-09-30 00592      592. 건국대학교 학생회관
2050112 2022-09-30 01149      1149. 신방화역환승주차장
2050113 2022-09-30 00450      450. 효자동 삼거리
2050114 2022-09-30 00501      501. 광진구의회 앞
2050115 2022-09-30 03500      3500. 군자역2번출구
2050116 2022-09-30 03501      3501. 광진구청 앞
2050117 2022-09-30 03502      3502. 중곡역 1번출구
2050118 2022-09-30 03505      3505. 신양초교앞 교차로
2050119 2022-09-30 00502      502. 뚝섬유원지역 1번출구 앞
2050120 2022-09-30 00723      723. SBS방송국
2050121 2022-09-30 00725      725. 양강중학교앞 교차로
        대여구분코드 성별 연령대 이용건수 운동량 탄소량 이동거리(M)
1       정기권       NA   ~10대  2        95.79  0.75    3224.92
2       정기권       NA   ~10대  2        103.89 0.92    3955.17
3       정기권       NA   ~10대  2        327.83 2.82   12170.00
4       정기권       NA   ~10대  4        76.66  0.80    3465.79
5       정기권       NA   ~10대  1        76.38  0.56    2411.07
6       정기권       NA   ~10대  1        42.73  0.39    1660.00
7       정기권       NA   ~10대  3        183.28 1.45    6281.16
8       정기권       NA   ~10대  4        241.05 2.15    9267.08
9       정기권       NA   ~10대  1        21.42  0.24    1040.00
10      정기권       NA   ~10대  1        42.42  0.37    1598.90
11      정기권       NA   ~10대  1        60.32  0.52    2240.00
12      정기권       NA   ~10대  2        33.00  0.38    1633.88
13      정기권       NA   ~10대  1        22.91  0.21     890.00
14      정기권       NA   ~10대  1        35.98  0.19     825.96
15      정기권       NA   ~10대  1        106.20 0.97    4190.39
16      정기권       NA   ~10대  4        145.66 1.17    4989.65
17      정기권       NA   ~10대  1        36.53  0.48    2050.00
18      정기권       NA   ~10대  1        14.75  0.11     490.00
19      정기권       NA   ~10대  1        13.62  0.18     781.48
20      정기권       NA   ~10대  3        60.12  0.46    1980.00
21      정기권       NA   ~10대  2        112.84 1.07    4614.25
22      정기권       NA   ~10대  1        7.60   0.07     320.00
23      정기권       NA   ~10대  1        28.63  0.26    1112.33
24      정기권       NA   ~10대  1        26.40  0.24    1025.60
25      정기권       NA   ~10대  5        202.19 1.94    8353.46
26      정기권       NA   ~10대  1        39.98  0.36    1553.05
27      정기권       NA   ~10대  2        91.42  0.74    3160.00
28      정기권       NA   ~10대  1        20.78  0.16     699.62
29      정기권       NA   ~10대  1        15.22  0.14     620.00
30      정기권       NA   ~10대  1        42.17  0.49    2130.00
⋮       ⋮            ⋮    ⋮      ⋮        ⋮      ⋮      ⋮
2050092 정기권       M    기타   1        0.00   0.00       0.00
2050093 정기권       M    기타   1        15.44  0.14     600.00
2050094 정기권       M    기타   1        46.47  0.42    1805.48
2050095 정기권       M    기타   1        36.09  0.32    1380.83
2050096 정기권       M    기타   1        12.14  0.11     471.79
2050097 정기권       M    기타   2        224.47 2.08    8936.51
2050098 정기권       M    기타   1        29.56  0.27    1148.42
2050099 정기권       M    기타   2        699.14 4.17   17970.00
2050100 정기권       M    기타   1        80.78  0.59    2550.00
2050101 정기권       M    기타   1        22.89  0.16     680.00
2050102 정기권       M    기타   1        418.18 3.27   14080.00
2050103 정기권       M    기타   1        486.62 4.39   18905.05
2050104 정기권       M    기타   2        494.54 4.08   17592.48
2050105 정기권       M    기타   1        138.39 1.08    4659.75
2050106 정기권       M    기타   2        49.18  0.46    1962.90
2050107 정기권       M    기타   1        28.04  0.27    1180.00
2050108 정기권       M    기타   1        106.89 0.86    3697.64
2050109 정기권       M    기타   1        260.52 2.35   10121.02
2050110 정기권       M    기타   2        35.69  0.28    1186.02
2050111 정기권       M    기타   2        89.62  0.74    3178.83
2050112 정기권       M    기타   1        23.76  0.17     750.00
2050113 정기권       M    기타   2        237.86 1.96    8466.67
2050114 정기권       M    기타   1        9.50   0.08     324.13
2050115 정기권       M    기타   2        687.41 4.76   20512.81
2050116 정기권       M    기타   2        196.49 1.39    5950.31
2050117 정기권       M    기타   1        137.04 1.00    4325.83
2050118 정기권       M    기타   1        48.39  0.44    1880.00
2050119 정기권       M    기타   4        537.25 5.05   21741.61
2050120 정기권       M    기타   2        271.70 2.44   10496.31
2050121 정기권       M    기타   1        55.68  0.34    1480.00
        이용시간(분)
1       16
2       25
3       72
4       45
5       12
6       14
7       83
8       77
9       11
10      16
11      56
12      14
13       2
14       3
15      31
16      50
17      12
18       1
19       4
20      17
21      45
22       3
23       7
24       4
25      77
26      10
27      18
28      11
29       3
30      25
⋮       ⋮
2050092   2
2050093   4
2050094  81
2050095   7
2050096   3
2050097  43
2050098   8
2050099 120
2050100  19
2050101   3
2050102  90
2050103 106
2050104 100
2050105  28
2050106  13
2050107   7
2050108  22
2050109  82
2050110  32
2050111  20
2050112   7
2050113 146
2050114   4
2050115 102
2050116 104
2050117  41
2050118  12
2050119 295
2050120  51
2050121   7

In [ ]:
DF09$대여소번호 <- as.numeric(DF09$대여소번호)

In [ ]:
f_DF09<-DF09%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897,5751,5752,5753,5760,5756,5758,5759,5761,5763,5764,5765,5766,5767))
f_DF09

       대여일자   대여소번호 대여소
1      2022-09-01 1251       1251. 석촌역 2번출구
2      2022-09-01 1260       1260. 방이동 한양3차아파트 옆
3      2022-09-01 1264       1264. 천호역 10번 출구 앞
4      2022-09-01 1265       1265. 문정동 근린공원
5      2022-09-01 1269       1269. 리센츠아파트
6      2022-09-01 1275       1275. 거여초등학교 옆
7      2022-09-01 1277       1277. 성내6교
8      2022-09-01 1288       1288. 문정중교 사거리
9      2022-09-01 1295       1295. 잠실역 8번출구
10     2022-09-01 1299       1299. 송파소방서 (방이119안전센터)
11     2022-09-01 2601       2601. 석촌호수 아뜰리에
12     2022-09-01 2606       2606. 위례동주민센터 맞은편 근린공원
13     2022-09-01 2615       2615. 테라타워2
14     2022-09-01 2621       2621. 한성백제역 2번 출구
15     2022-09-01 2620       2620. 송파나루역 4번 출구옆
16     2022-09-01 2644       2644. 성내5교
17     2022-09-01 2623       2623.석촌동 주민센터
18     2022-09-01 2630       2630.서울방이동 고분군
19     2022-09-01 2632       2632.석촌고분역 2번 출구
20     2022-09-01 2633       2633.송파학사 옆
21     2022-09-01 2635       2635.잠실새내역 1번출구
22     2022-09-01 2646       2646.레이크펠리스101동앞
23     2022-09-01 2647       2647.잠실 자전거 수리센터 앞
24     2022-09-01 2648       2648.헬리오시티 112동 앞
25     2022-09-01 2651       2651.경찰병원역 3번출구 앞
26     2022-09-01 2652       2652.송파 레미니스1단지 102동 앞
27     2022-09-01 2655       2655.송이공원
28     2022-09-01 2656       2656.풍납동 아이파크 107동 앞
29     2022-09-01 4452       4452. 삼성SDS
30     2022-09-01 4465       4465. 건영아파트앞 사거리
⋮      ⋮          ⋮          ⋮
175653 2022-09-30 4870       4870. 몽촌토성역 3번 출구
175654 2022-09-30 4871       4871. 오금동 대림아파트 정문
175655 2022-09-30 4875       4875. 위례포레샤인13단지
175656 2022-09-30 4876       4876. 삼전동주민센터 앞
175657 2022-09-30 4881       4881. 거여동사거리 송파둘레길 입구
175658 2022-09-30 4883       4883. 위례포레샤인18단지 1812동
175659 2022-09-30 4893       4893. 문정법조단지12
175660 2022-09-30 4884       4884. H비즈니스파크
175661 2022-09-30 4885       4885. 가든파이브 리빙관
175662 2022-09-30 4897       4897. 잠실주공5단지1
175663 2022-09-30 4891       4891. 위례포레샤인17단지 위례대로 방면
175664 2022-09-30 1205       1205. 종합운동장역 4번출구
175665 2022-09-30 1208       1208. 풍납현대아파트쉼터
175666 2022-09-30 1209       1209. 잠실나루역 (2번 출구 쪽)
175667 2022-09-30 1213       1213. 백토공원 앞
175668 2022-09-30 1224       1224. 아시아지하보도 2번 출구
175669 2022-09-30 1207       1207. 마천중앙시장
175670 2022-09-30 1201       1201. 가락시장역 3번 출구
175671 2022-09-30 1231       1231. 잠실역 6번출구
175672 2022-09-30 1210       1210. 롯데월드타워(잠실역2번출구 쪽)
175673 2022-09-30 1218       1218. 방이역 4번출구
175674 2022-09-30 1228       1228. 마천사거리
175675 2022-09-30 1241       1241. 문정 법조단지5
175676 2022-09-30 1243       1243. 문정 법조단지7
175677 2022-09-30 1245       1245. 문정 법조단지9
175678 2022-09-30 1246       1246. 문정 법조단지10
175679 2022-09-30 1247       1247. 문정 법조단지11
175680 2022-09-30 1248       1248. 방이초등학교
175681 2022-09-30 1249       1249. 아주중학교건너편
175682 2022-09-30 1249       1249. 아주중학교건너편
       대여구분코드 성별 연령대 이용건수 운동량 탄소량 이동거리(M) 이용시간(분)
1      정기권       NA   ~10대  1        20.78  0.16     699.62     11
2      정기권       NA   ~10대  1        15.22  0.14     620.00      3
3      정기권       NA   ~10대  3        391.79 2.89   12430.00     53
4      정기권       NA   ~10대  1        17.92  0.17     730.00      5
5      정기권       NA   ~10대  3        142.13 1.24    5380.07     84
6      정기권       NA   ~10대  1        15.78  0.19     830.00      7
7      정기권       NA   ~10대  1        40.39  0.39    1700.00      8
8      정기권       NA   ~10대  2        109.45 1.06    4542.64     40
9      정기권       NA   ~10대  1        11.71  0.11     469.56      4
10     정기권       NA   ~10대  2        66.43  0.63    2712.95     20
11     정기권       NA   ~10대  1        43.28  0.39    1681.48      7
12     정기권       NA   ~10대  2        261.54 2.45   10538.11     64
13     정기권       NA   ~10대  1        21.82  0.21     918.22      8
14     정기권       NA   ~10대  1        33.20  0.30    1290.00     10
15     정기권       NA   ~10대  1        26.51  0.24    1030.00      7
16     정기권       NA   ~10대  2        32.10  0.33    1444.23      9
17     정기권       NA   ~10대  1        26.22  0.24    1018.69      6
18     정기권       NA   ~10대  3        155.79 1.20    5163.30     55
19     정기권       NA   ~10대  2        106.49 0.94    4049.64     25
20     정기권       NA   ~10대  1        56.34  0.50    2155.52     10
21     정기권       NA   ~10대  2        85.25  0.85    3703.43    114
22     정기권       NA   ~10대  3        114.04 0.99    4288.78     32
23     정기권       NA   ~10대  1        18.27  0.16     709.98      5
24     정기권       NA   ~10대  1        21.69  0.19     830.00      6
25     정기권       NA   ~10대  1        37.00  0.30    1280.00      6
26     정기권       NA   ~10대  2        44.39  0.46    1957.96     14
27     정기권       NA   ~10대  1        22.03  0.25    1070.00      9
28     정기권       NA   ~10대  1        118.44 1.16    4984.73     36
29     정기권       NA   ~10대  1        83.96  0.78    3365.27     25
30     정기권       NA   ~10대  2        53.00  0.49    2107.07     62
⋮      ⋮            ⋮    ⋮      ⋮        ⋮      ⋮      ⋮           ⋮
175653 정기권       M    기타   1        157.52 0.97    4187.01    25
175654 정기권       M    기타   1        39.12  0.30    1300.00     4
175655 정기권       M    기타   1        294.62 2.30    9919.73    32
175656 정기권       M    기타   1        10.45  0.08     330.00     3
175657 정기권       M    기타   1        22.39  0.21     911.87     7
175658 정기권       M    기타   1        72.25  0.50    2146.42    54
175659 정기권       M    기타   1        311.29 2.03    8734.26    69
175660 정기권       M    기타   1        377.40 3.35   14440.00    71
175661 정기권       M    기타   1        475.91 4.29   18489.12    59
175662 정기권       M    기타   1        69.34  0.62    2693.81    89
175663 정기권       M    기타   1        17.76  0.16     690.00     3
175664 정기권       M    기타   1        24.73  0.23     991.23     6
175665 정기권       M    기타   3        330.29 3.12   13409.02    71
175666 정기권       M    기타   2        115.30 0.99    4270.00    47
175667 정기권       M    기타   1        74.33  0.70    3027.34    16
175668 정기권       M    기타   1        5.94   0.03     150.00     5
175669 정기권       M    기타   1        19.05  0.17     740.14     7
175670 정기권       M    기타   1        26.46  0.24    1028.07     6
175671 정기권       M    기타   1        130.87 0.95    4080.00    38
175672 정기권       M    기타   5        313.68 2.49   10715.33    98
175673 정기권       M    기타   2        62.97  0.49    2113.81    25
175674 정기권       M    기타   1        218.20 1.35    5800.00    30
175675 정기권       M    기타   1        105.66 0.95    4104.83    24
175676 정기권       M    기타   1        20.12  0.16     705.73     8
175677 정기권       M    기타   1        64.72  0.57    2439.30    19
175678 정기권       M    기타   1        61.97  0.35    1490.37    12
175679 정기권       M    기타   1        39.50  0.32    1366.57    16
175680 정기권       M    기타   2        139.89 0.92    3980.11    97
175681 정기권       M    기타   1        21.73  0.17     731.62     4
175682 정기권       M    기타   1        26.51  0.24    1030.00     3

In [ ]:
selected_DF09<- f_DF09 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대, 이용건수)
selected_DF09

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수
1      2022-09-01 1251       정기권       NA   ~10대  1
2      2022-09-01 1260       정기권       NA   ~10대  1
3      2022-09-01 1264       정기권       NA   ~10대  3
4      2022-09-01 1265       정기권       NA   ~10대  1
5      2022-09-01 1269       정기권       NA   ~10대  3
6      2022-09-01 1275       정기권       NA   ~10대  1
7      2022-09-01 1277       정기권       NA   ~10대  1
8      2022-09-01 1288       정기권       NA   ~10대  2
9      2022-09-01 1295       정기권       NA   ~10대  1
10     2022-09-01 1299       정기권       NA   ~10대  2
11     2022-09-01 2601       정기권       NA   ~10대  1
12     2022-09-01 2606       정기권       NA   ~10대  2
13     2022-09-01 2615       정기권       NA   ~10대  1
14     2022-09-01 2621       정기권       NA   ~10대  1
15     2022-09-01 2620       정기권       NA   ~10대  1
16     2022-09-01 2644       정기권       NA   ~10대  2
17     2022-09-01 2623       정기권       NA   ~10대  1
18     2022-09-01 2630       정기권       NA   ~10대  3
19     2022-09-01 2632       정기권       NA   ~10대  2
20     2022-09-01 2633       정기권       NA   ~10대  1
21     2022-09-01 2635       정기권       NA   ~10대  2
22     2022-09-01 2646       정기권       NA   ~10대  3
23     2022-09-01 2647       정기권       NA   ~10대  1
24     2022-09-01 2648       정기권       NA   ~10대  1
25     2022-09-01 2651       정기권       NA   ~10대  1
26     2022-09-01 2652       정기권       NA   ~10대  2
27     2022-09-01 2655       정기권       NA   ~10대  1
28     2022-09-01 2656       정기권       NA   ~10대  1
29     2022-09-01 4452       정기권       NA   ~10대  1
30     2022-09-01 4465       정기권       NA   ~10대  2
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮
175653 2022-09-30 4870       정기권       M    기타   1
175654 2022-09-30 4871       정기권       M    기타   1
175655 2022-09-30 4875       정기권       M    기타   1
175656 2022-09-30 4876       정기권       M    기타   1
175657 2022-09-30 4881       정기권       M    기타   1
175658 2022-09-30 4883       정기권       M    기타   1
175659 2022-09-30 4893       정기권       M    기타   1
175660 2022-09-30 4884       정기권       M    기타   1
175661 2022-09-30 4885       정기권       M    기타   1
175662 2022-09-30 4897       정기권       M    기타   1
175663 2022-09-30 4891       정기권       M    기타   1
175664 2022-09-30 1205       정기권       M    기타   1
175665 2022-09-30 1208       정기권       M    기타   3
175666 2022-09-30 1209       정기권       M    기타   2
175667 2022-09-30 1213       정기권       M    기타   1
175668 2022-09-30 1224       정기권       M    기타   1
175669 2022-09-30 1207       정기권       M    기타   1
175670 2022-09-30 1201       정기권       M    기타   1
175671 2022-09-30 1231       정기권       M    기타   1
175672 2022-09-30 1210       정기권       M    기타   5
175673 2022-09-30 1218       정기권       M    기타   2
175674 2022-09-30 1228       정기권       M    기타   1
175675 2022-09-30 1241       정기권       M    기타   1
175676 2022-09-30 1243       정기권       M    기타   1
175677 2022-09-30 1245       정기권       M    기타   1
175678 2022-09-30 1246       정기권       M    기타   1
175679 2022-09-30 1247       정기권       M    기타   1
175680 2022-09-30 1248       정기권       M    기타   2
175681 2022-09-30 1249       정기권       M    기타   1
175682 2022-09-30 1249       정기권       M    기타   1

In [ ]:
selected_DF09$`대여구분코드`<-ifelse(selected_DF09$`대여구분코드`=='정기권',1,0)

In [ ]:
selected_DF09$`성별`<-ifelse(selected_DF09$`성별`=='M',0,ifelse(selected_DF09$`성별`=='F',1,2))

In [ ]:
selected_DF09$`연령대`<-ifelse(selected_DF09$`연령대`=='~10대',0,ifelse(selected_DF09$`연령대`=='20대',1,
ifelse(selected_DF09$`연령대`=='30대',2,ifelse(selected_DF09$`연령대`=='40대',3,ifelse(selected_DF09$`연령대`=='50대',4,
ifelse(selected_DF09$`연령대`=='60대',5,ifelse(selected_DF09$`연령대`=='70대이상',6,7)))))))

In [ ]:
selected_DF09

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수
1      2022-09-01 1251       1            NA   0      1
2      2022-09-01 1260       1            NA   0      1
3      2022-09-01 1264       1            NA   0      3
4      2022-09-01 1265       1            NA   0      1
5      2022-09-01 1269       1            NA   0      3
6      2022-09-01 1275       1            NA   0      1
7      2022-09-01 1277       1            NA   0      1
8      2022-09-01 1288       1            NA   0      2
9      2022-09-01 1295       1            NA   0      1
10     2022-09-01 1299       1            NA   0      2
11     2022-09-01 2601       1            NA   0      1
12     2022-09-01 2606       1            NA   0      2
13     2022-09-01 2615       1            NA   0      1
14     2022-09-01 2621       1            NA   0      1
15     2022-09-01 2620       1            NA   0      1
16     2022-09-01 2644       1            NA   0      2
17     2022-09-01 2623       1            NA   0      1
18     2022-09-01 2630       1            NA   0      3
19     2022-09-01 2632       1            NA   0      2
20     2022-09-01 2633       1            NA   0      1
21     2022-09-01 2635       1            NA   0      2
22     2022-09-01 2646       1            NA   0      3
23     2022-09-01 2647       1            NA   0      1
24     2022-09-01 2648       1            NA   0      1
25     2022-09-01 2651       1            NA   0      1
26     2022-09-01 2652       1            NA   0      2
27     2022-09-01 2655       1            NA   0      1
28     2022-09-01 2656       1            NA   0      1
29     2022-09-01 4452       1            NA   0      1
30     2022-09-01 4465       1            NA   0      2
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮
175653 2022-09-30 4870       1            0    7      1
175654 2022-09-30 4871       1            0    7      1
175655 2022-09-30 4875       1            0    7      1
175656 2022-09-30 4876       1            0    7      1
175657 2022-09-30 4881       1            0    7      1
175658 2022-09-30 4883       1            0    7      1
175659 2022-09-30 4893       1            0    7      1
175660 2022-09-30 4884       1            0    7      1
175661 2022-09-30 4885       1            0    7      1
175662 2022-09-30 4897       1            0    7      1
175663 2022-09-30 4891       1            0    7      1
175664 2022-09-30 1205       1            0    7      1
175665 2022-09-30 1208       1            0    7      3
175666 2022-09-30 1209       1            0    7      2
175667 2022-09-30 1213       1            0    7      1
175668 2022-09-30 1224       1            0    7      1
175669 2022-09-30 1207       1            0    7      1
175670 2022-09-30 1201       1            0    7      1
175671 2022-09-30 1231       1            0    7      1
175672 2022-09-30 1210       1            0    7      5
175673 2022-09-30 1218       1            0    7      2
175674 2022-09-30 1228       1            0    7      1
175675 2022-09-30 1241       1            0    7      1
175676 2022-09-30 1243       1            0    7      1
175677 2022-09-30 1245       1            0    7      1
175678 2022-09-30 1246       1            0    7      1
175679 2022-09-30 1247       1            0    7      1
175680 2022-09-30 1248       1            0    7      2
175681 2022-09-30 1249       1            0    7      1
175682 2022-09-30 1249       1            0    7      1

In [ ]:
write.csv(selected_DF09,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.09.csv",row.names=FALSE, na="")

In [ ]:
selected_DF09$'평일/주말' <- ifelse(selected_DF09$대여일자 %in% date$date_time, date$weekend[match(selected_DF09$대여일자, date$date_time)], 2)
selected_DF09

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수 평일/주말
1      2022-09-01 1251       1            NA   0      1        0
2      2022-09-01 1260       1            NA   0      1        0
3      2022-09-01 1264       1            NA   0      3        0
4      2022-09-01 1265       1            NA   0      1        0
5      2022-09-01 1269       1            NA   0      3        0
6      2022-09-01 1275       1            NA   0      1        0
7      2022-09-01 1277       1            NA   0      1        0
8      2022-09-01 1288       1            NA   0      2        0
9      2022-09-01 1295       1            NA   0      1        0
10     2022-09-01 1299       1            NA   0      2        0
11     2022-09-01 2601       1            NA   0      1        0
12     2022-09-01 2606       1            NA   0      2        0
13     2022-09-01 2615       1            NA   0      1        0
14     2022-09-01 2621       1            NA   0      1        0
15     2022-09-01 2620       1            NA   0      1        0
16     2022-09-01 2644       1            NA   0      2        0
17     2022-09-01 2623       1            NA   0      1        0
18     2022-09-01 2630       1            NA   0      3        0
19     2022-09-01 2632       1            NA   0      2        0
20     2022-09-01 2633       1            NA   0      1        0
21     2022-09-01 2635       1            NA   0      2        0
22     2022-09-01 2646       1            NA   0      3        0
23     2022-09-01 2647       1            NA   0      1        0
24     2022-09-01 2648       1            NA   0      1        0
25     2022-09-01 2651       1            NA   0      1        0
26     2022-09-01 2652       1            NA   0      2        0
27     2022-09-01 2655       1            NA   0      1        0
28     2022-09-01 2656       1            NA   0      1        0
29     2022-09-01 4452       1            NA   0      1        0
30     2022-09-01 4465       1            NA   0      2        0
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮        ⋮
175653 2022-09-30 4870       1            0    7      1        0
175654 2022-09-30 4871       1            0    7      1        0
175655 2022-09-30 4875       1            0    7      1        0
175656 2022-09-30 4876       1            0    7      1        0
175657 2022-09-30 4881       1            0    7      1        0
175658 2022-09-30 4883       1            0    7      1        0
175659 2022-09-30 4893       1            0    7      1        0
175660 2022-09-30 4884       1            0    7      1        0
175661 2022-09-30 4885       1            0    7      1        0
175662 2022-09-30 4897       1            0    7      1        0
175663 2022-09-30 4891       1            0    7      1        0
175664 2022-09-30 1205       1            0    7      1        0
175665 2022-09-30 1208       1            0    7      3        0
175666 2022-09-30 1209       1            0    7      2        0
175667 2022-09-30 1213       1            0    7      1        0
175668 2022-09-30 1224       1            0    7      1        0
175669 2022-09-30 1207       1            0    7      1        0
175670 2022-09-30 1201       1            0    7      1        0
175671 2022-09-30 1231       1            0    7      1        0
175672 2022-09-30 1210       1            0    7      5        0
175673 2022-09-30 1218       1            0    7      2        0
175674 2022-09-30 1228       1            0    7      1        0
175675 2022-09-30 1241       1            0    7      1        0
175676 2022-09-30 1243       1            0    7      1        0
175677 2022-09-30 1245       1            0    7      1        0
175678 2022-09-30 1246       1            0    7      1        0
175679 2022-09-30 1247       1            0    7      1        0
175680 2022-09-30 1248       1            0    7      2        0
175681 2022-09-30 1249       1            0    7      1        0
175682 2022-09-30 1249       1            0    7      1        0

In [ ]:
selected_DF09 <- selected_DF09 %>% select('평일/주말', '대여구분코드', '성별', '연령대', '이용건수')
selected_DF09

       평일/주말 대여구분코드 성별 연령대 이용건수
1      0         1            NA   0      1
2      0         1            NA   0      1
3      0         1            NA   0      3
4      0         1            NA   0      1
5      0         1            NA   0      3
6      0         1            NA   0      1
7      0         1            NA   0      1
8      0         1            NA   0      2
9      0         1            NA   0      1
10     0         1            NA   0      2
11     0         1            NA   0      1
12     0         1            NA   0      2
13     0         1            NA   0      1
14     0         1            NA   0      1
15     0         1            NA   0      1
16     0         1            NA   0      2
17     0         1            NA   0      1
18     0         1            NA   0      3
19     0         1            NA   0      2
20     0         1            NA   0      1
21     0         1            NA   0      2
22     0         1            NA   0      3
23     0         1            NA   0      1
24     0         1            NA   0      1
25     0         1            NA   0      1
26     0         1            NA   0      2
27     0         1            NA   0      1
28     0         1            NA   0      1
29     0         1            NA   0      1
30     0         1            NA   0      2
⋮      ⋮         ⋮            ⋮    ⋮      ⋮
175653 0         1            0    7      1
175654 0         1            0    7      1
175655 0         1            0    7      1
175656 0         1            0    7      1
175657 0         1            0    7      1
175658 0         1            0    7      1
175659 0         1            0    7      1
175660 0         1            0    7      1
175661 0         1            0    7      1
175662 0         1            0    7      1
175663 0         1            0    7      1
175664 0         1            0    7      1
175665 0         1            0    7      3
175666 0         1            0    7      2
175667 0         1            0    7      1
175668 0         1            0    7      1
175669 0         1            0    7      1
175670 0         1            0    7      1
175671 0         1            0    7      1
175672 0         1            0    7      5
175673 0         1            0    7      2
175674 0         1            0    7      1
175675 0         1            0    7      1
175676 0         1            0    7      1
175677 0         1            0    7      1
175678 0         1            0    7      1
175679 0         1            0    7      1
175680 0         1            0    7      2
175681 0         1            0    7      1
175682 0         1            0    7      1

In [ ]:
summarized_data_09 <- selected_DF09 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data_09

   대여일자   이용건수_합계
1  2022-09-01 15942
2  2022-09-02 16656
3  2022-09-03 15902
4  2022-09-04  3815
5  2022-09-05   391
6  2022-09-06 12562
7  2022-09-07 15768
8  2022-09-08 16461
9  2022-09-09 12017
10 2022-09-10 10301
11 2022-09-11 10019
12 2022-09-12 14818
13 2022-09-13 14292
14 2022-09-14 15801
15 2022-09-15 15833
16 2022-09-16 10773
17 2022-09-17 14211
18 2022-09-18 14118
19 2022-09-19 15710
20 2022-09-20 16667
21 2022-09-21 16302
22 2022-09-22 16171
23 2022-09-23 15743
24 2022-09-24 17244
25 2022-09-25 15638
26 2022-09-26 16438
27 2022-09-27 16622
28 2022-09-28 16924
29 2022-09-29 16342
30 2022-09-30 17501

## **10월 전처리**

In [ ]:
#https://drive.google.com/file/d/1i_FcB4v9OB3skmhy1rh95-BN7zfGE8Fm/view?usp=sharing
system("gdown --id 1i_FcB4v9OB3skmhy1rh95-BN7zfGE8Fm")
system("ls",TRUE)

 [1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [2] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [3] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [4] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [5] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [6] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [7] "서울특별시 공공자전거 이용정보(일별)_22.04.csv"
 [8] "서울특별시 공공자전거 이용정보(일별)_22.05.csv"
 [9] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.05.csv"
[10] "서울특별시 공공자전거 이용정보(일별)_22.06.csv"
[11] "서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[12] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[13] "서울특별시 공공자전거 이용정보(일별)_22.08.csv"
[14] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.08.csv"
[15] "서울특별시 공공자전거 이용정보(일별)_2209.csv"
[16] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.09.csv"
[17] "서울특별시 공공자전거 이용정보(일별)_2210.csv"
[18] "sample_data"

In [ ]:
DF10<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_2210.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF10

Rows: 2022901 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): 대여소번호, 대여소, 대여구분코드, 성별, 연령대, 운동량, 탄소량
dbl  (3): 이용건수, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        대여일자   대여소번호 대여소                            대여구분코드
1       2022-10-01 00108      108. 서교동 사거리                정기권
2       2022-10-01 00729      729. 서부식자재마트 건너편        정기권
3       2022-10-01 00729      729. 서부식자재마트 건너편        정기권
4       2022-10-01 00731      731. 서울시 도로환경관리센터      정기권
5       2022-10-01 00733      733. 신정이펜하우스314동          정기권
6       2022-10-01 00735      735. 영도초등학교                 정기권
7       2022-10-01 00736      736. 오솔길공원                   정기권
8       2022-10-01 00739      739. 신월사거리                   정기권
9       2022-10-01 00740      740. 으뜸공원                     정기권
10      2022-10-01 00746      746. 목동2단지 상가               정기권
11      2022-10-01 00747      747. 목동3단지 상가               정기권
12      2022-10-01 00946      946. 독바위역                     정기권
13      2022-10-01 00947      947. 연신내 선일하이츠빌 정류소   정기권
14      2022-10-01 00949      949. 연신내역 1번 출구            정기권
15      2022-10-01 00952      952. 서울연신중학교               정기권
16      2022-10-01 01029      1029. 성내어울터                  정기권
17      2022-10-01 01030      1030. 미호 플랜트 앞              정기권
18      2022-10-01 01031      1031. 올림픽로 836(아리수로)      정기권
19      2022-10-01 01034      1034. 고덕동 래미안 힐스테이트    정기권
20      2022-10-01 01035      1035. 고덕역 4번출구              정기권
21      2022-10-01 01044      1044. 굽은다리역                  정기권
22      2022-10-01 01150      1150. 송정역 1번출구              정기권
23      2022-10-01 01151      1151. 마곡역1번출구               정기권
24      2022-10-01 01153      1153. 발산역 1번, 9번 인근 대여소 정기권
25      2022-10-01 01155      1155. 기쁜우리복지관              정기권
26      2022-10-01 01256      1256. 문정현대아파트 교차로       정기권
27      2022-10-01 01268      1268. 몽촌토성역 1번출구 옆       정기권
28      2022-10-01 01271      1271. 송파도서관                  정기권
29      2022-10-01 00512      512. 뚝섬역 1번 출구 옆           정기권
30      2022-10-01 01442      1442. 중랑구 중소기업 창업센터    정기권
⋮       ⋮          ⋮          ⋮                                 ⋮
2022872 2022-10-31 01248      1248. 방이초등학교                정기권
2022873 2022-10-31 01249      1249. 아주중학교건너편            정기권
2022874 2022-10-31 01249      1249. 아주중학교건너편            정기권
2022875 2022-10-31 01625      1625. 상계역(4번출구)             정기권
2022876 2022-10-31 01627      1627. 수락산역 4번출구            정기권
2022877 2022-10-31 01706      1706. 방학동우체국 건너편         정기권
2022878 2022-10-31 01914      1914. 대림역4번출구               정기권
2022879 2022-10-31 01925      1925. 동양미래대학교 정문 옆      정기권
2022880 2022-10-31 01931      1931. 개봉역2번출구 A             정기권
2022881 2022-10-31 02032      2032. 이수역 11번출구쪽           정기권
2022882 2022-10-31 02026      2026. 흑석역 4번출구              정기권
2022883 2022-10-31 01221      1221. 삼전역 4번출구              정기권
2022884 2022-10-31 02264      2264. 이수역 1번출구              정기권
2022885 2022-10-31 01955      1955. 디지털입구 교차로           정기권
2022886 2022-10-31 01955      1955. 디지털입구 교차로           정기권
2022887 2022-10-31 02351      2351. 청소년수련관(수영장)앞      정기권
2022888 2022-10-31 00826      826. 서울역 서부교차로2           정기권
2022889 2022-10-31 01501      1501. 미아역 3번,4번 출구 사이    정기권
2022890 2022-10-31 02360      2360. 도곡1동 주민센터 교차로     정기권
2022891 2022-10-31 01642      1642. 서울여대 남문               정기권
2022892 2022-10-31 02111      2111. 서울대입구역 1번출구        정기권
2022893 2022-10-31 00591      591. 건국대학교 (행정관)          정기권
2022894 2022-10-31 00592      592. 건국대학교 학생회관          정기권
2022895 2022-10-31 00391      391. 시립미술관                   정기권
2022896 2022-10-31 00450      450. 효자동 삼거리                정기권
2022897 2022-10-31 03500      3500. 군자역2번출구               정기권
2022898 2022-10-31 03502      3502. 중곡역 1번출구              정기권
2022899 2022-10-31 00502      502. 뚝섬유원지역 1번출구 앞      정기권
2022900 2022-10-31 00723      723. SBS방송국                    정기권
2022901 2022-10-31 00726      726. 목동3단지 시내버스정류장     정기권
        성별 연령대 이용건수 운동량  탄소량 이동거리(M) 이용시간(분)
1       NA   ~10대  1        58.21   0.49    2100.00     22
2       NA   ~10대  1        56.28   0.52    2256.02     16
3       NA   ~10대  1        50.29   0.35    1530.00     14
4       NA   ~10대  2        36.84   0.40    1733.11     13
5       NA   ~10대  2        140.22  1.19    5131.70     32
6       NA   ~10대  6        240.26  2.39   10267.77    116
7       NA   ~10대  3        187.86  1.50    6472.58     77
8       NA   ~10대  1        50.68   0.55    2369.94     18
9       NA   ~10대  1        89.97   0.66    2840.00     18
10      NA   ~10대  6        172.83  1.84    7906.64     56
11      NA   ~10대  3        70.84   0.63    2749.97     20
12      NA   ~10대  1        28.56   0.25    1060.46      6
13      NA   ~10대  1        30.65   0.30    1290.00      4
14      NA   ~10대  1        118.92  1.07    4620.00     41
15      NA   ~10대  1        14.93   0.13     580.00      2
16      NA   ~10대  2        103.61  0.97    4188.23     20
17      NA   ~10대  1        31.79   0.30    1294.63      7
18      NA   ~10대  1        66.56   0.49    2100.90     15
19      NA   ~10대  1        67.14   0.20     847.74      7
20      NA   ~10대  2        39.67   0.40    1724.24     20
21      NA   ~10대  3        111.09  0.98    4206.79     59
22      NA   ~10대  2        45.11   0.48    2064.70     13
23      NA   ~10대  2        20.42   0.21     916.21      7
24      NA   ~10대  1        92.31   0.60    2590.00     12
25      NA   ~10대  3        101.25  0.96    4123.92     75
26      NA   ~10대  1        13.99   0.13     570.00      4
27      NA   ~10대  1        70.60   0.64    2742.64     24
28      NA   ~10대  1        63.31   0.57    2459.60     14
29      NA   ~10대  1        152.36  1.75    7544.20     53
30      NA   ~10대  1        27.78   0.41    1753.86     10
⋮       ⋮    ⋮      ⋮        ⋮       ⋮      ⋮           ⋮
2022872 M    기타   2        215.64  1.33    5755.14    117
2022873 M    기타   1        22.94   0.18     772.23      3
2022874 M    기타   1        19.06   0.18     763.97      3
2022875 M    기타   5        484.62  3.85   16582.45    173
2022876 M    기타   1        34.90   0.32    1376.97     20
2022877 M    기타   2        226.93  1.40    6032.27     41
2022878 M    기타   4        1285.10 9.04   38986.71    269
2022879 M    기타   2        163.56  1.48    6354.21     28
2022880 M    기타   2        93.86   0.68    2910.00     23
2022881 M    기타   2        43.23   0.40    1690.00     12
2022882 M    기타   2        69.13   0.65    2770.86     44
2022883 M    기타   1        58.86   0.73    3162.57    153
2022884 M    기타   1        50.84   0.38    1645.91     19
2022885 M    기타   1        11.59   0.11     480.00      1
2022886 M    기타   1        51.00   0.37    1610.00     10
2022887 M    기타   1        86.70   0.77    3317.16     20
2022888 M    기타   3        482.06  4.20   18088.42     79
2022889 M    기타   1        44.48   0.31    1321.42      9
2022890 M    기타   1        6.17    0.04     183.29     19
2022891 M    기타   3        180.70  1.56    6763.41     42
2022892 M    기타   1        73.56   0.65    2814.63     43
2022893 M    기타   1        48.11   0.36    1557.47     99
2022894 M    기타   2        65.17   0.55    2351.18     21
2022895 M    기타   1        106.36  0.69    2984.39     63
2022896 M    기타   1        62.91   0.61    2647.86     17
2022897 M    기타   1        111.79  0.64    2740.71     16
2022898 M    기타   1        10.10   0.08     364.28      1
2022899 M    기타   1        61.13   0.46    1979.15     43
2022900 M    기타   2        210.63  1.92    8260.24     82
2022901 M    기타   1        50.24   0.98    4228.97    100

In [ ]:
DF10$대여소번호 <- as.numeric(DF10$대여소번호)

In [ ]:
f_DF10<- DF10%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897,5751,5752,5753,5760,5756,5758,5759,5761,5763,5764,5765,5766,5767))
f_DF10

       대여일자   대여소번호 대여소
1      2022-10-01 1256       1256. 문정현대아파트 교차로
2      2022-10-01 1268       1268. 몽촌토성역 1번출구 옆
3      2022-10-01 1271       1271. 송파도서관
4      2022-10-01 1275       1275. 거여초등학교 옆
5      2022-10-01 1277       1277. 성내6교
6      2022-10-01 1278       1278. 송파구청 교차로
7      2022-10-01 1282       1282. 송파소방서 맞은편(성내4교)
8      2022-10-01 1286       1286. 위례중앙푸르지오 1단지 앞
9      2022-10-01 1288       1288. 문정중교 사거리
10     2022-10-01 1293       1293. 석촌호수 서호 사거리
11     2022-10-01 1295       1295. 잠실역 8번출구
12     2022-10-01 2611       2611. 송파지역자활센터 뒤
13     2022-10-01 2622       2622. 올림픽공원역 3번출구
14     2022-10-01 2618       2618. 삼전역 1번출구
15     2022-10-01 2620       2620. 송파나루역 4번 출구옆
16     2022-10-01 2642       2642.마천동 성내천 쉼터
17     2022-10-01 2628       2628.문정역 1번출구
18     2022-10-01 2630       2630.서울방이동 고분군
19     2022-10-01 2631       2631.배명고등학교
20     2022-10-01 2632       2632.석촌고분역 2번 출구
21     2022-10-01 2637       2637. 아시아지하보도 14번 출구
22     2022-10-01 2639       2639.석촌역 8번출구
23     2022-10-01 2646       2646.레이크펠리스101동앞
24     2022-10-01 2647       2647.잠실 자전거 수리센터 앞
25     2022-10-01 4465       4465. 건영아파트앞 사거리
26     2022-10-01 4467       4467. 한림연예예술고등학교
27     2022-10-01 4468       4468. 가락1동주민센터
28     2022-10-01 4469       4469. 거여동 어울림아파트  102동앞
29     2022-10-01 4478       4478. 문정근린공원2
30     2022-10-01 4479       4479. 문정중학교
⋮      ⋮          ⋮          ⋮
177078 2022-10-31 4868       4868. 석촌호수 서호 남단
177079 2022-10-31 4870       4870. 몽촌토성역 3번 출구
177080 2022-10-31 4873       4873. 개롱역사거리 2번 출구
177081 2022-10-31 4883       4883. 위례포레샤인18단지 1812동
177082 2022-10-31 4889       4889. 마천역 1번 출구 인근②
177083 2022-10-31 4893       4893. 문정법조단지12
177084 2022-10-31 4884       4884. H비즈니스파크
177085 2022-10-31 4891       4891. 위례포레샤인17단지 위례대로 방면
177086 2022-10-31 5753       5753. 호반써밋
177087 2022-10-31 5758       5758. 올림픽선수기자촌아파트 123동 근처
177088 2022-10-31 1206       1206. 9호선종합운동장역 9번출구
177089 2022-10-31 1208       1208. 풍납현대아파트쉼터
177090 2022-10-31 1209       1209. 잠실나루역 (2번 출구 쪽)
177091 2022-10-31 1215       1215. 올림픽공원역 1번출구 앞
177092 2022-10-31 1224       1224. 아시아지하보도 2번 출구
177093 2022-10-31 1232       1232. 잠실주공 521동 건너편
177094 2022-10-31 1235       1235. 잠실트리지움310동 옆
177095 2022-10-31 1203       1203. 밀리아나2빌딩 앞
177096 2022-10-31 1201       1201. 가락시장역 3번 출구
177097 2022-10-31 1231       1231. 잠실역 6번출구
177098 2022-10-31 1210       1210. 롯데월드타워(잠실역2번출구 쪽)
177099 2022-10-31 1227       1227. 거여역 8번출구 뒤
177100 2022-10-31 1228       1228. 마천사거리
177101 2022-10-31 1240       1240. 문정 법조단지4
177102 2022-10-31 1243       1243. 문정 법조단지7
177103 2022-10-31 1244       1244. 문정 법조단지8
177104 2022-10-31 1245       1245. 문정 법조단지9
177105 2022-10-31 1248       1248. 방이초등학교
177106 2022-10-31 1249       1249. 아주중학교건너편
177107 2022-10-31 1249       1249. 아주중학교건너편
       대여구분코드 성별 연령대 이용건수 운동량  탄소량 이동거리(M)
1      정기권       NA   ~10대  1        13.99   0.13    570.00
2      정기권       NA   ~10대  1        70.60   0.64   2742.64
3      정기권       NA   ~10대  1        63.31   0.57   2459.60
4      정기권       NA   ~10대  1        24.50   0.16    695.11
5      정기권       NA   ~10대  1        14.42   0.16    700.42
6      정기권       NA   ~10대  2        55.53   0.46   1974.99
7      정기권       NA   ~10대  1        18.55   0.18    780.66
8      정기권       NA   ~10대  1        60.37   0.54   2345.19
9      정기권       NA   ~10대  2        216.26  1.95   8401.90
10     정기권       NA   ~10대  1        37.73   0.34   1465.64
11     정기권       NA   ~10대  1        116.86  1.10   4759.50
12     정기권       NA   ~10대  2        43.36   0.34   1460.00
13     정기권       NA   ~10대  2        71.76   0.58   2479.63
14     정기권       NA   ~10대  1        30.37   0.27   1180.00
15     정기권       NA   ~10대  2        102.83  1.11   4787.58
16     정기권       NA   ~10대  1        33.48   0.22    950.00
17     정기권       NA   ~10대  2        28.27   0.33   1400.00
18     정기권       NA   ~10대  1        118.29  0.85   3642.70
19     정기권       NA   ~10대  1        68.89   0.62   2676.38
20     정기권       NA   ~10대  2        84.11   0.84   3600.00
21     정기권       NA   ~10대  3        132.63  1.17   5020.35
22     정기권       NA   ~10대  1        17.26   0.16    670.38
23     정기권       NA   ~10대  1        33.24   0.33   1422.53
24     정기권       NA   ~10대  1        13.80   0.16    670.00
25     정기권       NA   ~10대  1        74.31   0.76   3292.20
26     정기권       NA   ~10대  2        40.59   0.42   1790.10
27     정기권       NA   ~10대  1        35.86   0.28   1207.52
28     정기권       NA   ~10대  1        16.87   0.16    687.19
29     정기권       NA   ~10대  3        61.02   0.58   2530.00
30     정기권       NA   ~10대  1        24.03   0.29   1238.27
⋮      ⋮            ⋮    ⋮      ⋮        ⋮       ⋮      ⋮
177078 정기권       M    기타   1        37.72   0.29    1270.00
177079 정기권       M    기타   2        56.54   0.49    2106.84
177080 정기권       M    기타   1        22.82   0.18     778.63
177081 정기권       M    기타   1        51.58   0.41    1760.00
177082 정기권       M    기타   1        26.01   0.21     887.47
177083 정기권       M    기타   3        1193.58 7.77   33490.00
177084 정기권       M    기타   2        111.66  0.85    3659.43
177085 정기권       M    기타   2        340.64  2.96   12760.00
177086 정기권       M    기타   1        456.84  3.62   15589.73
177087 정기권       M    기타   1        36.42   0.28    1210.00
177088 정기권       M    기타   1        20.05   0.16     674.92
177089 정기권       M    기타   1        137.98  1.30    5620.00
177090 정기권       M    기타   3        270.61  1.96    8462.25
177091 정기권       M    기타   3        162.51  1.55    6658.62
177092 정기권       M    기타   2        104.74  0.71    3050.00
177093 정기권       M    기타   1        44.47   0.43    1871.72
177094 정기권       M    기타   1        36.84   0.36    1550.60
177095 정기권       M    기타   1        68.40   0.51    2214.39
177096 정기권       M    기타   1        95.82   0.76    3270.00
177097 정기권       M    기타   1        19.31   0.17     750.00
177098 정기권       M    기타   2        148.32  1.10    4743.79
177099 정기권       M    기타   2        132.12  0.85    3682.85
177100 정기권       M    기타   1        355.34  2.19    9445.58
177101 정기권       M    기타   1        182.51  1.65    7090.64
177102 정기권       M    기타   2        520.39  4.30   18515.84
177103 정기권       M    기타   2        112.04  0.86    3728.94
177104 정기권       M    기타   1        47.49   0.42    1790.00
177105 정기권       M    기타   2        215.64  1.33    5755.14
177106 정기권       M    기타   1        22.94   0.18     772.23
177107 정기권       M    기타   1        19.06   0.18     763.97
       이용시간(분)
1        4
2       24
3       14
4        5
5        3
6       11
7        6
8       11
9       82
10      10
11      34
12      10
13      16
14      13
15      32
16       4
17      10
18      19
19      17
20      69
21      54
22       4
23      39
24       4
25      18
26       9
27       6
28       5
29     126
30       6
⋮      ⋮
177078   9
177079  28
177080   3
177081  10
177082   6
177083 254
177084 127
177085  59
177086  82
177087   4
177088   3
177089  27
177090 133
177091 156
177092  28
177093  76
177094  35
177095  12
177096  25
177097   8
177098  33
177099  19
177100  56
177101  59
177102  83
177103 119
177104   7
177105 117
177106   3
177107   3

In [ ]:
selected_DF10<- f_DF10 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대, 이용건수)
selected_DF10

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수
1      2022-10-01 1256       정기권       NA   ~10대  1
2      2022-10-01 1268       정기권       NA   ~10대  1
3      2022-10-01 1271       정기권       NA   ~10대  1
4      2022-10-01 1275       정기권       NA   ~10대  1
5      2022-10-01 1277       정기권       NA   ~10대  1
6      2022-10-01 1278       정기권       NA   ~10대  2
7      2022-10-01 1282       정기권       NA   ~10대  1
8      2022-10-01 1286       정기권       NA   ~10대  1
9      2022-10-01 1288       정기권       NA   ~10대  2
10     2022-10-01 1293       정기권       NA   ~10대  1
11     2022-10-01 1295       정기권       NA   ~10대  1
12     2022-10-01 2611       정기권       NA   ~10대  2
13     2022-10-01 2622       정기권       NA   ~10대  2
14     2022-10-01 2618       정기권       NA   ~10대  1
15     2022-10-01 2620       정기권       NA   ~10대  2
16     2022-10-01 2642       정기권       NA   ~10대  1
17     2022-10-01 2628       정기권       NA   ~10대  2
18     2022-10-01 2630       정기권       NA   ~10대  1
19     2022-10-01 2631       정기권       NA   ~10대  1
20     2022-10-01 2632       정기권       NA   ~10대  2
21     2022-10-01 2637       정기권       NA   ~10대  3
22     2022-10-01 2639       정기권       NA   ~10대  1
23     2022-10-01 2646       정기권       NA   ~10대  1
24     2022-10-01 2647       정기권       NA   ~10대  1
25     2022-10-01 4465       정기권       NA   ~10대  1
26     2022-10-01 4467       정기권       NA   ~10대  2
27     2022-10-01 4468       정기권       NA   ~10대  1
28     2022-10-01 4469       정기권       NA   ~10대  1
29     2022-10-01 4478       정기권       NA   ~10대  3
30     2022-10-01 4479       정기권       NA   ~10대  1
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮
177078 2022-10-31 4868       정기권       M    기타   1
177079 2022-10-31 4870       정기권       M    기타   2
177080 2022-10-31 4873       정기권       M    기타   1
177081 2022-10-31 4883       정기권       M    기타   1
177082 2022-10-31 4889       정기권       M    기타   1
177083 2022-10-31 4893       정기권       M    기타   3
177084 2022-10-31 4884       정기권       M    기타   2
177085 2022-10-31 4891       정기권       M    기타   2
177086 2022-10-31 5753       정기권       M    기타   1
177087 2022-10-31 5758       정기권       M    기타   1
177088 2022-10-31 1206       정기권       M    기타   1
177089 2022-10-31 1208       정기권       M    기타   1
177090 2022-10-31 1209       정기권       M    기타   3
177091 2022-10-31 1215       정기권       M    기타   3
177092 2022-10-31 1224       정기권       M    기타   2
177093 2022-10-31 1232       정기권       M    기타   1
177094 2022-10-31 1235       정기권       M    기타   1
177095 2022-10-31 1203       정기권       M    기타   1
177096 2022-10-31 1201       정기권       M    기타   1
177097 2022-10-31 1231       정기권       M    기타   1
177098 2022-10-31 1210       정기권       M    기타   2
177099 2022-10-31 1227       정기권       M    기타   2
177100 2022-10-31 1228       정기권       M    기타   1
177101 2022-10-31 1240       정기권       M    기타   1
177102 2022-10-31 1243       정기권       M    기타   2
177103 2022-10-31 1244       정기권       M    기타   2
177104 2022-10-31 1245       정기권       M    기타   1
177105 2022-10-31 1248       정기권       M    기타   2
177106 2022-10-31 1249       정기권       M    기타   1
177107 2022-10-31 1249       정기권       M    기타   1

In [ ]:
selected_DF10$`대여구분코드`<-ifelse(selected_DF10$`대여구분코드`=='정기권',1,0)

In [ ]:
selected_DF10$`성별`<-ifelse(selected_DF10$`성별`=='M',0,ifelse(selected_DF10$`성별`=='F',1,2))

In [ ]:
selected_DF10$`연령대`<-ifelse(selected_DF10$`연령대`=='~10대',0,ifelse(selected_DF10$`연령대`=='20대',1,
ifelse(selected_DF10$`연령대`=='30대',2,ifelse(selected_DF10$`연령대`=='40대',3,ifelse(selected_DF10$`연령대`=='50대',4,
ifelse(selected_DF10$`연령대`=='60대',5,ifelse(selected_DF10$`연령대`=='70대이상',6,7)))))))

In [ ]:
selected_DF10

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수
1      2022-10-01 1256       1            NA   0      1
2      2022-10-01 1268       1            NA   0      1
3      2022-10-01 1271       1            NA   0      1
4      2022-10-01 1275       1            NA   0      1
5      2022-10-01 1277       1            NA   0      1
6      2022-10-01 1278       1            NA   0      2
7      2022-10-01 1282       1            NA   0      1
8      2022-10-01 1286       1            NA   0      1
9      2022-10-01 1288       1            NA   0      2
10     2022-10-01 1293       1            NA   0      1
11     2022-10-01 1295       1            NA   0      1
12     2022-10-01 2611       1            NA   0      2
13     2022-10-01 2622       1            NA   0      2
14     2022-10-01 2618       1            NA   0      1
15     2022-10-01 2620       1            NA   0      2
16     2022-10-01 2642       1            NA   0      1
17     2022-10-01 2628       1            NA   0      2
18     2022-10-01 2630       1            NA   0      1
19     2022-10-01 2631       1            NA   0      1
20     2022-10-01 2632       1            NA   0      2
21     2022-10-01 2637       1            NA   0      3
22     2022-10-01 2639       1            NA   0      1
23     2022-10-01 2646       1            NA   0      1
24     2022-10-01 2647       1            NA   0      1
25     2022-10-01 4465       1            NA   0      1
26     2022-10-01 4467       1            NA   0      2
27     2022-10-01 4468       1            NA   0      1
28     2022-10-01 4469       1            NA   0      1
29     2022-10-01 4478       1            NA   0      3
30     2022-10-01 4479       1            NA   0      1
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮
177078 2022-10-31 4868       1            0    7      1
177079 2022-10-31 4870       1            0    7      2
177080 2022-10-31 4873       1            0    7      1
177081 2022-10-31 4883       1            0    7      1
177082 2022-10-31 4889       1            0    7      1
177083 2022-10-31 4893       1            0    7      3
177084 2022-10-31 4884       1            0    7      2
177085 2022-10-31 4891       1            0    7      2
177086 2022-10-31 5753       1            0    7      1
177087 2022-10-31 5758       1            0    7      1
177088 2022-10-31 1206       1            0    7      1
177089 2022-10-31 1208       1            0    7      1
177090 2022-10-31 1209       1            0    7      3
177091 2022-10-31 1215       1            0    7      3
177092 2022-10-31 1224       1            0    7      2
177093 2022-10-31 1232       1            0    7      1
177094 2022-10-31 1235       1            0    7      1
177095 2022-10-31 1203       1            0    7      1
177096 2022-10-31 1201       1            0    7      1
177097 2022-10-31 1231       1            0    7      1
177098 2022-10-31 1210       1            0    7      2
177099 2022-10-31 1227       1            0    7      2
177100 2022-10-31 1228       1            0    7      1
177101 2022-10-31 1240       1            0    7      1
177102 2022-10-31 1243       1            0    7      2
177103 2022-10-31 1244       1            0    7      2
177104 2022-10-31 1245       1            0    7      1
177105 2022-10-31 1248       1            0    7      2
177106 2022-10-31 1249       1            0    7      1
177107 2022-10-31 1249       1            0    7      1

In [ ]:
selected_DF10$'평일/주말' <- ifelse(selected_DF10$대여일자 %in% date$date_time, date$weekend[match(selected_DF10$대여일자, date$date_time)], 2)
selected_DF10

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수 평일/주말
1      2022-10-01 1256       1            NA   0      1        1
2      2022-10-01 1268       1            NA   0      1        1
3      2022-10-01 1271       1            NA   0      1        1
4      2022-10-01 1275       1            NA   0      1        1
5      2022-10-01 1277       1            NA   0      1        1
6      2022-10-01 1278       1            NA   0      2        1
7      2022-10-01 1282       1            NA   0      1        1
8      2022-10-01 1286       1            NA   0      1        1
9      2022-10-01 1288       1            NA   0      2        1
10     2022-10-01 1293       1            NA   0      1        1
11     2022-10-01 1295       1            NA   0      1        1
12     2022-10-01 2611       1            NA   0      2        1
13     2022-10-01 2622       1            NA   0      2        1
14     2022-10-01 2618       1            NA   0      1        1
15     2022-10-01 2620       1            NA   0      2        1
16     2022-10-01 2642       1            NA   0      1        1
17     2022-10-01 2628       1            NA   0      2        1
18     2022-10-01 2630       1            NA   0      1        1
19     2022-10-01 2631       1            NA   0      1        1
20     2022-10-01 2632       1            NA   0      2        1
21     2022-10-01 2637       1            NA   0      3        1
22     2022-10-01 2639       1            NA   0      1        1
23     2022-10-01 2646       1            NA   0      1        1
24     2022-10-01 2647       1            NA   0      1        1
25     2022-10-01 4465       1            NA   0      1        1
26     2022-10-01 4467       1            NA   0      2        1
27     2022-10-01 4468       1            NA   0      1        1
28     2022-10-01 4469       1            NA   0      1        1
29     2022-10-01 4478       1            NA   0      3        1
30     2022-10-01 4479       1            NA   0      1        1
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮        ⋮
177078 2022-10-31 4868       1            0    7      1        0
177079 2022-10-31 4870       1            0    7      2        0
177080 2022-10-31 4873       1            0    7      1        0
177081 2022-10-31 4883       1            0    7      1        0
177082 2022-10-31 4889       1            0    7      1        0
177083 2022-10-31 4893       1            0    7      3        0
177084 2022-10-31 4884       1            0    7      2        0
177085 2022-10-31 4891       1            0    7      2        0
177086 2022-10-31 5753       1            0    7      1        0
177087 2022-10-31 5758       1            0    7      1        0
177088 2022-10-31 1206       1            0    7      1        0
177089 2022-10-31 1208       1            0    7      1        0
177090 2022-10-31 1209       1            0    7      3        0
177091 2022-10-31 1215       1            0    7      3        0
177092 2022-10-31 1224       1            0    7      2        0
177093 2022-10-31 1232       1            0    7      1        0
177094 2022-10-31 1235       1            0    7      1        0
177095 2022-10-31 1203       1            0    7      1        0
177096 2022-10-31 1201       1            0    7      1        0
177097 2022-10-31 1231       1            0    7      1        0
177098 2022-10-31 1210       1            0    7      2        0
177099 2022-10-31 1227       1            0    7      2        0
177100 2022-10-31 1228       1            0    7      1        0
177101 2022-10-31 1240       1            0    7      1        0
177102 2022-10-31 1243       1            0    7      2        0
177103 2022-10-31 1244       1            0    7      2        0
177104 2022-10-31 1245       1            0    7      1        0
177105 2022-10-31 1248       1            0    7      2        0
177106 2022-10-31 1249       1            0    7      1        0
177107 2022-10-31 1249       1            0    7      1        0

In [ ]:
selected_DF10 <- selected_DF10 %>% select('평일/주말', '대여구분코드', '성별', '연령대', '이용건수')
selected_DF10

       평일/주말 대여구분코드 성별 연령대 이용건수
1      1         1            NA   0      1
2      1         1            NA   0      1
3      1         1            NA   0      1
4      1         1            NA   0      1
5      1         1            NA   0      1
6      1         1            NA   0      2
7      1         1            NA   0      1
8      1         1            NA   0      1
9      1         1            NA   0      2
10     1         1            NA   0      1
11     1         1            NA   0      1
12     1         1            NA   0      2
13     1         1            NA   0      2
14     1         1            NA   0      1
15     1         1            NA   0      2
16     1         1            NA   0      1
17     1         1            NA   0      2
18     1         1            NA   0      1
19     1         1            NA   0      1
20     1         1            NA   0      2
21     1         1            NA   0      3
22     1         1            NA   0      1
23     1         1            NA   0      1
24     1         1            NA   0      1
25     1         1            NA   0      1
26     1         1            NA   0      2
27     1         1            NA   0      1
28     1         1            NA   0      1
29     1         1            NA   0      3
30     1         1            NA   0      1
⋮      ⋮         ⋮            ⋮    ⋮      ⋮
177078 0         1            0    7      1
177079 0         1            0    7      2
177080 0         1            0    7      1
177081 0         1            0    7      1
177082 0         1            0    7      1
177083 0         1            0    7      3
177084 0         1            0    7      2
177085 0         1            0    7      2
177086 0         1            0    7      1
177087 0         1            0    7      1
177088 0         1            0    7      1
177089 0         1            0    7      1
177090 0         1            0    7      3
177091 0         1            0    7      3
177092 0         1            0    7      2
177093 0         1            0    7      1
177094 0         1            0    7      1
177095 0         1            0    7      1
177096 0         1            0    7      1
177097 0         1            0    7      1
177098 0         1            0    7      2
177099 0         1            0    7      2
177100 0         1            0    7      1
177101 0         1            0    7      1
177102 0         1            0    7      2
177103 0         1            0    7      2
177104 0         1            0    7      1
177105 0         1            0    7      2
177106 0         1            0    7      1
177107 0         1            0    7      1

## **11월 전처리**

In [ ]:
#https://drive.google.com/file/d/1v3-HFpDhcxC2637f87s1b6-3ncglBFVW/view?usp=sharing
system("gdown --id 1v3-HFpDhcxC2637f87s1b6-3ncglBFVW")
system("ls",TRUE)

 [1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [2] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [3] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [4] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [5] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [6] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [7] "서울특별시 공공자전거 이용정보(일별)_22.04.csv"
 [8] "서울특별시 공공자전거 이용정보(일별)_22.05.csv"
 [9] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.05.csv"
[10] "서울특별시 공공자전거 이용정보(일별)_22.06.csv"
[11] "서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[12] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[13] "서울특별시 공공자전거 이용정보(일별)_22.08.csv"
[14] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.08.csv"
[15] "서울특별시 공공자전거 이용정보(일별)_2209.csv"
[16] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.09.csv"
[17] "서울특별시 공공자전거 이용정보(일별)_2210.csv"
[18] "서울특별시 공공자전거 이용정보(일별)_2211.csv"
[19] "sample_data"

In [ ]:
DF11<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_2211.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF11

Rows: 1848895 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): 대여소번호, 대여소, 대여구분코드, 성별, 연령대, 운동량, 탄소량
dbl  (3): 이용건수, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        대여일자   대여소번호 대여소
1       2022-11-01 00731      731. 서울시 도로환경관리센터
2       2022-11-01 00732      732. 신월중학교
3       2022-11-01 00733      733. 신정이펜하우스314동
4       2022-11-01 00735      735. 영도초등학교
5       2022-11-01 00736      736. 오솔길공원
6       2022-11-01 00739      739. 신월사거리
7       2022-11-01 00746      746. 목동2단지 상가
8       2022-11-01 00746      746. 목동2단지 상가
9       2022-11-01 00747      747. 목동3단지 상가
10      2022-11-01 00748      748. 목동운동장
11      2022-11-01 00505      505. 자양사거리 광진아크로텔 앞
12      2022-11-01 00947      947. 연신내 선일하이츠빌 정류소
13      2022-11-01 00950      950. 구산역 2번 출구 예일여고 버스정류장
14      2022-11-01 00952      952. 서울연신중학교
15      2022-11-01 00953      953. 서울연신초등학교
16      2022-11-01 01023      1023. 한국종합기술사옥 앞
17      2022-11-01 01026      1026. 대명초교 입구 교차로
18      2022-11-01 01027      1027. 프라자 아파트 앞
19      2022-11-01 01029      1029. 성내어울터
20      2022-11-01 01036      1036. 고덕동 주양쇼핑
21      2022-11-01 01037      1037. 강일리버파크 6단지
22      2022-11-01 00509      509. 이마트 버스정류소 옆
23      2022-11-01 01044      1044. 굽은다리역
24      2022-11-01 01150      1150. 송정역 1번출구
25      2022-11-01 01151      1151. 마곡역1번출구
26      2022-11-01 01152      1152. 마곡역교차로
27      2022-11-01 01152      1152. 마곡역교차로
28      2022-11-01 01153      1153. 발산역 1번, 9번 인근 대여소
29      2022-11-01 01155      1155. 기쁜우리복지관
30      2022-11-01 01251      1251. 석촌역 2번출구
⋮       ⋮          ⋮          ⋮
1848866 2022-11-30 01227      1227. 거여역 8번출구 뒤
1848867 2022-11-30 01246      1246. 문정 법조단지10
1848868 2022-11-30 01249      1249. 아주중학교건너편
1848869 2022-11-30 01249      1249. 아주중학교건너편
1848870 2022-11-30 00412      412. DMC산학협력연구센터 앞
1848871 2022-11-30 01328      1328. 월곡역 3번출구
1848872 2022-11-30 01602      1602. 광운대역 앞
1848873 2022-11-30 01625      1625. 상계역(4번출구)
1848874 2022-11-30 01706      1706. 방학동우체국 건너편
1848875 2022-11-30 01914      1914. 대림역4번출구
1848876 2022-11-30 01925      1925. 동양미래대학교 정문 옆
1848877 2022-11-30 01931      1931. 개봉역2번출구 A
1848878 2022-11-30 02211      2211. 서초구립반포도서관 앞
1848879 2022-11-30 01221      1221. 삼전역 4번출구
1848880 2022-11-30 01955      1955. 디지털입구 교차로
1848881 2022-11-30 00414      414. 상암동주민센터 옆
1848882 2022-11-30 01305      1305. 성북구청
1848883 2022-11-30 02360      2360. 도곡1동 주민센터 교차로
1848884 2022-11-30 02350      2350. 래미안그레이튼102동앞
1848885 2022-11-30 00500      500. 어린이대공원역 3번출구 앞
1848886 2022-11-30 00592      592. 건국대학교 학생회관
1848887 2022-11-30 00391      391. 시립미술관
1848888 2022-11-30 00501      501. 광진구의회 앞
1848889 2022-11-30 00593      593.자양중앙나들목
1848890 2022-11-30 03501      3501. 광진구청 앞
1848891 2022-11-30 03501      3501. 광진구청 앞
1848892 2022-11-30 00424      424. 롯데하이마트 (상암월드컵점)
1848893 2022-11-30 00722      722. 경서농협 버스정류장(우리은행신정동지점방향)
1848894 2022-11-30 00723      723. SBS방송국
1848895 2022-11-30 00725      725. 양강중학교앞 교차로
        대여구분코드 성별 연령대 이용건수 운동량 탄소량 이동거리(M)
1       정기권       NA   ~10대  1        22.66  0.18    773.34
2       정기권       NA   ~10대  1        32.65  0.29   1268.47
3       정기권       NA   ~10대  2        77.39  0.68   2923.00
4       정기권       NA   ~10대  3        76.55  0.93   4010.88
5       정기권       NA   ~10대  2        80.80  0.63   2711.15
6       정기권       NA   ~10대  2        81.59  0.73   3170.00
7       정기권       NA   ~10대  3        49.82  0.58   2500.61
8       정기권       NA   ~10대  1        73.63  0.86   3718.69
9       정기권       NA   ~10대  1        12.36  0.14    600.00
10      정기권       NA   ~10대  1        23.71  0.19    820.04
11      정기권       NA   ~10대  1        10.10  0.14    593.15
12      정기권       NA   ~10대  1        28.46  0.28   1197.90
13      정기권       NA   ~10대  1        49.99  0.49   2103.79
14      정기권       NA   ~10대  1        9.01   0.08    350.16
15      정기권       NA   ~10대  1        23.76  0.29   1250.00
16      정기권       NA   ~10대  2        91.02  0.84   3600.44
17      정기권       NA   ~10대  1        25.58  0.25   1076.40
18      정기권       NA   ~10대  2        89.30  0.80   3469.15
19      정기권       NA   ~10대  1        49.67  0.47   2023.18
20      정기권       NA   ~10대  2        128.89 1.21   5250.00
21      정기권       NA   ~10대  1        35.73  0.30   1288.90
22      정기권       NA   ~10대  1        20.11  0.18    781.28
23      정기권       NA   ~10대  1        23.70  0.22    950.00
24      정기권       NA   ~10대  1        8.07   0.09    384.71
25      정기권       NA   ~10대  1        10.45  0.10    440.00
26      정기권       NA   ~10대  1        17.08  0.15    634.39
27      정기권       NA   ~10대  1        6.38   0.08    350.00
28      정기권       NA   ~10대  2        41.94  0.43   1847.72
29      정기권       NA   ~10대  1        93.84  0.76   3291.27
30      정기권       NA   ~10대  1        17.82  0.14    600.00
⋮       ⋮            ⋮    ⋮      ⋮        ⋮      ⋮      ⋮
1848866 정기권       M    기타   1        39.67  0.37    1590.00
1848867 정기권       M    기타   1        44.03  0.51    2180.00
1848868 정기권       M    기타   1        20.16  0.16     678.64
1848869 정기권       M    기타   1        22.35  0.20     868.18
1848870 정기권       M    기타   1        24.33  0.19     797.79
1848871 정기권       M    기타   1        191.55 1.60    6910.00
1848872 정기권       M    기타   1        22.39  0.20     870.00
1848873 정기권       M    기타   1        67.92  0.59    2522.37
1848874 정기권       M    기타   1        197.49 1.22    5249.66
1848875 정기권       M    기타   1        30.98  0.21     920.30
1848876 정기권       M    기타   3        312.92 2.53   10952.75
1848877 정기권       M    기타   1        123.55 1.11    4800.00
1848878 정기권       M    기타   1        14.67  0.13     570.00
1848879 정기권       M    기타   1        43.92  0.55    2360.00
1848880 정기권       M    기타   1        37.93  0.34    1473.48
1848881 정기권       M    기타   1        21.84  0.20     848.32
1848882 정기권       M    기타   1        70.71  0.54    2319.08
1848883 정기권       M    기타   2        83.08  0.68    2963.69
1848884 정기권       M    기타   1        17.63  0.14     593.57
1848885 정기권       M    기타   1        47.74  0.32    1370.00
1848886 정기권       M    기타   1        31.09  0.26    1121.68
1848887 정기권       M    기타   1        33.30  0.30    1293.61
1848888 정기권       M    기타   1        11.43  0.09     390.00
1848889 정기권       M    기타   1        25.23  0.21     910.00
1848890 정기권       M    기타   3        221.97 1.44    6227.82
1848891 정기권       M    기타   1        25.58  0.22     950.00
1848892 정기권       M    기타   1        169.92 1.53    6601.57
1848893 정기권       M    기타   1        33.92  0.32    1359.80
1848894 정기권       M    기타   2        484.40 3.56   15314.27
1848895 정기권       M    기타   1        182.99 1.19    5134.35
        이용시간(분)
1       27
2        6
3       13
4       26
5       13
6       16
7       15
8       22
9        3
10       7
11       3
12       6
13      17
14       2
15      12
16      53
17       6
18      21
19      13
20      33
21       8
22       5
23       5
24       3
25       3
26       3
27       4
28      12
29      16
30       6
⋮       ⋮
1848866   7
1848867  13
1848868   2
1848869   4
1848870   6
1848871  31
1848872   4
1848873  93
1848874  86
1848875   4
1848876  58
1848877  22
1848878   3
1848879  85
1848880  32
1848881   6
1848882  11
1848883  25
1848884   3
1848885  54
1848886   7
1848887  11
1848888   3
1848889   6
1848890 110
1848891   4
1848892 119
1848893   9
1848894  50
1848895  56

In [ ]:
DF11$대여소번호 <- as.numeric(DF11$대여소번호)

In [ ]:
f_DF11<-DF11%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897,5751,5752,5753,5760,5756,5758,5759,5761,5763,5764,5765,5766,5767))
f_DF11

       대여일자   대여소번호 대여소
1      2022-11-01 1251       1251. 석촌역 2번출구
2      2022-11-01 1260       1260. 방이동 한양3차아파트 옆
3      2022-11-01 1264       1264. 천호역 10번 출구 앞
4      2022-11-01 1265       1265. 문정동 근린공원
5      2022-11-01 1267       1267. 올림픽공원 남2문 앞
6      2022-11-01 1274       1274. 영파여고 앞
7      2022-11-01 1278       1278. 송파구청 교차로
8      2022-11-01 1293       1293. 석촌호수 서호 사거리
9      2022-11-01 2611       2611. 송파지역자활센터 뒤
10     2022-11-01 2617       2617. 가락삼환아파트 앞
11     2022-11-01 2620       2620. 송파나루역 4번 출구옆
12     2022-11-01 2630       2630.서울방이동 고분군
13     2022-11-01 2632       2632.석촌고분역 2번 출구
14     2022-11-01 2647       2647.잠실 자전거 수리센터 앞
15     2022-11-01 2651       2651.경찰병원역 3번출구 앞
16     2022-11-01 4457       4457. 아산병원 기숙사 부근
17     2022-11-01 4458       4458. 가락2동주민센터 인근
18     2022-11-01 4464       4464. 올림픽공원 북2문
19     2022-11-01 4467       4467. 한림연예예술고등학교
20     2022-11-01 4468       4468. 가락1동주민센터
21     2022-11-01 4475       4475. 송파파인타운 4단지 403동
22     2022-11-01 4478       4478. 문정근린공원2
23     2022-11-01 4481       4481. 올림픽공원 북2문 2
24     2022-11-01 4497       4497. 아시아선수촌아파트 교차로
25     2022-11-01 4864       4864. 송파사거리
26     2022-11-01 4867       4867. 가락대림아파트 앞
27     2022-11-01 4886       4886. 배명고등학교 건너편
28     2022-11-01 5758       5758. 올림픽선수기자촌아파트 123동 근처
29     2022-11-01 5759       5759. 풍납근린공원
30     2022-11-01 1205       1205. 종합운동장역 4번출구
⋮      ⋮          ⋮          ⋮
162854 2022-11-30 2631       2631.배명고등학교
162855 2022-11-30 2639       2639.석촌역 8번출구
162856 2022-11-30 2648       2648.헬리오시티 112동 앞
162857 2022-11-30 2650       2650.위례22단지 2208동 다리앞
162858 2022-11-30 2652       2652.송파 레미니스1단지 102동 앞
162859 2022-11-30 2656       2656.풍납동 아이파크 107동 앞
162860 2022-11-30 4452       4452. 삼성SDS
162861 2022-11-30 4452       4452. 삼성SDS
162862 2022-11-30 4465       4465. 건영아파트앞 사거리
162863 2022-11-30 4480       4480. 가락시장 남1문 사거리
162864 2022-11-30 4854       4854. 가락시장역 2번 출구
162865 2022-11-30 4860       4860. 가락쌍용2차아파트 103동
162866 2022-11-30 4865       4865. 한성백제역 1번출구 뒤
162867 2022-11-30 4868       4868. 석촌호수 서호 남단
162868 2022-11-30 4870       4870. 몽촌토성역 3번 출구
162869 2022-11-30 4873       4873. 개롱역사거리 2번 출구
162870 2022-11-30 4893       4893. 문정법조단지12
162871 2022-11-30 4897       4897. 잠실주공5단지1
162872 2022-11-30 4891       4891. 위례포레샤인17단지 위례대로 방면
162873 2022-11-30 5758       5758. 올림픽선수기자촌아파트 123동 근처
162874 2022-11-30 1206       1206. 9호선종합운동장역 9번출구
162875 2022-11-30 1222       1222. 잠실새내역 5번 출구 뒤
162876 2022-11-30 1224       1224. 아시아지하보도 2번 출구
162877 2022-11-30 1207       1207. 마천중앙시장
162878 2022-11-30 1210       1210. 롯데월드타워(잠실역2번출구 쪽)
162879 2022-11-30 1210       1210. 롯데월드타워(잠실역2번출구 쪽)
162880 2022-11-30 1227       1227. 거여역 8번출구 뒤
162881 2022-11-30 1246       1246. 문정 법조단지10
162882 2022-11-30 1249       1249. 아주중학교건너편
162883 2022-11-30 1249       1249. 아주중학교건너편
       대여구분코드 성별 연령대 이용건수 운동량 탄소량 이동거리(M) 이용시간(분)
1      정기권       NA   ~10대  1        17.82  0.14    600.00      6
2      정기권       NA   ~10대  2        56.22  0.54   2340.00     20
3      정기권       NA   ~10대  2        152.00 1.12   4844.85     27
4      정기권       NA   ~10대  1        3.23   0.04    160.00      1
5      정기권       NA   ~10대  1        79.04  0.56   2434.11     10
6      정기권       NA   ~10대  2        49.92  0.48   2066.61     51
7      정기권       NA   ~10대  1        0.00   0.00      0.10      3
8      정기권       NA   ~10대  1        29.09  0.26   1130.00      9
9      정기권       NA   ~10대  1        17.39  0.14    585.44      4
10     정기권       NA   ~10대  1        17.43  0.16    710.00      7
11     정기권       NA   ~10대  2        64.79  0.72   3070.69     56
12     정기권       NA   ~10대  1        35.30  0.25   1087.03      9
13     정기권       NA   ~10대  1        71.04  0.59   2526.52     13
14     정기권       NA   ~10대  1        49.77  0.45   1933.61     21
15     정기권       NA   ~10대  2        59.02  0.51   2170.16     34
16     정기권       NA   ~10대  2        78.12  0.71   3086.50     26
17     정기권       NA   ~10대  1        87.69  0.58   2488.09     21
18     정기권       NA   ~10대  1        23.42  0.21    910.00      6
19     정기권       NA   ~10대  1        22.83  0.22    930.00      6
20     정기권       NA   ~10대  1        33.73  0.26   1135.79      7
21     정기권       NA   ~10대  1        13.39  0.12    520.37     42
22     정기권       NA   ~10대  2        74.98  0.83   3569.93     23
23     정기권       NA   ~10대  1        29.86  0.39   1675.52     11
24     정기권       NA   ~10대  1        25.88  0.23   1005.55      5
25     정기권       NA   ~10대  1        42.73  0.39   1660.00     16
26     정기권       NA   ~10대  1        24.60  0.24   1035.23      9
27     정기권       NA   ~10대  1        35.86  0.28   1207.52      7
28     정기권       NA   ~10대  2        113.66 0.98   4223.96     24
29     정기권       NA   ~10대  1        14.01  0.14    610.00      4
30     정기권       NA   ~10대  2        83.44  0.75   3241.79     15
⋮      ⋮            ⋮    ⋮      ⋮        ⋮      ⋮      ⋮           ⋮
162854 정기권       M    기타   1        84.55  0.71   3050.00      26
162855 정기권       M    기타   1        23.36  0.25   1072.55       7
162856 정기권       M    기타   1        27.56  0.28   1200.00       7
162857 정기권       M    기타   1        83.32  0.61   2630.00      19
162858 정기권       M    기타   1        75.11  0.71   3059.17      18
162859 정기권       M    기타   3        76.38  0.71   3057.18      32
162860 정기권       M    기타   3        191.22 1.44   6221.73      36
162861 정기권       M    기타   1        12.67  0.11    492.37       3
162862 정기권       M    기타   1        61.61  0.56   2393.59      34
162863 정기권       M    기타   1        15.28  0.13    575.87       5
162864 정기권       M    기타   3        83.38  0.67   2888.64     123
162865 정기권       M    기타   1        28.72  0.17    725.16       6
162866 정기권       M    기타   1        38.58  0.33   1412.03       6
162867 정기권       M    기타   1        67.42  0.53   2270.00       5
162868 정기권       M    기타   1        42.19  0.38   1638.90       9
162869 정기권       M    기타   1        197.43 1.78   7670.00      20
162870 정기권       M    기타   1        25.84  0.20    870.00       4
162871 정기권       M    기타   1        41.98  0.41   1766.73      33
162872 정기권       M    기타   1        31.31  0.30   1275.33       6
162873 정기권       M    기타   1        37.33  0.29   1240.50       6
162874 정기권       M    기타   1        20.20  0.16    680.00       3
162875 정기권       M    기타   1        27.28  0.25   1060.00       8
162876 정기권       M    기타   2        96.20  0.69   2962.51     161
162877 정기권       M    기타   1        19.31  0.17    750.00       6
162878 정기권       M    기타   3        110.96 0.83   3575.45      20
162879 정기권       M    기타   1        18.28  0.16    710.00       4
162880 정기권       M    기타   1        39.67  0.37   1590.00       7
162881 정기권       M    기타   1        44.03  0.51   2180.00      13
162882 정기권       M    기타   1        20.16  0.16    678.64       2
162883 정기권       M    기타   1        22.35  0.20    868.18       4

In [ ]:
selected_DF11 <- f_DF11 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대, 이용건수)
selected_DF11

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수
1      2022-11-01 1251       정기권       NA   ~10대  1
2      2022-11-01 1260       정기권       NA   ~10대  2
3      2022-11-01 1264       정기권       NA   ~10대  2
4      2022-11-01 1265       정기권       NA   ~10대  1
5      2022-11-01 1267       정기권       NA   ~10대  1
6      2022-11-01 1274       정기권       NA   ~10대  2
7      2022-11-01 1278       정기권       NA   ~10대  1
8      2022-11-01 1293       정기권       NA   ~10대  1
9      2022-11-01 2611       정기권       NA   ~10대  1
10     2022-11-01 2617       정기권       NA   ~10대  1
11     2022-11-01 2620       정기권       NA   ~10대  2
12     2022-11-01 2630       정기권       NA   ~10대  1
13     2022-11-01 2632       정기권       NA   ~10대  1
14     2022-11-01 2647       정기권       NA   ~10대  1
15     2022-11-01 2651       정기권       NA   ~10대  2
16     2022-11-01 4457       정기권       NA   ~10대  2
17     2022-11-01 4458       정기권       NA   ~10대  1
18     2022-11-01 4464       정기권       NA   ~10대  1
19     2022-11-01 4467       정기권       NA   ~10대  1
20     2022-11-01 4468       정기권       NA   ~10대  1
21     2022-11-01 4475       정기권       NA   ~10대  1
22     2022-11-01 4478       정기권       NA   ~10대  2
23     2022-11-01 4481       정기권       NA   ~10대  1
24     2022-11-01 4497       정기권       NA   ~10대  1
25     2022-11-01 4864       정기권       NA   ~10대  1
26     2022-11-01 4867       정기권       NA   ~10대  1
27     2022-11-01 4886       정기권       NA   ~10대  1
28     2022-11-01 5758       정기권       NA   ~10대  2
29     2022-11-01 5759       정기권       NA   ~10대  1
30     2022-11-01 1205       정기권       NA   ~10대  2
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮
162854 2022-11-30 2631       정기권       M    기타   1
162855 2022-11-30 2639       정기권       M    기타   1
162856 2022-11-30 2648       정기권       M    기타   1
162857 2022-11-30 2650       정기권       M    기타   1
162858 2022-11-30 2652       정기권       M    기타   1
162859 2022-11-30 2656       정기권       M    기타   3
162860 2022-11-30 4452       정기권       M    기타   3
162861 2022-11-30 4452       정기권       M    기타   1
162862 2022-11-30 4465       정기권       M    기타   1
162863 2022-11-30 4480       정기권       M    기타   1
162864 2022-11-30 4854       정기권       M    기타   3
162865 2022-11-30 4860       정기권       M    기타   1
162866 2022-11-30 4865       정기권       M    기타   1
162867 2022-11-30 4868       정기권       M    기타   1
162868 2022-11-30 4870       정기권       M    기타   1
162869 2022-11-30 4873       정기권       M    기타   1
162870 2022-11-30 4893       정기권       M    기타   1
162871 2022-11-30 4897       정기권       M    기타   1
162872 2022-11-30 4891       정기권       M    기타   1
162873 2022-11-30 5758       정기권       M    기타   1
162874 2022-11-30 1206       정기권       M    기타   1
162875 2022-11-30 1222       정기권       M    기타   1
162876 2022-11-30 1224       정기권       M    기타   2
162877 2022-11-30 1207       정기권       M    기타   1
162878 2022-11-30 1210       정기권       M    기타   3
162879 2022-11-30 1210       정기권       M    기타   1
162880 2022-11-30 1227       정기권       M    기타   1
162881 2022-11-30 1246       정기권       M    기타   1
162882 2022-11-30 1249       정기권       M    기타   1
162883 2022-11-30 1249       정기권       M    기타   1

In [ ]:
selected_DF11$`대여구분코드`<-ifelse(selected_DF11$`대여구분코드`=='정기권',1,0)

In [ ]:
selected_DF11$`성별`<-ifelse(selected_DF11$`성별`=='M',0,ifelse(selected_DF11$`성별`=='F',1,2))

In [ ]:
selected_DF11$`연령대`<-ifelse(selected_DF11$`연령대`=='~10대',0,ifelse(selected_DF11$`연령대`=='20대',1,
ifelse(selected_DF11$`연령대`=='30대',2,ifelse(selected_DF11$`연령대`=='40대',3,ifelse(selected_DF11$`연령대`=='50대',4,
ifelse(selected_DF11$`연령대`=='60대',5,ifelse(selected_DF11$`연령대`=='70대이상',6,7)))))))

In [ ]:
selected_DF11

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수
1      2022-11-01 1251       1            NA   0      1
2      2022-11-01 1260       1            NA   0      2
3      2022-11-01 1264       1            NA   0      2
4      2022-11-01 1265       1            NA   0      1
5      2022-11-01 1267       1            NA   0      1
6      2022-11-01 1274       1            NA   0      2
7      2022-11-01 1278       1            NA   0      1
8      2022-11-01 1293       1            NA   0      1
9      2022-11-01 2611       1            NA   0      1
10     2022-11-01 2617       1            NA   0      1
11     2022-11-01 2620       1            NA   0      2
12     2022-11-01 2630       1            NA   0      1
13     2022-11-01 2632       1            NA   0      1
14     2022-11-01 2647       1            NA   0      1
15     2022-11-01 2651       1            NA   0      2
16     2022-11-01 4457       1            NA   0      2
17     2022-11-01 4458       1            NA   0      1
18     2022-11-01 4464       1            NA   0      1
19     2022-11-01 4467       1            NA   0      1
20     2022-11-01 4468       1            NA   0      1
21     2022-11-01 4475       1            NA   0      1
22     2022-11-01 4478       1            NA   0      2
23     2022-11-01 4481       1            NA   0      1
24     2022-11-01 4497       1            NA   0      1
25     2022-11-01 4864       1            NA   0      1
26     2022-11-01 4867       1            NA   0      1
27     2022-11-01 4886       1            NA   0      1
28     2022-11-01 5758       1            NA   0      2
29     2022-11-01 5759       1            NA   0      1
30     2022-11-01 1205       1            NA   0      2
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮
162854 2022-11-30 2631       1            0    7      1
162855 2022-11-30 2639       1            0    7      1
162856 2022-11-30 2648       1            0    7      1
162857 2022-11-30 2650       1            0    7      1
162858 2022-11-30 2652       1            0    7      1
162859 2022-11-30 2656       1            0    7      3
162860 2022-11-30 4452       1            0    7      3
162861 2022-11-30 4452       1            0    7      1
162862 2022-11-30 4465       1            0    7      1
162863 2022-11-30 4480       1            0    7      1
162864 2022-11-30 4854       1            0    7      3
162865 2022-11-30 4860       1            0    7      1
162866 2022-11-30 4865       1            0    7      1
162867 2022-11-30 4868       1            0    7      1
162868 2022-11-30 4870       1            0    7      1
162869 2022-11-30 4873       1            0    7      1
162870 2022-11-30 4893       1            0    7      1
162871 2022-11-30 4897       1            0    7      1
162872 2022-11-30 4891       1            0    7      1
162873 2022-11-30 5758       1            0    7      1
162874 2022-11-30 1206       1            0    7      1
162875 2022-11-30 1222       1            0    7      1
162876 2022-11-30 1224       1            0    7      2
162877 2022-11-30 1207       1            0    7      1
162878 2022-11-30 1210       1            0    7      3
162879 2022-11-30 1210       1            0    7      1
162880 2022-11-30 1227       1            0    7      1
162881 2022-11-30 1246       1            0    7      1
162882 2022-11-30 1249       1            0    7      1
162883 2022-11-30 1249       1            0    7      1

In [ ]:
write.csv(selected_DF11,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.11.csv",row.names=FALSE, na="")

In [ ]:
selected_DF11$'평일/주말' <- ifelse(selected_DF11$대여일자 %in% date$date_time, date$weekend[match(selected_DF11$대여일자, date$date_time)], 2)
selected_DF11

       대여일자   대여소번호 대여구분코드 성별 연령대 이용건수 평일/주말
1      2022-11-01 1251       1            NA   0      1        0
2      2022-11-01 1260       1            NA   0      2        0
3      2022-11-01 1264       1            NA   0      2        0
4      2022-11-01 1265       1            NA   0      1        0
5      2022-11-01 1267       1            NA   0      1        0
6      2022-11-01 1274       1            NA   0      2        0
7      2022-11-01 1278       1            NA   0      1        0
8      2022-11-01 1293       1            NA   0      1        0
9      2022-11-01 2611       1            NA   0      1        0
10     2022-11-01 2617       1            NA   0      1        0
11     2022-11-01 2620       1            NA   0      2        0
12     2022-11-01 2630       1            NA   0      1        0
13     2022-11-01 2632       1            NA   0      1        0
14     2022-11-01 2647       1            NA   0      1        0
15     2022-11-01 2651       1            NA   0      2        0
16     2022-11-01 4457       1            NA   0      2        0
17     2022-11-01 4458       1            NA   0      1        0
18     2022-11-01 4464       1            NA   0      1        0
19     2022-11-01 4467       1            NA   0      1        0
20     2022-11-01 4468       1            NA   0      1        0
21     2022-11-01 4475       1            NA   0      1        0
22     2022-11-01 4478       1            NA   0      2        0
23     2022-11-01 4481       1            NA   0      1        0
24     2022-11-01 4497       1            NA   0      1        0
25     2022-11-01 4864       1            NA   0      1        0
26     2022-11-01 4867       1            NA   0      1        0
27     2022-11-01 4886       1            NA   0      1        0
28     2022-11-01 5758       1            NA   0      2        0
29     2022-11-01 5759       1            NA   0      1        0
30     2022-11-01 1205       1            NA   0      2        0
⋮      ⋮          ⋮          ⋮            ⋮    ⋮      ⋮        ⋮
162854 2022-11-30 2631       1            0    7      1        0
162855 2022-11-30 2639       1            0    7      1        0
162856 2022-11-30 2648       1            0    7      1        0
162857 2022-11-30 2650       1            0    7      1        0
162858 2022-11-30 2652       1            0    7      1        0
162859 2022-11-30 2656       1            0    7      3        0
162860 2022-11-30 4452       1            0    7      3        0
162861 2022-11-30 4452       1            0    7      1        0
162862 2022-11-30 4465       1            0    7      1        0
162863 2022-11-30 4480       1            0    7      1        0
162864 2022-11-30 4854       1            0    7      3        0
162865 2022-11-30 4860       1            0    7      1        0
162866 2022-11-30 4865       1            0    7      1        0
162867 2022-11-30 4868       1            0    7      1        0
162868 2022-11-30 4870       1            0    7      1        0
162869 2022-11-30 4873       1            0    7      1        0
162870 2022-11-30 4893       1            0    7      1        0
162871 2022-11-30 4897       1            0    7      1        0
162872 2022-11-30 4891       1            0    7      1        0
162873 2022-11-30 5758       1            0    7      1        0
162874 2022-11-30 1206       1            0    7      1        0
162875 2022-11-30 1222       1            0    7      1        0
162876 2022-11-30 1224       1            0    7      2        0
162877 2022-11-30 1207       1            0    7      1        0
162878 2022-11-30 1210       1            0    7      3        0
162879 2022-11-30 1210       1            0    7      1        0
162880 2022-11-30 1227       1            0    7      1        0
162881 2022-11-30 1246       1            0    7      1        0
162882 2022-11-30 1249       1            0    7      1        0
162883 2022-11-30 1249       1            0    7      1        0

In [ ]:
selected_DF11 <- selected_DF11 %>% select('평일/주말', '대여구분코드', '성별', '연령대', '이용건수')
selected_DF11

       평일/주말 대여구분코드 성별 연령대 이용건수
1      0         1            NA   0      1
2      0         1            NA   0      2
3      0         1            NA   0      2
4      0         1            NA   0      1
5      0         1            NA   0      1
6      0         1            NA   0      2
7      0         1            NA   0      1
8      0         1            NA   0      1
9      0         1            NA   0      1
10     0         1            NA   0      1
11     0         1            NA   0      2
12     0         1            NA   0      1
13     0         1            NA   0      1
14     0         1            NA   0      1
15     0         1            NA   0      2
16     0         1            NA   0      2
17     0         1            NA   0      1
18     0         1            NA   0      1
19     0         1            NA   0      1
20     0         1            NA   0      1
21     0         1            NA   0      1
22     0         1            NA   0      2
23     0         1            NA   0      1
24     0         1            NA   0      1
25     0         1            NA   0      1
26     0         1            NA   0      1
27     0         1            NA   0      1
28     0         1            NA   0      2
29     0         1            NA   0      1
30     0         1            NA   0      2
⋮      ⋮         ⋮            ⋮    ⋮      ⋮
162854 0         1            0    7      1
162855 0         1            0    7      1
162856 0         1            0    7      1
162857 0         1            0    7      1
162858 0         1            0    7      1
162859 0         1            0    7      3
162860 0         1            0    7      3
162861 0         1            0    7      1
162862 0         1            0    7      1
162863 0         1            0    7      1
162864 0         1            0    7      3
162865 0         1            0    7      1
162866 0         1            0    7      1
162867 0         1            0    7      1
162868 0         1            0    7      1
162869 0         1            0    7      1
162870 0         1            0    7      1
162871 0         1            0    7      1
162872 0         1            0    7      1
162873 0         1            0    7      1
162874 0         1            0    7      1
162875 0         1            0    7      1
162876 0         1            0    7      2
162877 0         1            0    7      1
162878 0         1            0    7      3
162879 0         1            0    7      1
162880 0         1            0    7      1
162881 0         1            0    7      1
162882 0         1            0    7      1
162883 0         1            0    7      1

In [ ]:
summarized_data_11 <- selected_DF11 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data_11

   대여일자   이용건수_합계
1  2022-11-01 14630
2  2022-11-02 14316
3  2022-11-03 12865
4  2022-11-04 11318
5  2022-11-05 10314
6  2022-11-06 10579
7  2022-11-07 12925
8  2022-11-08 14137
9  2022-11-09 14139
10 2022-11-10 13970
11 2022-11-11 15116
12 2022-11-12  6323
13 2022-11-13  8297
14 2022-11-14 12584
15 2022-11-15 10563
16 2022-11-16 12486
17 2022-11-17 13026
18 2022-11-18 13742
19 2022-11-19 12007
20 2022-11-20 11673
21 2022-11-21 13349
22 2022-11-22 12366
23 2022-11-23 13503
24 2022-11-24 13148
25 2022-11-25 12945
26 2022-11-26  8865
27 2022-11-27  8040
28 2022-11-28  6291
29 2022-11-29  8201
30 2022-11-30  6649

## **12월 전처리**

In [ ]:
#https://drive.google.com/file/d/1Ra0bVrnFImdwuL9JWTNKD1nk5Q4m77KL/view?usp=sharing
system("gdown --id 1Ra0bVrnFImdwuL9JWTNKD1nk5Q4m77KL")
system("ls",TRUE)

 [1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [2] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.01.csv"
 [3] "서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [4] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.02.csv"
 [5] "서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [6] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.03.csv"
 [7] "서울특별시 공공자전거 이용정보(일별)_22.04.csv"
 [8] "서울특별시 공공자전거 이용정보(일별)_22.05.csv"
 [9] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.05.csv"
[10] "서울특별시 공공자전거 이용정보(일별)_22.06.csv"
[11] "서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[12] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.07.csv"
[13] "서울특별시 공공자전거 이용정보(일별)_22.08.csv"
[14] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.08.csv"
[15] "서울특별시 공공자전거 이용정보(일별)_2209.csv"
[16] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.09.csv"
[17] "서울특별시 공공자전거 이용정보(일별)_2210.csv"
[18] "서울특별시 공공자전거 이용정보(일별)_2211.csv"
[19] "전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.11.csv"
[20] "서울특별시 공공자전거 이용정보(일별)_2212.csv"
[21] "sample_data"

In [ ]:
DF12<- read_csv("/content/서울특별시 공공자전거 이용정보(일별)_2212.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
DF12

Rows: 1074746 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): 대여소번호, 대여소, 대여구분코드, 성별, 연령대, 운동량, 탄소량
dbl  (3): 이용건수, 이동거리(M), 이용시간(분)
date (1): 대여일자

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

        대여일자   대여소번호 대여소
1       2022-12-01 00729      729. 서부식자재마트 건너편
2       2022-12-01 00735      735. 영도초등학교
3       2022-12-01 00739      739. 신월사거리
4       2022-12-01 00741      741. 화곡로 입구 교차로
5       2022-12-01 00746      746. 목동2단지 상가
6       2022-12-01 00937      937. 상림마을 롯데캐슬2단지 옆
7       2022-12-01 00950      950. 구산역 2번 출구 예일여고 버스정류장
8       2022-12-01 01023      1023. 한국종합기술사옥 앞
9       2022-12-01 01025      1025. 상일초등학교
10      2022-12-01 01029      1029. 성내어울터
11      2022-12-01 01035      1035. 고덕역 4번출구
12      2022-12-01 01036      1036. 고덕동 주양쇼핑
13      2022-12-01 01044      1044. 굽은다리역
14      2022-12-01 01151      1151. 마곡역1번출구
15      2022-12-01 01152      1152. 마곡역교차로
16      2022-12-01 01153      1153. 발산역 1번, 9번 인근 대여소
17      2022-12-01 01260      1260. 방이동 한양3차아파트 옆
18      2022-12-01 01264      1264. 천호역 10번 출구 앞
19      2022-12-01 01265      1265. 문정동 근린공원
20      2022-12-01 01269      1269. 리센츠아파트
21      2022-12-01 00512      512. 뚝섬역 1번 출구 옆
22      2022-12-01 01274      1274. 영파여고 앞
23      2022-12-01 01442      1442. 중랑구 중소기업 창업센터
24      2022-12-01 01446      1446. 중랑전화국 교차로
25      2022-12-01 01529      1529. 미아동 한국전력공사
26      2022-12-01 01531      1531. 미아사거리 1번 출구
27      2022-12-01 01650      1650. 중계근린공원내
28      2022-12-01 01651      1651. 상계동 우방유쉘아파트 앞
29      2022-12-01 01652      1652. 파르코 앞
30      2022-12-01 01653      1653. 노원역1번출구
⋮       ⋮          ⋮          ⋮
1074717 2022-12-31 02313      2313. 금원빌딩 앞
1074718 2022-12-31 02318      2318. 삼성중앙역4번출구(문화센터더 리빌)
1074719 2022-12-31 02327      2327. 뱅뱅사거리 랜드마크타워 앞
1074720 2022-12-31 02332      2332. 선릉역3번출구
1074721 2022-12-31 00421      421. 마포구청 앞
1074722 2022-12-31 02342      2342. 대청역 1번출구  뒤
1074723 2022-12-31 01117      1117. 등촌5단지아파트 버스정류장
1074724 2022-12-31 01201      1201. 가락시장역 3번 출구
1074725 2022-12-31 01231      1231. 잠실역 6번출구
1074726 2022-12-31 01414      1414. 사가정역 2번출구
1074727 2022-12-31 01430      1430. 중랑구청
1074728 2022-12-31 01630      1630. 수연빌딩 앞
1074729 2022-12-31 00419      419. 홈플러스 앞
1074730 2022-12-31 01936      1936. 개봉역 1번 출구 자전거보관서쪽
1074731 2022-12-31 01227      1227. 거여역 8번출구 뒤
1074732 2022-12-31 01246      1246. 문정 법조단지10
1074733 2022-12-31 01706      1706. 방학동우체국 건너편
1074734 2022-12-31 01914      1914. 대림역4번출구
1074735 2022-12-31 01925      1925. 동양미래대학교 정문 옆
1074736 2022-12-31 02034      2034. 사당역 7번출구쪽
1074737 2022-12-31 01221      1221. 삼전역 4번출구
1074738 2022-12-31 02264      2264. 이수역 1번출구
1074739 2022-12-31 00414      414. 상암동주민센터 옆
1074740 2022-12-31 02156      2156. 신림푸르지오아파트
1074741 2022-12-31 00501      501. 광진구의회 앞
1074742 2022-12-31 03501      3501. 광진구청 앞
1074743 2022-12-31 03502      3502. 중곡역 1번출구
1074744 2022-12-31 00502      502. 뚝섬유원지역 1번출구 앞
1074745 2022-12-31 00426      426. 서울신용보증재단
1074746 2022-12-31 00726      726. 목동3단지 시내버스정류장
        대여구분코드 성별 연령대 이용건수 운동량 탄소량 이동거리(M)
1       정기권       NA   ~10대  1        58.56  0.44   1895.75
2       정기권       NA   ~10대  3        47.52  0.51   2190.00
3       정기권       NA   ~10대  1        13.50  0.14    620.00
4       정기권       NA   ~10대  1        54.67  0.58   2510.00
5       정기권       NA   ~10대  3        64.97  0.73   3170.97
6       정기권       NA   ~10대  1        26.77  0.22    965.80
7       정기권       NA   ~10대  1        55.39  0.54   2331.16
8       정기권       NA   ~10대  1        8.98   0.10    420.00
9       정기권       NA   ~10대  1        13.20  0.14    617.10
10      정기권       NA   ~10대  1        37.68  0.36   1560.00
11      정기권       NA   ~10대  1        56.67  0.61   2650.00
12      정기권       NA   ~10대  1        122.23 0.86   3718.79
13      정기권       NA   ~10대  1        24.17  0.22    938.86
14      정기권       NA   ~10대  1        19.30  0.17    727.60
15      정기권       NA   ~10대  1        14.16  0.13    550.00
16      정기권       NA   ~10대  2        107.70 0.72   3130.00
17      정기권       NA   ~10대  1        15.22  0.14    620.00
18      정기권       NA   ~10대  1        14.26  0.14    600.00
19      정기권       NA   ~10대  1        14.80  0.18    778.78
20      정기권       NA   ~10대  1        18.79  0.17    730.00
21      정기권       NA   ~10대  1        83.90  0.96   4154.10
22      정기권       NA   ~10대  1        19.01  0.15    640.00
23      정기권       NA   ~10대  1        20.39  0.30   1287.54
24      정기권       NA   ~10대  1        36.74  0.36   1572.46
25      정기권       NA   ~10대  1        24.50  0.21    910.00
26      정기권       NA   ~10대  1        114.13 0.76   3275.11
27      정기권       NA   ~10대  2        81.54  0.92   3960.00
28      정기권       NA   ~10대  1        10.82  0.08    350.37
29      정기권       NA   ~10대  1        21.86  0.20    849.18
30      정기권       NA   ~10대  4        110.12 1.04   4472.10
⋮       ⋮            ⋮    ⋮      ⋮        ⋮      ⋮      ⋮
1074717 정기권       M    기타   1        79.15  0.59    2530.00
1074718 정기권       M    기타   1        303.68 1.78    7668.81
1074719 정기권       M    기타   1        43.12  0.33    1432.73
1074720 정기권       M    기타   1        220.55 1.64    7050.00
1074721 정기권       M    기타   1        24.67  0.22     958.29
1074722 정기권       M    기타   1        69.60  0.42    1830.72
1074723 정기권       M    기타   1        28.96  0.17     731.24
1074724 정기권       M    기타   1        62.46  0.47    2022.21
1074725 정기권       M    기타   1        19.32  0.14     610.00
1074726 정기권       M    기타   1        27.20  0.26    1108.05
1074727 정기권       M    기타   1        37.38  0.27    1180.00
1074728 정기권       M    기타   1        63.32  0.57    2460.00
1074729 정기권       M    기타   2        463.62 3.68   15880.00
1074730 정기권       M    기타   1        11.95  0.11     464.09
1074731 정기권       M    기타   1        71.52  0.60    2580.00
1074732 정기권       M    기타   1        227.72 1.91    8215.18
1074733 정기권       M    기타   1        25.66  0.19     810.00
1074734 정기권       M    기타   1        38.35  0.35    1490.00
1074735 정기권       M    기타   3        118.20 1.06    4542.86
1074736 정기권       M    기타   1        24.58  0.20     874.07
1074737 정기권       M    기타   1        43.55  0.54    2340.00
1074738 정기권       M    기타   1        99.36  0.90    3860.00
1074739 정기권       M    기타   1        21.09  0.16     710.00
1074740 정기권       M    기타   1        151.21 1.27    5454.78
1074741 정기권       M    기타   1        77.07  0.61    2630.00
1074742 정기권       M    기타   1        52.78  0.45    1960.00
1074743 정기권       M    기타   1        96.31  0.71    3040.00
1074744 정기권       M    기타   1        34.49  0.31    1340.00
1074745 정기권       M    기타   1        42.47  0.38    1650.00
1074746 정기권       M    기타   2        102.70 0.92    3990.00
        이용시간(분)
1       10
2       12
3        6
4       19
5       20
6       20
7       17
8        4
9        6
10       8
11      20
12      23
13       6
14       3
15       4
16      20
17       3
18       3
19       8
20      16
21      25
22       5
23       8
24      14
25       4
26      21
27      30
28       4
29       6
30      32
⋮       ⋮
1074717  82
1074718  36
1074719  10
1074720 122
1074721  83
1074722  16
1074723   3
1074724  13
1074725   3
1074726  18
1074727   7
1074728 160
1074729 198
1074730   5
1074731  15
1074732  63
1074733   7
1074734   7
1074735  28
1074736   5
1074737  67
1074738  20
1074739   4
1074740  36
1074741  29
1074742  62
1074743  23
1074744   8
1074745  28
1074746  93

In [ ]:
DF12$대여소번호 <- as.numeric(DF12$대여소번호)

In [ ]:
f_DF12<-DF12%>% filter(대여소번호 %in% c(1201,1203,1204,1205,1206,1207,1208,1209,1210,1212,1213,1214,1215,1217,1218,1220,1222,1224,1226,1227,1228,
1229,1230,1231,1232,1233,1235,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1253,1256,1257,1258,1259,1260,1262,1263,1264,
1265,1266,1267,1268,1269,1271,1274,1275,1277,1278,1279,1280,1282,1283,1285,1286,1287,1288,1289,1290,1291,1293,1295,1296,1297,1299,1300,2601,
2605,2606,2608,2609,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2625,2626,2627,2628,2630,2631,2632,2633,2634,2635,2637,
2639,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,4458,4460,4461,4462,4463,4464,4465,4467,
4468,4860,4469,4472,4473,4474,4475,4478,4479,4480,4481,4483,4452,4484,4485,4486,4488,4490,4491,4493,4496,4497,4499,4500,4852,4854,4855,4856,4857,
4453,4454,4456,4457,4859,4862,4863,4864,4865,4867,4868,4870,4871,4869,4872,4873,4874,4875,4876,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,
4889,4891,4892,4893,4895,4896,4897,5751,5752,5753,5760,5756,5758,5759,5761,5763,5764,5765,5766,5767))
f_DF12

      대여일자   대여소번호 대여소                                 대여구분코드
1     2022-12-01 1260       1260. 방이동 한양3차아파트 옆          정기권
2     2022-12-01 1264       1264. 천호역 10번 출구 앞              정기권
3     2022-12-01 1265       1265. 문정동 근린공원                  정기권
4     2022-12-01 1269       1269. 리센츠아파트                     정기권
5     2022-12-01 1274       1274. 영파여고 앞                      정기권
6     2022-12-01 1277       1277. 성내6교                          정기권
7     2022-12-01 1282       1282. 송파소방서 맞은편(성내4교)       정기권
8     2022-12-01 1288       1288. 문정중교 사거리                  정기권
9     2022-12-01 1291       1291. 서울체육고등학교 앞              정기권
10    2022-12-01 1299       1299. 송파소방서 (방이119안전센터)     정기권
11    2022-12-01 2601       2601. 석촌호수 아뜰리에                정기권
12    2022-12-01 2608       2608. 송파구청                         정기권
13    2022-12-01 2611       2611. 송파지역자활센터 뒤              정기권
14    2022-12-01 2615       2615. 테라타워2                        정기권
15    2022-12-01 2644       2644. 성내5교                          정기권
16    2022-12-01 2630       2630.서울방이동 고분군                 정기권
17    2022-12-01 2635       2635.잠실새내역 1번출구                정기권
18    2022-12-01 2651       2651.경찰병원역 3번출구 앞             정기권
19    2022-12-01 4464       4464. 올림픽공원 북2문                 정기권
20    2022-12-01 4465       4465. 건영아파트앞 사거리              정기권
21    2022-12-01 4467       4467. 한림연예예술고등학교             정기권
22    2022-12-01 4467       4467. 한림연예예술고등학교             정기권
23    2022-12-01 4478       4478. 문정근린공원2                    정기권
24    2022-12-01 4479       4479. 문정중학교                       정기권
25    2022-12-01 4491       4491. 장지역 1번출구                   정기권
26    2022-12-01 4852       4852. 서울복합물류 게이트 1            정기권
27    2022-12-01 4860       4860. 가락쌍용2차아파트 103동          정기권
28    2022-12-01 4871       4871. 오금동 대림아파트 정문           정기권
29    2022-12-01 4875       4875. 위례포레샤인13단지               정기권
30    2022-12-01 4891       4891. 위례포레샤인17단지 위례대로 방면 정기권
⋮     ⋮          ⋮          ⋮                                      ⋮
94482 2022-12-31 2621       2621. 한성백제역 2번 출구              정기권
94483 2022-12-31 2634       2634.위례포레샤인아파트 2318동         정기권
94484 2022-12-31 2648       2648.헬리오시티 112동 앞               정기권
94485 2022-12-31 4486       4486. 홈플러스 잠실점                  정기권
94486 2022-12-31 4862       4862. 성내교 남단                      정기권
94487 2022-12-31 5751       5751. 송파여성축구장                   정기권
94488 2022-12-31 1208       1208. 풍납현대아파트쉼터               정기권
94489 2022-12-31 1210       1210. 롯데월드타워(잠실역2번출구 쪽)   정기권
94490 2022-12-31 1275       1275. 거여초등학교 옆                  정기권
94491 2022-12-31 1289       1289. 풍납토성 서성벽터B               정기권
94492 2022-12-31 1295       1295. 잠실역 8번출구                   정기권
94493 2022-12-31 1297       1297. 석촌호수교차로(동호 팔각정 앞)   정기권
94494 2022-12-31 2605       2605. 복정역 1번 출구 앞               정기권
94495 2022-12-31 2608       2608. 송파구청                         정기권
94496 2022-12-31 2617       2617. 가락삼환아파트 앞                정기권
94497 2022-12-31 2622       2622. 올림픽공원역 3번출구             정기권
94498 2022-12-31 2623       2623.석촌동 주민센터                   정기권
94499 2022-12-31 2651       2651.경찰병원역 3번출구 앞             정기권
94500 2022-12-31 2656       2656.풍납동 아이파크 107동 앞          정기권
94501 2022-12-31 4453       4453. 위례중앙푸르지오 201동 앞        정기권
94502 2022-12-31 4460       4460. 올림픽훼미리아파트 112동 앞      정기권
94503 2022-12-31 4480       4480. 가락시장 남1문 사거리            정기권
94504 2022-12-31 4481       4481. 올림픽공원 북2문 2               정기권
94505 2022-12-31 4870       4870. 몽촌토성역 3번 출구              정기권
94506 2022-12-31 4891       4891. 위례포레샤인17단지 위례대로 방면 정기권
94507 2022-12-31 1206       1206. 9호선종합운동장역 9번출구        정기권
94508 2022-12-31 1201       1201. 가락시장역 3번 출구              정기권
94509 2022-12-31 1231       1231. 잠실역 6번출구                   정기권
94510 2022-12-31 1227       1227. 거여역 8번출구 뒤                정기권
94511 2022-12-31 1246       1246. 문정 법조단지10                  정기권
      성별 연령대   이용건수 운동량 탄소량 이동거리(M) 이용시간(분)
1     NA   ~10대    1        15.22  0.14    620.00      3
2     NA   ~10대    1        14.26  0.14    600.00      3
3     NA   ~10대    1        14.80  0.18    778.78      8
4     NA   ~10대    1        18.79  0.17    730.00     16
5     NA   ~10대    1        19.01  0.15    640.00      5
6     NA   ~10대    2        106.15 1.02   4394.56     31
7     NA   ~10대    1        25.35  0.23    984.78      6
8     NA   ~10대    1        7.94   0.08    364.34      3
9     NA   ~10대    1        44.49  0.54   2340.61     27
10    NA   ~10대    1        32.88  0.30   1277.28     11
11    NA   ~10대    1        68.12  0.65   2820.00     20
12    NA   ~10대    1        11.49  0.13    580.19      4
13    NA   ~10대    1        17.82  0.14    600.00      4
14    NA   ~10대    1        69.76  0.80   3454.12     25
15    NA   ~10대    1        9.78   0.12    537.01      2
16    NA   ~10대    1        38.69  0.38   1655.93     12
17    NA   ~10대    1        30.12  0.27   1170.00     10
18    NA   ~10대    1        112.16 0.81   3496.58     45
19    NA   ~10대    1        13.60  0.17    715.24      6
20    NA   ~10대    2        87.38  0.86   3700.00     29
21    NA   ~10대    2        43.51  0.41   1755.85     15
22    NA   ~10대    1        17.37  0.24   1020.00      6
23    NA   ~10대    1        23.78  0.21    923.72     36
24    NA   ~10대    1        13.12  0.12    534.56      3
25    NA   ~10대    1        15.25  0.21    895.30     12
26    NA   ~10대    1        52.25  0.47   2030.00     21
27    NA   ~10대    1        15.92  0.20    873.75      6
28    NA   ~10대    1        65.85  0.48   2053.00     13
29    NA   ~10대    1        19.01  0.15    640.00      9
30    NA   ~10대    1        17.50  0.16    680.00      5
⋮     ⋮    ⋮        ⋮        ⋮      ⋮      ⋮           ⋮
94482 M    70대이상 1        33.53  0.28    1227.03     10
94483 M    70대이상 1        41.70  0.38    1620.00     12
94484 M    70대이상 1        14.45  0.13     561.45      3
94485 M    70대이상 1        40.67  0.34    1467.13     14
94486 M    70대이상 1        297.57 2.81   12120.00    108
94487 M    70대이상 1        28.13  0.24    1029.42      6
94488 M    70대이상 1        55.11  0.50    2174.64    104
94489 M    70대이상 1        280.67 2.19    9450.00    104
94490 M    기타     1        30.34  0.27    1178.79     10
94491 M    기타     1        34.88  0.26    1101.14      6
94492 M    기타     1        117.85 1.06    4578.54     32
94493 M    기타     1        17.48  0.12     519.29      1
94494 M    기타     1        48.12  0.37    1598.72     11
94495 M    기타     1        41.77  0.48    2068.18     17
94496 M    기타     2        455.29 4.27   18420.00     84
94497 M    기타     2        84.66  0.62    2639.26     30
94498 M    기타     2        123.65 0.89    3843.32     29
94499 M    기타     2        95.16  0.62    2670.00     20
94500 M    기타     1        137.34 1.24    5335.74     58
94501 M    기타     1        22.87  0.18     760.00      7
94502 M    기타     1        4.78   0.03     141.95      3
94503 M    기타     2        43.68  0.29    1251.28      8
94504 M    기타     1        75.68  0.63    2730.00     13
94505 M    기타     1        45.82  0.41    1780.00     11
94506 M    기타     1        21.31  0.16     708.20      6
94507 M    기타     1        50.69  0.37    1600.00      9
94508 M    기타     1        62.46  0.47    2022.21     13
94509 M    기타     1        19.32  0.14     610.00      3
94510 M    기타     1        71.52  0.60    2580.00     15
94511 M    기타     1        227.72 1.91    8215.18     63

In [ ]:
selected_DF12 <- f_DF12 %>% select(대여일자, 대여소번호, 대여구분코드, 성별, 연령대, 이용건수)
selected_DF12

      대여일자   대여소번호 대여구분코드 성별 연령대   이용건수
1     2022-12-01 1260       정기권       NA   ~10대    1
2     2022-12-01 1264       정기권       NA   ~10대    1
3     2022-12-01 1265       정기권       NA   ~10대    1
4     2022-12-01 1269       정기권       NA   ~10대    1
5     2022-12-01 1274       정기권       NA   ~10대    1
6     2022-12-01 1277       정기권       NA   ~10대    2
7     2022-12-01 1282       정기권       NA   ~10대    1
8     2022-12-01 1288       정기권       NA   ~10대    1
9     2022-12-01 1291       정기권       NA   ~10대    1
10    2022-12-01 1299       정기권       NA   ~10대    1
11    2022-12-01 2601       정기권       NA   ~10대    1
12    2022-12-01 2608       정기권       NA   ~10대    1
13    2022-12-01 2611       정기권       NA   ~10대    1
14    2022-12-01 2615       정기권       NA   ~10대    1
15    2022-12-01 2644       정기권       NA   ~10대    1
16    2022-12-01 2630       정기권       NA   ~10대    1
17    2022-12-01 2635       정기권       NA   ~10대    1
18    2022-12-01 2651       정기권       NA   ~10대    1
19    2022-12-01 4464       정기권       NA   ~10대    1
20    2022-12-01 4465       정기권       NA   ~10대    2
21    2022-12-01 4467       정기권       NA   ~10대    2
22    2022-12-01 4467       정기권       NA   ~10대    1
23    2022-12-01 4478       정기권       NA   ~10대    1
24    2022-12-01 4479       정기권       NA   ~10대    1
25    2022-12-01 4491       정기권       NA   ~10대    1
26    2022-12-01 4852       정기권       NA   ~10대    1
27    2022-12-01 4860       정기권       NA   ~10대    1
28    2022-12-01 4871       정기권       NA   ~10대    1
29    2022-12-01 4875       정기권       NA   ~10대    1
30    2022-12-01 4891       정기권       NA   ~10대    1
⋮     ⋮          ⋮          ⋮            ⋮    ⋮        ⋮
94482 2022-12-31 2621       정기권       M    70대이상 1
94483 2022-12-31 2634       정기권       M    70대이상 1
94484 2022-12-31 2648       정기권       M    70대이상 1
94485 2022-12-31 4486       정기권       M    70대이상 1
94486 2022-12-31 4862       정기권       M    70대이상 1
94487 2022-12-31 5751       정기권       M    70대이상 1
94488 2022-12-31 1208       정기권       M    70대이상 1
94489 2022-12-31 1210       정기권       M    70대이상 1
94490 2022-12-31 1275       정기권       M    기타     1
94491 2022-12-31 1289       정기권       M    기타     1
94492 2022-12-31 1295       정기권       M    기타     1
94493 2022-12-31 1297       정기권       M    기타     1
94494 2022-12-31 2605       정기권       M    기타     1
94495 2022-12-31 2608       정기권       M    기타     1
94496 2022-12-31 2617       정기권       M    기타     2
94497 2022-12-31 2622       정기권       M    기타     2
94498 2022-12-31 2623       정기권       M    기타     2
94499 2022-12-31 2651       정기권       M    기타     2
94500 2022-12-31 2656       정기권       M    기타     1
94501 2022-12-31 4453       정기권       M    기타     1
94502 2022-12-31 4460       정기권       M    기타     1
94503 2022-12-31 4480       정기권       M    기타     2
94504 2022-12-31 4481       정기권       M    기타     1
94505 2022-12-31 4870       정기권       M    기타     1
94506 2022-12-31 4891       정기권       M    기타     1
94507 2022-12-31 1206       정기권       M    기타     1
94508 2022-12-31 1201       정기권       M    기타     1
94509 2022-12-31 1231       정기권       M    기타     1
94510 2022-12-31 1227       정기권       M    기타     1
94511 2022-12-31 1246       정기권       M    기타     1

In [ ]:
selected_DF12$`대여구분코드`<-ifelse(selected_DF12$`대여구분코드`=='정기권',1,0)

In [ ]:
selected_DF12$`성별`<-ifelse(selected_DF12$`성별`=='M',0,ifelse(selected_DF12$`성별`=='F',1,2))

In [ ]:
selected_DF12$`연령대`<-ifelse(selected_DF12$`연령대`=='~10대',0,ifelse(selected_DF12$`연령대`=='20대',1,
ifelse(selected_DF12$`연령대`=='30대',2,ifelse(selected_DF12$`연령대`=='40대',3,ifelse(selected_DF12$`연령대`=='50대',4,
ifelse(selected_DF12$`연령대`=='60대',5,ifelse(selected_DF12$`연령대`=='70대이상',6,7)))))))

In [ ]:
selected_DF12

      대여일자   대여소번호 대여구분코드 성별 연령대 이용건수
1     2022-12-01 1260       1            NA   0      1
2     2022-12-01 1264       1            NA   0      1
3     2022-12-01 1265       1            NA   0      1
4     2022-12-01 1269       1            NA   0      1
5     2022-12-01 1274       1            NA   0      1
6     2022-12-01 1277       1            NA   0      2
7     2022-12-01 1282       1            NA   0      1
8     2022-12-01 1288       1            NA   0      1
9     2022-12-01 1291       1            NA   0      1
10    2022-12-01 1299       1            NA   0      1
11    2022-12-01 2601       1            NA   0      1
12    2022-12-01 2608       1            NA   0      1
13    2022-12-01 2611       1            NA   0      1
14    2022-12-01 2615       1            NA   0      1
15    2022-12-01 2644       1            NA   0      1
16    2022-12-01 2630       1            NA   0      1
17    2022-12-01 2635       1            NA   0      1
18    2022-12-01 2651       1            NA   0      1
19    2022-12-01 4464       1            NA   0      1
20    2022-12-01 4465       1            NA   0      2
21    2022-12-01 4467       1            NA   0      2
22    2022-12-01 4467       1            NA   0      1
23    2022-12-01 4478       1            NA   0      1
24    2022-12-01 4479       1            NA   0      1
25    2022-12-01 4491       1            NA   0      1
26    2022-12-01 4852       1            NA   0      1
27    2022-12-01 4860       1            NA   0      1
28    2022-12-01 4871       1            NA   0      1
29    2022-12-01 4875       1            NA   0      1
30    2022-12-01 4891       1            NA   0      1
⋮     ⋮          ⋮          ⋮            ⋮    ⋮      ⋮
94482 2022-12-31 2621       1            0    6      1
94483 2022-12-31 2634       1            0    6      1
94484 2022-12-31 2648       1            0    6      1
94485 2022-12-31 4486       1            0    6      1
94486 2022-12-31 4862       1            0    6      1
94487 2022-12-31 5751       1            0    6      1
94488 2022-12-31 1208       1            0    6      1
94489 2022-12-31 1210       1            0    6      1
94490 2022-12-31 1275       1            0    7      1
94491 2022-12-31 1289       1            0    7      1
94492 2022-12-31 1295       1            0    7      1
94493 2022-12-31 1297       1            0    7      1
94494 2022-12-31 2605       1            0    7      1
94495 2022-12-31 2608       1            0    7      1
94496 2022-12-31 2617       1            0    7      2
94497 2022-12-31 2622       1            0    7      2
94498 2022-12-31 2623       1            0    7      2
94499 2022-12-31 2651       1            0    7      2
94500 2022-12-31 2656       1            0    7      1
94501 2022-12-31 4453       1            0    7      1
94502 2022-12-31 4460       1            0    7      1
94503 2022-12-31 4480       1            0    7      2
94504 2022-12-31 4481       1            0    7      1
94505 2022-12-31 4870       1            0    7      1
94506 2022-12-31 4891       1            0    7      1
94507 2022-12-31 1206       1            0    7      1
94508 2022-12-31 1201       1            0    7      1
94509 2022-12-31 1231       1            0    7      1
94510 2022-12-31 1227       1            0    7      1
94511 2022-12-31 1246       1            0    7      1

In [ ]:
write.csv(selected_DF12,file="/content/전처리_송파구_서울특별시 공공자전거 이용정보(일별)_22.12.csv",row.names=FALSE, na="")

In [ ]:
selected_DF12$'평일/주말' <- ifelse(selected_DF12$대여일자 %in% date$date_time, date$weekend[match(selected_DF12$대여일자, date$date_time)], 2)
selected_DF12

      대여일자   대여소번호 대여구분코드 성별 연령대 이용건수 평일/주말
1     2022-12-01 1260       1            NA   0      1        0
2     2022-12-01 1264       1            NA   0      1        0
3     2022-12-01 1265       1            NA   0      1        0
4     2022-12-01 1269       1            NA   0      1        0
5     2022-12-01 1274       1            NA   0      1        0
6     2022-12-01 1277       1            NA   0      2        0
7     2022-12-01 1282       1            NA   0      1        0
8     2022-12-01 1288       1            NA   0      1        0
9     2022-12-01 1291       1            NA   0      1        0
10    2022-12-01 1299       1            NA   0      1        0
11    2022-12-01 2601       1            NA   0      1        0
12    2022-12-01 2608       1            NA   0      1        0
13    2022-12-01 2611       1            NA   0      1        0
14    2022-12-01 2615       1            NA   0      1        0
15    2022-12-01 2644       1            NA   0      1        0
16    2022-12-01 2630       1            NA   0      1        0
17    2022-12-01 2635       1            NA   0      1        0
18    2022-12-01 2651       1            NA   0      1        0
19    2022-12-01 4464       1            NA   0      1        0
20    2022-12-01 4465       1            NA   0      2        0
21    2022-12-01 4467       1            NA   0      2        0
22    2022-12-01 4467       1            NA   0      1        0
23    2022-12-01 4478       1            NA   0      1        0
24    2022-12-01 4479       1            NA   0      1        0
25    2022-12-01 4491       1            NA   0      1        0
26    2022-12-01 4852       1            NA   0      1        0
27    2022-12-01 4860       1            NA   0      1        0
28    2022-12-01 4871       1            NA   0      1        0
29    2022-12-01 4875       1            NA   0      1        0
30    2022-12-01 4891       1            NA   0      1        0
⋮     ⋮          ⋮          ⋮            ⋮    ⋮      ⋮        ⋮
94482 2022-12-31 2621       1            0    6      1        1
94483 2022-12-31 2634       1            0    6      1        1
94484 2022-12-31 2648       1            0    6      1        1
94485 2022-12-31 4486       1            0    6      1        1
94486 2022-12-31 4862       1            0    6      1        1
94487 2022-12-31 5751       1            0    6      1        1
94488 2022-12-31 1208       1            0    6      1        1
94489 2022-12-31 1210       1            0    6      1        1
94490 2022-12-31 1275       1            0    7      1        1
94491 2022-12-31 1289       1            0    7      1        1
94492 2022-12-31 1295       1            0    7      1        1
94493 2022-12-31 1297       1            0    7      1        1
94494 2022-12-31 2605       1            0    7      1        1
94495 2022-12-31 2608       1            0    7      1        1
94496 2022-12-31 2617       1            0    7      2        1
94497 2022-12-31 2622       1            0    7      2        1
94498 2022-12-31 2623       1            0    7      2        1
94499 2022-12-31 2651       1            0    7      2        1
94500 2022-12-31 2656       1            0    7      1        1
94501 2022-12-31 4453       1            0    7      1        1
94502 2022-12-31 4460       1            0    7      1        1
94503 2022-12-31 4480       1            0    7      2        1
94504 2022-12-31 4481       1            0    7      1        1
94505 2022-12-31 4870       1            0    7      1        1
94506 2022-12-31 4891       1            0    7      1        1
94507 2022-12-31 1206       1            0    7      1        1
94508 2022-12-31 1201       1            0    7      1        1
94509 2022-12-31 1231       1            0    7      1        1
94510 2022-12-31 1227       1            0    7      1        1
94511 2022-12-31 1246       1            0    7      1        1

In [ ]:
selected_DF12 <- selected_DF12 %>% select('평일/주말', '대여구분코드', '성별', '연령대', '이용건수')
selected_DF12

      평일/주말 대여구분코드 성별 연령대 이용건수
1     0         1            NA   0      1
2     0         1            NA   0      1
3     0         1            NA   0      1
4     0         1            NA   0      1
5     0         1            NA   0      1
6     0         1            NA   0      2
7     0         1            NA   0      1
8     0         1            NA   0      1
9     0         1            NA   0      1
10    0         1            NA   0      1
11    0         1            NA   0      1
12    0         1            NA   0      1
13    0         1            NA   0      1
14    0         1            NA   0      1
15    0         1            NA   0      1
16    0         1            NA   0      1
17    0         1            NA   0      1
18    0         1            NA   0      1
19    0         1            NA   0      1
20    0         1            NA   0      2
21    0         1            NA   0      2
22    0         1            NA   0      1
23    0         1            NA   0      1
24    0         1            NA   0      1
25    0         1            NA   0      1
26    0         1            NA   0      1
27    0         1            NA   0      1
28    0         1            NA   0      1
29    0         1            NA   0      1
30    0         1            NA   0      1
⋮     ⋮         ⋮            ⋮    ⋮      ⋮
94482 1         1            0    6      1
94483 1         1            0    6      1
94484 1         1            0    6      1
94485 1         1            0    6      1
94486 1         1            0    6      1
94487 1         1            0    6      1
94488 1         1            0    6      1
94489 1         1            0    6      1
94490 1         1            0    7      1
94491 1         1            0    7      1
94492 1         1            0    7      1
94493 1         1            0    7      1
94494 1         1            0    7      1
94495 1         1            0    7      1
94496 1         1            0    7      2
94497 1         1            0    7      2
94498 1         1            0    7      2
94499 1         1            0    7      2
94500 1         1            0    7      1
94501 1         1            0    7      1
94502 1         1            0    7      1
94503 1         1            0    7      2
94504 1         1            0    7      1
94505 1         1            0    7      1
94506 1         1            0    7      1
94507 1         1            0    7      1
94508 1         1            0    7      1
94509 1         1            0    7      1
94510 1         1            0    7      1
94511 1         1            0    7      1

In [ ]:
summarized_data_12 <- selected_DF12 %>%
  group_by(대여일자) %>%
  summarise(이용건수_합계 = sum(이용건수, na.rm = TRUE))

summarized_data_12

   대여일자   이용건수_합계
1  2022-12-01 6622
2  2022-12-02 7477
3  2022-12-03 5605
4  2022-12-04 4245
5  2022-12-05 7054
6  2022-12-06 6962
7  2022-12-07 8637
8  2022-12-08 9114
9  2022-12-09 9603
10 2022-12-10 6910
11 2022-12-11 5684
12 2022-12-12 5478
13 2022-12-13 5050
14 2022-12-14 4975
15 2022-12-15 3565
16 2022-12-16 4202
17 2022-12-17 3226
18 2022-12-18 2359
19 2022-12-19 4995
20 2022-12-20 6058
21 2022-12-21 2516
22 2022-12-22 2750
23 2022-12-23 2487
24 2022-12-24 2297
25 2022-12-25 2090
26 2022-12-26 4235
27 2022-12-27 4825
28 2022-12-28 4536
29 2022-12-29 4986
30 2022-12-30 4680
31 2022-12-31 3713

## **일자별 0/1파일**

In [14]:
#https://drive.google.com/file/d/1JlXF_LH5XdOvcfjdbFAqyhn2QUJJYUgz/view?usp=sharing
system("gdown --id 1JlXF_LH5XdOvcfjdbFAqyhn2QUJJYUgz")
system("ls",TRUE)

[1] "서울특별시 공공자전거 이용정보(일별)_22.01.csv"
[2] "일자별 날씨정보.csv"
[3] "sample_data"

In [15]:
date<- read_csv("/content/일자별 날씨정보.csv", locale = locale('ko',encoding = 'cp949'))%>% as_tibble()
date

Rows: 365 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl  (7): rain, wind_speed, humidity, avrage_temp, weekend, discomfort_index...
date (1): date_time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    date_time  rain wind_speed humidity avrage_temp weekend discomfort_index
1   2022-01-01 0    1.5        46.3     -4.3        1       34.2
2   2022-01-02 1    2.3        57.9     -1.3        1       36.2
3   2022-01-03 0    1.8        58.3     -1.9        0       35.3
4   2022-01-04 0    2.4        51.8     -2.5        0       35.6
5   2022-01-05 0    1.7        47.6     -2.8        0       35.9
6   2022-01-06 0    2.3        47.1     -2.2        0       36.8
7   2022-01-07 0    1.5        47.1     -1.6        0       37.5
8   2022-01-08 0    1.7        64.3      0.3        1       37.5
9   2022-01-09 0    1.7        71.5      1.3        1       38.0
10  2022-01-10 1    2.0        68.3      0.5        0       37.3
11  2022-01-11 1    4.0        55.5     -7.4        0       28.3
12  2022-01-12 0    2.4        47.8     -7.7        0       29.6
13  2022-01-13 0    3.3        45.8     -6.4        0       31.7
14  2022-01-14 0    1.7        41.8     -4.8        0       34.4
15  2022-01-15 0    1.9        48.3     -1.0        1       38.1
16  2022-01-16 0    3.3        54.5     -2.0        1       35.8
17  2022-01-17 1    2.2        59.9     -5.8        0       29.6
18  2022-01-18 0    2.3        47.9     -5.6        0       32.3
19  2022-01-19 1    2.1        72.3     -5.3        0       27.9
20  2022-01-20 0    1.8        63.5     -5.0        0       30.0
21  2022-01-21 0    1.8        55.6     -2.7        0       34.7
22  2022-01-22 0    1.7        52.4      0.3        1       39.2
23  2022-01-23 0    1.7        52.4      2.0        1       41.5
24  2022-01-24 0    3.5        56.0      4.6        0       44.6
25  2022-01-25 1    2.3        80.0      2.8        0       39.3
26  2022-01-26 0    2.2        62.8      1.3        0       39.2
27  2022-01-27 0    2.1        50.0     -1.1        0       37.7
28  2022-01-28 0    2.8        51.6     -2.7        0       35.4
29  2022-01-29 0    2.4        48.9     -3.6        1       34.6
30  2022-01-30 0    2.2        45.4     -2.8        1       36.3
⋮   ⋮          ⋮    ⋮          ⋮        ⋮           ⋮       ⋮
336 2022-12-02 0    1.7        42.0      -2.5       0       37.2
337 2022-12-03 1    2.6        70.5       2.1       1       39.4
338 2022-12-04 0    2.8        38.9      -3.5       1       36.6
339 2022-12-05 0    2.4        41.9      -3.1       0       36.5
340 2022-12-06 1    2.4        62.8       0.9       0       38.6
341 2022-12-07 1    2.7        60.4       4.9       0       44.6
342 2022-12-08 0    1.4        57.5       3.7       0       43.2
343 2022-12-09 0    2.0        60.8       4.5       0       44.0
344 2022-12-10 0    1.3        46.5       2.6       1       43.0
345 2022-12-11 0    1.8        52.5       1.6       1       40.9
346 2022-12-12 1    1.7        73.4       2.0       0       38.9
347 2022-12-13 1    3.5        70.8       0.0       0       36.2
348 2022-12-14 0    3.2        50.1      -8.4       0       28.2
349 2022-12-15 1    2.5        79.1      -4.5       0       27.8
350 2022-12-16 0    2.0        56.9      -6.3       0       29.5
351 2022-12-17 1    2.7        52.0      -7.0       1       29.6
352 2022-12-18 0    2.6        47.1      -9.5       1       27.4
353 2022-12-19 0    1.7        55.6      -7.0       0       28.8
354 2022-12-20 0    2.2        55.8      -3.2       0       34.0
355 2022-12-21 1    2.7        82.4      -0.1       0       34.4
356 2022-12-22 0    4.4        60.5      -7.8       0       26.7
357 2022-12-23 0    4.3        60.5     -11.8       0       21.0
358 2022-12-24 0    1.8        54.9      -8.4       1       27.1
359 2022-12-25 0    1.7        66.5      -5.4       1       28.9
360 2022-12-26 0    1.4        68.4      -3.9       0       30.7
361 2022-12-27 0    1.8        69.8      -2.6       0       32.4
362 2022-12-28 1    2.5        58.1      -3.3       0       33.4
363 2022-12-29 0    1.7        56.3      -2.9       0       34.3
364 2022-12-30 0    1.9        65.6      -1.8       0       34.3
365 2022-12-31 0    1.4        65.5      -1.2       1       35.2
    wind_direction
1    20
2   290
3   250
4   250
5    50
6   290
7   250
8   200
9   270
10  250
11  290
12  290
13  270
14  180
15   50
16  250
17  270
18  290
19  320
20  320
21   50
22  290
23  250
24   70
25  270
26  320
27  290
28  290
29  320
30  270
⋮   ⋮
336  50
337 270
338 290
339 290
340 250
341 270
342 290
343 290
344 290
345 290
346 180
347 290
348 320
349 320
350 290
351 290
352 270
353 290
354  50
355 290
356 270
357 290
358  50
359 250
360  50
361 290
362 290
363 290
364 270
365 340

In [16]:
date<- date%>% select(c(date_time, weekend))
date

    date_time  weekend
1   2022-01-01 1
2   2022-01-02 1
3   2022-01-03 0
4   2022-01-04 0
5   2022-01-05 0
6   2022-01-06 0
7   2022-01-07 0
8   2022-01-08 1
9   2022-01-09 1
10  2022-01-10 0
11  2022-01-11 0
12  2022-01-12 0
13  2022-01-13 0
14  2022-01-14 0
15  2022-01-15 1
16  2022-01-16 1
17  2022-01-17 0
18  2022-01-18 0
19  2022-01-19 0
20  2022-01-20 0
21  2022-01-21 0
22  2022-01-22 1
23  2022-01-23 1
24  2022-01-24 0
25  2022-01-25 0
26  2022-01-26 0
27  2022-01-27 0
28  2022-01-28 0
29  2022-01-29 1
30  2022-01-30 1
⋮   ⋮          ⋮
336 2022-12-02 0
337 2022-12-03 1
338 2022-12-04 1
339 2022-12-05 0
340 2022-12-06 0
341 2022-12-07 0
342 2022-12-08 0
343 2022-12-09 0
344 2022-12-10 1
345 2022-12-11 1
346 2022-12-12 0
347 2022-12-13 0
348 2022-12-14 0
349 2022-12-15 0
350 2022-12-16 0
351 2022-12-17 1
352 2022-12-18 1
353 2022-12-19 0
354 2022-12-20 0
355 2022-12-21 0
356 2022-12-22 0
357 2022-12-23 0
358 2022-12-24 1
359 2022-12-25 1
360 2022-12-26 0
361 2022-12-27 0
362 2022-12-28 0
363 2022-12-29 0
364 2022-12-30 0
365 2022-12-31 1

## **1월 사용량**

In [ ]:
selected_DF01$'평일/주말' <- ifelse(selected_DF01$대여일자 %in% date$date_time, date$weekend[match(selected_DF01$대여일자, date$date_time)], 2)
selected_DF01

Warning message:
“Unknown or uninitialised column: `대여일자`.”

ERROR: ignored

In [ ]:
selected_DF01 <- selected_DF01 %>% select('평일/주말', '대여구분코드', '성별', '연령대코드', '이용건수')
selected_DF01

      평일/주말 대여구분코드 성별 연령대코드 이용건수
1     1         0            NA   4          1
2     1         1             2   1          4
3     1         1             2   2          2
4     1         1             2   3          1
5     1         1             2   4          1
6     1         1            NA   1          1
7     1         1             1   1          1
8     1         1             1   2          1
9     1         1             1   3          1
10    1         1             1   7          2
11    1         1             0   1          1
12    1         1             0   2          2
13    1         1             0   4          1
14    1         1             0   7          1
15    1         0             2   0          1
16    1         0             2   1          1
17    1         0             1   4          1
18    1         0             0   2          1
19    1         0             0   3          1
20    1         0             0   4          1
21    1         1             2   2          1
22    1         1             2   3          1
23    1         1             2   4          2
24    1         1             1   0          2
25    1         1             1   2          1
26    1         1             1   4          1
27    1         1             0   0          1
28    1         1             0   1          2
29    1         1             0   3          1
30    1         1             0   4          2
⋮     ⋮         ⋮            ⋮    ⋮          ⋮
66043 1         1             2   1          1
66044 1         1             0   1          1
66045 1         1             0   7          1
66046 1         0             1   3          1
66047 1         1             1   2          1
66048 1         0             1   4          1
66049 1         1             2   2          1
66050 1         1             2   4          1
66051 1         1             1   2          1
66052 1         1             1   3          1
66053 1         1             1   4          1
66054 1         1             0   1          1
66055 1         1             0   2          1
66056 1         1             0   3          1
66057 1         0             2   1          1
66058 1         1             2   1          1
66059 1         0             2   1          1
66060 1         0             1   1          1
66061 1         0             1   7          2
66062 1         0             0   2          1
66063 1         1             2   0          2
66064 1         1             2   1          1
66065 1         1             2   2          2
66066 1         1            NA   2          1
66067 1         1             1   1          1
66068 1         1             1   2          3
66069 1         1             1   7          1
66070 1         1             0   2          4
66071 1         1             0   3          1
66072 1         1             0   7          2

In [ ]:
selected_DF01$'사용량'<-